export const DEFAULT_SETTINGS = Object.freeze({
  iconEnabled: true,
  showOnCollectionPages: true,
  showOnHomePage: true,
  showOnProductImage: true,
  autoInjectHeaderIcon: false,
  heartColor: "#222222",
  iconPositionX: 100,
  iconPositionY: 0,
  pageTitle: "My Wishlist",
  emptyStateTitle: "Your wishlist is empty",
  emptyStateBody: "Save products you love and come back to them anytime.",
  floatingButtonEnabled: true,
  floatingButtonText: "My Wishlist",
  floatingButtonPosition: "bottom-right",
  addButtonEnabled: true,
  addButtonText: "Add to wishlist",
  removeButtonText: "Remove from wishlist",
  showPrices: true,
  showAddToCart: true,
  requireLogin: false,
  onlyInStock: false,
  excludedTags: "",
  customCss: "",
  setupEmbedConfirmed: false,
});

export const PUBLIC_SETTING_KEYS = [
  "iconEnabled",
  "showOnCollectionPages",
  "showOnHomePage",
  "showOnProductImage",
  "autoInjectHeaderIcon",
  "heartColor",
  "iconPositionX",
  "iconPositionY",
  "pageTitle",
  "emptyStateTitle",
  "emptyStateBody",
  "floatingButtonEnabled",
  "floatingButtonText",
  "floatingButtonPosition",
  "addButtonEnabled",
  "addButtonText",
  "removeButtonText",
  "showPrices",
  "showAddToCart",
  "requireLogin",
  "onlyInStock",
  "customCss",
];

export const PROFILE_SETTING_KEYS = [...PUBLIC_SETTING_KEYS, "excludedTags"];

export const ADMIN_SETTING_KEYS = [...PROFILE_SETTING_KEYS];
