
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model stores
 * 
 */
export type stores = Prisma.storesModel
/**
 * Model session
 * 
 */
export type session = Prisma.sessionModel
/**
 * Model store_settings
 * 
 */
export type store_settings = Prisma.store_settingsModel
/**
 * Model wishlist
 * 
 */
export type wishlist = Prisma.wishlistModel
/**
 * Model wishlist_item
 * 
 */
export type wishlist_item = Prisma.wishlist_itemModel
/**
 * Model wishlist_event
 * 
 */
export type wishlist_event = Prisma.wishlist_eventModel
/**
 * Model wishlist_sync_operation
 * 
 */
export type wishlist_sync_operation = Prisma.wishlist_sync_operationModel
/**
 * Model wishlist_settings_profile
 * 
 */
export type wishlist_settings_profile = Prisma.wishlist_settings_profileModel
