
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.ts"
import * as $Class from "./internal/class.ts"
import * as Prisma from "./internal/prismaNamespace.ts"

export * as $Enums from './enums.ts'
export * from "./enums.ts"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient({
 *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
 * })
 * // Fetch zero or more Stores
 * const stores = await prisma.stores.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model stores
 * 
 */
export type stores = Prisma.storesModel
/**
 * Model session
 * 
 */
export type session = Prisma.sessionModel
/**
 * Model store_settings
 * 
 */
export type store_settings = Prisma.store_settingsModel
/**
 * Model wishlist
 * 
 */
export type wishlist = Prisma.wishlistModel
/**
 * Model wishlist_item
 * 
 */
export type wishlist_item = Prisma.wishlist_itemModel
/**
 * Model wishlist_event
 * 
 */
export type wishlist_event = Prisma.wishlist_eventModel
/**
 * Model wishlist_sync_operation
 * 
 */
export type wishlist_sync_operation = Prisma.wishlist_sync_operationModel
/**
 * Model wishlist_settings_profile
 * 
 */
export type wishlist_settings_profile = Prisma.wishlist_settings_profileModel
