
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `stores` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model stores
 * 
 */
export type storesModel = runtime.Types.Result.DefaultSelection<Prisma.$storesPayload>

export type AggregateStores = {
  _count: StoresCountAggregateOutputType | null
  _min: StoresMinAggregateOutputType | null
  _max: StoresMaxAggregateOutputType | null
}

export type StoresMinAggregateOutputType = {
  shop: string | null
  isActive: boolean | null
  installedAt: Date | null
  updatedAt: Date | null
}

export type StoresMaxAggregateOutputType = {
  shop: string | null
  isActive: boolean | null
  installedAt: Date | null
  updatedAt: Date | null
}

export type StoresCountAggregateOutputType = {
  shop: number
  isActive: number
  installedAt: number
  updatedAt: number
  _all: number
}


export type StoresMinAggregateInputType = {
  shop?: true
  isActive?: true
  installedAt?: true
  updatedAt?: true
}

export type StoresMaxAggregateInputType = {
  shop?: true
  isActive?: true
  installedAt?: true
  updatedAt?: true
}

export type StoresCountAggregateInputType = {
  shop?: true
  isActive?: true
  installedAt?: true
  updatedAt?: true
  _all?: true
}

export type StoresAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which stores to aggregate.
   */
  where?: Prisma.storesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of stores to fetch.
   */
  orderBy?: Prisma.storesOrderByWithRelationInput | Prisma.storesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.storesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` stores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` stores.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned stores
  **/
  _count?: true | StoresCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StoresMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StoresMaxAggregateInputType
}

export type GetStoresAggregateType<T extends StoresAggregateArgs> = {
      [P in keyof T & keyof AggregateStores]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStores[P]>
    : Prisma.GetScalarType<T[P], AggregateStores[P]>
}




export type storesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.storesWhereInput
  orderBy?: Prisma.storesOrderByWithAggregationInput | Prisma.storesOrderByWithAggregationInput[]
  by: Prisma.StoresScalarFieldEnum[] | Prisma.StoresScalarFieldEnum
  having?: Prisma.storesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StoresCountAggregateInputType | true
  _min?: StoresMinAggregateInputType
  _max?: StoresMaxAggregateInputType
}

export type StoresGroupByOutputType = {
  shop: string
  isActive: boolean
  installedAt: Date
  updatedAt: Date
  _count: StoresCountAggregateOutputType | null
  _min: StoresMinAggregateOutputType | null
  _max: StoresMaxAggregateOutputType | null
}

export type GetStoresGroupByPayload<T extends storesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StoresGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StoresGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StoresGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StoresGroupByOutputType[P]>
      }
    >
  >



export type storesWhereInput = {
  AND?: Prisma.storesWhereInput | Prisma.storesWhereInput[]
  OR?: Prisma.storesWhereInput[]
  NOT?: Prisma.storesWhereInput | Prisma.storesWhereInput[]
  shop?: Prisma.StringFilter<"stores"> | string
  isActive?: Prisma.BoolFilter<"stores"> | boolean
  installedAt?: Prisma.DateTimeFilter<"stores"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"stores"> | Date | string
  settings?: Prisma.XOR<Prisma.Store_settingsNullableScalarRelationFilter, Prisma.store_settingsWhereInput> | null
  wishlists?: Prisma.WishlistListRelationFilter
  events?: Prisma.Wishlist_eventListRelationFilter
  syncOperations?: Prisma.Wishlist_sync_operationListRelationFilter
}

export type storesOrderByWithRelationInput = {
  shop?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  installedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  settings?: Prisma.store_settingsOrderByWithRelationInput
  wishlists?: Prisma.wishlistOrderByRelationAggregateInput
  events?: Prisma.wishlist_eventOrderByRelationAggregateInput
  syncOperations?: Prisma.wishlist_sync_operationOrderByRelationAggregateInput
}

export type storesWhereUniqueInput = Prisma.AtLeast<{
  shop?: string
  AND?: Prisma.storesWhereInput | Prisma.storesWhereInput[]
  OR?: Prisma.storesWhereInput[]
  NOT?: Prisma.storesWhereInput | Prisma.storesWhereInput[]
  isActive?: Prisma.BoolFilter<"stores"> | boolean
  installedAt?: Prisma.DateTimeFilter<"stores"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"stores"> | Date | string
  settings?: Prisma.XOR<Prisma.Store_settingsNullableScalarRelationFilter, Prisma.store_settingsWhereInput> | null
  wishlists?: Prisma.WishlistListRelationFilter
  events?: Prisma.Wishlist_eventListRelationFilter
  syncOperations?: Prisma.Wishlist_sync_operationListRelationFilter
}, "shop">

export type storesOrderByWithAggregationInput = {
  shop?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  installedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.storesCountOrderByAggregateInput
  _max?: Prisma.storesMaxOrderByAggregateInput
  _min?: Prisma.storesMinOrderByAggregateInput
}

export type storesScalarWhereWithAggregatesInput = {
  AND?: Prisma.storesScalarWhereWithAggregatesInput | Prisma.storesScalarWhereWithAggregatesInput[]
  OR?: Prisma.storesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.storesScalarWhereWithAggregatesInput | Prisma.storesScalarWhereWithAggregatesInput[]
  shop?: Prisma.StringWithAggregatesFilter<"stores"> | string
  isActive?: Prisma.BoolWithAggregatesFilter<"stores"> | boolean
  installedAt?: Prisma.DateTimeWithAggregatesFilter<"stores"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"stores"> | Date | string
}

export type storesCreateInput = {
  shop: string
  isActive?: boolean
  installedAt?: Date | string
  updatedAt?: Date | string
  settings?: Prisma.store_settingsCreateNestedOneWithoutStoreInput
  wishlists?: Prisma.wishlistCreateNestedManyWithoutStoreInput
  events?: Prisma.wishlist_eventCreateNestedManyWithoutStoreInput
  syncOperations?: Prisma.wishlist_sync_operationCreateNestedManyWithoutStoreInput
}

export type storesUncheckedCreateInput = {
  shop: string
  isActive?: boolean
  installedAt?: Date | string
  updatedAt?: Date | string
  settings?: Prisma.store_settingsUncheckedCreateNestedOneWithoutStoreInput
  wishlists?: Prisma.wishlistUncheckedCreateNestedManyWithoutStoreInput
  events?: Prisma.wishlist_eventUncheckedCreateNestedManyWithoutStoreInput
  syncOperations?: Prisma.wishlist_sync_operationUncheckedCreateNestedManyWithoutStoreInput
}

export type storesUpdateInput = {
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  installedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  settings?: Prisma.store_settingsUpdateOneWithoutStoreNestedInput
  wishlists?: Prisma.wishlistUpdateManyWithoutStoreNestedInput
  events?: Prisma.wishlist_eventUpdateManyWithoutStoreNestedInput
  syncOperations?: Prisma.wishlist_sync_operationUpdateManyWithoutStoreNestedInput
}

export type storesUncheckedUpdateInput = {
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  installedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  settings?: Prisma.store_settingsUncheckedUpdateOneWithoutStoreNestedInput
  wishlists?: Prisma.wishlistUncheckedUpdateManyWithoutStoreNestedInput
  events?: Prisma.wishlist_eventUncheckedUpdateManyWithoutStoreNestedInput
  syncOperations?: Prisma.wishlist_sync_operationUncheckedUpdateManyWithoutStoreNestedInput
}

export type storesCreateManyInput = {
  shop: string
  isActive?: boolean
  installedAt?: Date | string
  updatedAt?: Date | string
}

export type storesUpdateManyMutationInput = {
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  installedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type storesUncheckedUpdateManyInput = {
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  installedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type storesCountOrderByAggregateInput = {
  shop?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  installedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type storesMaxOrderByAggregateInput = {
  shop?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  installedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type storesMinOrderByAggregateInput = {
  shop?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  installedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StoresScalarRelationFilter = {
  is?: Prisma.storesWhereInput
  isNot?: Prisma.storesWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type storesCreateNestedOneWithoutSettingsInput = {
  create?: Prisma.XOR<Prisma.storesCreateWithoutSettingsInput, Prisma.storesUncheckedCreateWithoutSettingsInput>
  connectOrCreate?: Prisma.storesCreateOrConnectWithoutSettingsInput
  connect?: Prisma.storesWhereUniqueInput
}

export type storesUpdateOneRequiredWithoutSettingsNestedInput = {
  create?: Prisma.XOR<Prisma.storesCreateWithoutSettingsInput, Prisma.storesUncheckedCreateWithoutSettingsInput>
  connectOrCreate?: Prisma.storesCreateOrConnectWithoutSettingsInput
  upsert?: Prisma.storesUpsertWithoutSettingsInput
  connect?: Prisma.storesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.storesUpdateToOneWithWhereWithoutSettingsInput, Prisma.storesUpdateWithoutSettingsInput>, Prisma.storesUncheckedUpdateWithoutSettingsInput>
}

export type storesCreateNestedOneWithoutWishlistsInput = {
  create?: Prisma.XOR<Prisma.storesCreateWithoutWishlistsInput, Prisma.storesUncheckedCreateWithoutWishlistsInput>
  connectOrCreate?: Prisma.storesCreateOrConnectWithoutWishlistsInput
  connect?: Prisma.storesWhereUniqueInput
}

export type storesUpdateOneRequiredWithoutWishlistsNestedInput = {
  create?: Prisma.XOR<Prisma.storesCreateWithoutWishlistsInput, Prisma.storesUncheckedCreateWithoutWishlistsInput>
  connectOrCreate?: Prisma.storesCreateOrConnectWithoutWishlistsInput
  upsert?: Prisma.storesUpsertWithoutWishlistsInput
  connect?: Prisma.storesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.storesUpdateToOneWithWhereWithoutWishlistsInput, Prisma.storesUpdateWithoutWishlistsInput>, Prisma.storesUncheckedUpdateWithoutWishlistsInput>
}

export type storesCreateNestedOneWithoutEventsInput = {
  create?: Prisma.XOR<Prisma.storesCreateWithoutEventsInput, Prisma.storesUncheckedCreateWithoutEventsInput>
  connectOrCreate?: Prisma.storesCreateOrConnectWithoutEventsInput
  connect?: Prisma.storesWhereUniqueInput
}

export type storesUpdateOneRequiredWithoutEventsNestedInput = {
  create?: Prisma.XOR<Prisma.storesCreateWithoutEventsInput, Prisma.storesUncheckedCreateWithoutEventsInput>
  connectOrCreate?: Prisma.storesCreateOrConnectWithoutEventsInput
  upsert?: Prisma.storesUpsertWithoutEventsInput
  connect?: Prisma.storesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.storesUpdateToOneWithWhereWithoutEventsInput, Prisma.storesUpdateWithoutEventsInput>, Prisma.storesUncheckedUpdateWithoutEventsInput>
}

export type storesCreateNestedOneWithoutSyncOperationsInput = {
  create?: Prisma.XOR<Prisma.storesCreateWithoutSyncOperationsInput, Prisma.storesUncheckedCreateWithoutSyncOperationsInput>
  connectOrCreate?: Prisma.storesCreateOrConnectWithoutSyncOperationsInput
  connect?: Prisma.storesWhereUniqueInput
}

export type storesUpdateOneRequiredWithoutSyncOperationsNestedInput = {
  create?: Prisma.XOR<Prisma.storesCreateWithoutSyncOperationsInput, Prisma.storesUncheckedCreateWithoutSyncOperationsInput>
  connectOrCreate?: Prisma.storesCreateOrConnectWithoutSyncOperationsInput
  upsert?: Prisma.storesUpsertWithoutSyncOperationsInput
  connect?: Prisma.storesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.storesUpdateToOneWithWhereWithoutSyncOperationsInput, Prisma.storesUpdateWithoutSyncOperationsInput>, Prisma.storesUncheckedUpdateWithoutSyncOperationsInput>
}

export type storesCreateWithoutSettingsInput = {
  shop: string
  isActive?: boolean
  installedAt?: Date | string
  updatedAt?: Date | string
  wishlists?: Prisma.wishlistCreateNestedManyWithoutStoreInput
  events?: Prisma.wishlist_eventCreateNestedManyWithoutStoreInput
  syncOperations?: Prisma.wishlist_sync_operationCreateNestedManyWithoutStoreInput
}

export type storesUncheckedCreateWithoutSettingsInput = {
  shop: string
  isActive?: boolean
  installedAt?: Date | string
  updatedAt?: Date | string
  wishlists?: Prisma.wishlistUncheckedCreateNestedManyWithoutStoreInput
  events?: Prisma.wishlist_eventUncheckedCreateNestedManyWithoutStoreInput
  syncOperations?: Prisma.wishlist_sync_operationUncheckedCreateNestedManyWithoutStoreInput
}

export type storesCreateOrConnectWithoutSettingsInput = {
  where: Prisma.storesWhereUniqueInput
  create: Prisma.XOR<Prisma.storesCreateWithoutSettingsInput, Prisma.storesUncheckedCreateWithoutSettingsInput>
}

export type storesUpsertWithoutSettingsInput = {
  update: Prisma.XOR<Prisma.storesUpdateWithoutSettingsInput, Prisma.storesUncheckedUpdateWithoutSettingsInput>
  create: Prisma.XOR<Prisma.storesCreateWithoutSettingsInput, Prisma.storesUncheckedCreateWithoutSettingsInput>
  where?: Prisma.storesWhereInput
}

export type storesUpdateToOneWithWhereWithoutSettingsInput = {
  where?: Prisma.storesWhereInput
  data: Prisma.XOR<Prisma.storesUpdateWithoutSettingsInput, Prisma.storesUncheckedUpdateWithoutSettingsInput>
}

export type storesUpdateWithoutSettingsInput = {
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  installedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  wishlists?: Prisma.wishlistUpdateManyWithoutStoreNestedInput
  events?: Prisma.wishlist_eventUpdateManyWithoutStoreNestedInput
  syncOperations?: Prisma.wishlist_sync_operationUpdateManyWithoutStoreNestedInput
}

export type storesUncheckedUpdateWithoutSettingsInput = {
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  installedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  wishlists?: Prisma.wishlistUncheckedUpdateManyWithoutStoreNestedInput
  events?: Prisma.wishlist_eventUncheckedUpdateManyWithoutStoreNestedInput
  syncOperations?: Prisma.wishlist_sync_operationUncheckedUpdateManyWithoutStoreNestedInput
}

export type storesCreateWithoutWishlistsInput = {
  shop: string
  isActive?: boolean
  installedAt?: Date | string
  updatedAt?: Date | string
  settings?: Prisma.store_settingsCreateNestedOneWithoutStoreInput
  events?: Prisma.wishlist_eventCreateNestedManyWithoutStoreInput
  syncOperations?: Prisma.wishlist_sync_operationCreateNestedManyWithoutStoreInput
}

export type storesUncheckedCreateWithoutWishlistsInput = {
  shop: string
  isActive?: boolean
  installedAt?: Date | string
  updatedAt?: Date | string
  settings?: Prisma.store_settingsUncheckedCreateNestedOneWithoutStoreInput
  events?: Prisma.wishlist_eventUncheckedCreateNestedManyWithoutStoreInput
  syncOperations?: Prisma.wishlist_sync_operationUncheckedCreateNestedManyWithoutStoreInput
}

export type storesCreateOrConnectWithoutWishlistsInput = {
  where: Prisma.storesWhereUniqueInput
  create: Prisma.XOR<Prisma.storesCreateWithoutWishlistsInput, Prisma.storesUncheckedCreateWithoutWishlistsInput>
}

export type storesUpsertWithoutWishlistsInput = {
  update: Prisma.XOR<Prisma.storesUpdateWithoutWishlistsInput, Prisma.storesUncheckedUpdateWithoutWishlistsInput>
  create: Prisma.XOR<Prisma.storesCreateWithoutWishlistsInput, Prisma.storesUncheckedCreateWithoutWishlistsInput>
  where?: Prisma.storesWhereInput
}

export type storesUpdateToOneWithWhereWithoutWishlistsInput = {
  where?: Prisma.storesWhereInput
  data: Prisma.XOR<Prisma.storesUpdateWithoutWishlistsInput, Prisma.storesUncheckedUpdateWithoutWishlistsInput>
}

export type storesUpdateWithoutWishlistsInput = {
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  installedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  settings?: Prisma.store_settingsUpdateOneWithoutStoreNestedInput
  events?: Prisma.wishlist_eventUpdateManyWithoutStoreNestedInput
  syncOperations?: Prisma.wishlist_sync_operationUpdateManyWithoutStoreNestedInput
}

export type storesUncheckedUpdateWithoutWishlistsInput = {
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  installedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  settings?: Prisma.store_settingsUncheckedUpdateOneWithoutStoreNestedInput
  events?: Prisma.wishlist_eventUncheckedUpdateManyWithoutStoreNestedInput
  syncOperations?: Prisma.wishlist_sync_operationUncheckedUpdateManyWithoutStoreNestedInput
}

export type storesCreateWithoutEventsInput = {
  shop: string
  isActive?: boolean
  installedAt?: Date | string
  updatedAt?: Date | string
  settings?: Prisma.store_settingsCreateNestedOneWithoutStoreInput
  wishlists?: Prisma.wishlistCreateNestedManyWithoutStoreInput
  syncOperations?: Prisma.wishlist_sync_operationCreateNestedManyWithoutStoreInput
}

export type storesUncheckedCreateWithoutEventsInput = {
  shop: string
  isActive?: boolean
  installedAt?: Date | string
  updatedAt?: Date | string
  settings?: Prisma.store_settingsUncheckedCreateNestedOneWithoutStoreInput
  wishlists?: Prisma.wishlistUncheckedCreateNestedManyWithoutStoreInput
  syncOperations?: Prisma.wishlist_sync_operationUncheckedCreateNestedManyWithoutStoreInput
}

export type storesCreateOrConnectWithoutEventsInput = {
  where: Prisma.storesWhereUniqueInput
  create: Prisma.XOR<Prisma.storesCreateWithoutEventsInput, Prisma.storesUncheckedCreateWithoutEventsInput>
}

export type storesUpsertWithoutEventsInput = {
  update: Prisma.XOR<Prisma.storesUpdateWithoutEventsInput, Prisma.storesUncheckedUpdateWithoutEventsInput>
  create: Prisma.XOR<Prisma.storesCreateWithoutEventsInput, Prisma.storesUncheckedCreateWithoutEventsInput>
  where?: Prisma.storesWhereInput
}

export type storesUpdateToOneWithWhereWithoutEventsInput = {
  where?: Prisma.storesWhereInput
  data: Prisma.XOR<Prisma.storesUpdateWithoutEventsInput, Prisma.storesUncheckedUpdateWithoutEventsInput>
}

export type storesUpdateWithoutEventsInput = {
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  installedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  settings?: Prisma.store_settingsUpdateOneWithoutStoreNestedInput
  wishlists?: Prisma.wishlistUpdateManyWithoutStoreNestedInput
  syncOperations?: Prisma.wishlist_sync_operationUpdateManyWithoutStoreNestedInput
}

export type storesUncheckedUpdateWithoutEventsInput = {
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  installedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  settings?: Prisma.store_settingsUncheckedUpdateOneWithoutStoreNestedInput
  wishlists?: Prisma.wishlistUncheckedUpdateManyWithoutStoreNestedInput
  syncOperations?: Prisma.wishlist_sync_operationUncheckedUpdateManyWithoutStoreNestedInput
}

export type storesCreateWithoutSyncOperationsInput = {
  shop: string
  isActive?: boolean
  installedAt?: Date | string
  updatedAt?: Date | string
  settings?: Prisma.store_settingsCreateNestedOneWithoutStoreInput
  wishlists?: Prisma.wishlistCreateNestedManyWithoutStoreInput
  events?: Prisma.wishlist_eventCreateNestedManyWithoutStoreInput
}

export type storesUncheckedCreateWithoutSyncOperationsInput = {
  shop: string
  isActive?: boolean
  installedAt?: Date | string
  updatedAt?: Date | string
  settings?: Prisma.store_settingsUncheckedCreateNestedOneWithoutStoreInput
  wishlists?: Prisma.wishlistUncheckedCreateNestedManyWithoutStoreInput
  events?: Prisma.wishlist_eventUncheckedCreateNestedManyWithoutStoreInput
}

export type storesCreateOrConnectWithoutSyncOperationsInput = {
  where: Prisma.storesWhereUniqueInput
  create: Prisma.XOR<Prisma.storesCreateWithoutSyncOperationsInput, Prisma.storesUncheckedCreateWithoutSyncOperationsInput>
}

export type storesUpsertWithoutSyncOperationsInput = {
  update: Prisma.XOR<Prisma.storesUpdateWithoutSyncOperationsInput, Prisma.storesUncheckedUpdateWithoutSyncOperationsInput>
  create: Prisma.XOR<Prisma.storesCreateWithoutSyncOperationsInput, Prisma.storesUncheckedCreateWithoutSyncOperationsInput>
  where?: Prisma.storesWhereInput
}

export type storesUpdateToOneWithWhereWithoutSyncOperationsInput = {
  where?: Prisma.storesWhereInput
  data: Prisma.XOR<Prisma.storesUpdateWithoutSyncOperationsInput, Prisma.storesUncheckedUpdateWithoutSyncOperationsInput>
}

export type storesUpdateWithoutSyncOperationsInput = {
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  installedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  settings?: Prisma.store_settingsUpdateOneWithoutStoreNestedInput
  wishlists?: Prisma.wishlistUpdateManyWithoutStoreNestedInput
  events?: Prisma.wishlist_eventUpdateManyWithoutStoreNestedInput
}

export type storesUncheckedUpdateWithoutSyncOperationsInput = {
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  installedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  settings?: Prisma.store_settingsUncheckedUpdateOneWithoutStoreNestedInput
  wishlists?: Prisma.wishlistUncheckedUpdateManyWithoutStoreNestedInput
  events?: Prisma.wishlist_eventUncheckedUpdateManyWithoutStoreNestedInput
}


/**
 * Count Type StoresCountOutputType
 */

export type StoresCountOutputType = {
  wishlists: number
  events: number
  syncOperations: number
}

export type StoresCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  wishlists?: boolean | StoresCountOutputTypeCountWishlistsArgs
  events?: boolean | StoresCountOutputTypeCountEventsArgs
  syncOperations?: boolean | StoresCountOutputTypeCountSyncOperationsArgs
}

/**
 * StoresCountOutputType without action
 */
export type StoresCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoresCountOutputType
   */
  select?: Prisma.StoresCountOutputTypeSelect<ExtArgs> | null
}

/**
 * StoresCountOutputType without action
 */
export type StoresCountOutputTypeCountWishlistsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.wishlistWhereInput
}

/**
 * StoresCountOutputType without action
 */
export type StoresCountOutputTypeCountEventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.wishlist_eventWhereInput
}

/**
 * StoresCountOutputType without action
 */
export type StoresCountOutputTypeCountSyncOperationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.wishlist_sync_operationWhereInput
}


export type storesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  shop?: boolean
  isActive?: boolean
  installedAt?: boolean
  updatedAt?: boolean
  settings?: boolean | Prisma.stores$settingsArgs<ExtArgs>
  wishlists?: boolean | Prisma.stores$wishlistsArgs<ExtArgs>
  events?: boolean | Prisma.stores$eventsArgs<ExtArgs>
  syncOperations?: boolean | Prisma.stores$syncOperationsArgs<ExtArgs>
  _count?: boolean | Prisma.StoresCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["stores"]>

export type storesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  shop?: boolean
  isActive?: boolean
  installedAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["stores"]>

export type storesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  shop?: boolean
  isActive?: boolean
  installedAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["stores"]>

export type storesSelectScalar = {
  shop?: boolean
  isActive?: boolean
  installedAt?: boolean
  updatedAt?: boolean
}

export type storesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"shop" | "isActive" | "installedAt" | "updatedAt", ExtArgs["result"]["stores"]>
export type storesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  settings?: boolean | Prisma.stores$settingsArgs<ExtArgs>
  wishlists?: boolean | Prisma.stores$wishlistsArgs<ExtArgs>
  events?: boolean | Prisma.stores$eventsArgs<ExtArgs>
  syncOperations?: boolean | Prisma.stores$syncOperationsArgs<ExtArgs>
  _count?: boolean | Prisma.StoresCountOutputTypeDefaultArgs<ExtArgs>
}
export type storesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type storesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $storesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "stores"
  objects: {
    settings: Prisma.$store_settingsPayload<ExtArgs> | null
    wishlists: Prisma.$wishlistPayload<ExtArgs>[]
    events: Prisma.$wishlist_eventPayload<ExtArgs>[]
    syncOperations: Prisma.$wishlist_sync_operationPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    shop: string
    isActive: boolean
    installedAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["stores"]>
  composites: {}
}

export type storesGetPayload<S extends boolean | null | undefined | storesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$storesPayload, S>

export type storesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<storesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StoresCountAggregateInputType | true
  }

export interface storesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['stores'], meta: { name: 'stores' } }
  /**
   * Find zero or one Stores that matches the filter.
   * @param {storesFindUniqueArgs} args - Arguments to find a Stores
   * @example
   * // Get one Stores
   * const stores = await prisma.stores.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends storesFindUniqueArgs>(args: Prisma.SelectSubset<T, storesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__storesClient<runtime.Types.Result.GetResult<Prisma.$storesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Stores that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {storesFindUniqueOrThrowArgs} args - Arguments to find a Stores
   * @example
   * // Get one Stores
   * const stores = await prisma.stores.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends storesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, storesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__storesClient<runtime.Types.Result.GetResult<Prisma.$storesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Stores that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {storesFindFirstArgs} args - Arguments to find a Stores
   * @example
   * // Get one Stores
   * const stores = await prisma.stores.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends storesFindFirstArgs>(args?: Prisma.SelectSubset<T, storesFindFirstArgs<ExtArgs>>): Prisma.Prisma__storesClient<runtime.Types.Result.GetResult<Prisma.$storesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Stores that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {storesFindFirstOrThrowArgs} args - Arguments to find a Stores
   * @example
   * // Get one Stores
   * const stores = await prisma.stores.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends storesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, storesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__storesClient<runtime.Types.Result.GetResult<Prisma.$storesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Stores that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {storesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Stores
   * const stores = await prisma.stores.findMany()
   * 
   * // Get first 10 Stores
   * const stores = await prisma.stores.findMany({ take: 10 })
   * 
   * // Only select the `shop`
   * const storesWithShopOnly = await prisma.stores.findMany({ select: { shop: true } })
   * 
   */
  findMany<T extends storesFindManyArgs>(args?: Prisma.SelectSubset<T, storesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$storesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Stores.
   * @param {storesCreateArgs} args - Arguments to create a Stores.
   * @example
   * // Create one Stores
   * const Stores = await prisma.stores.create({
   *   data: {
   *     // ... data to create a Stores
   *   }
   * })
   * 
   */
  create<T extends storesCreateArgs>(args: Prisma.SelectSubset<T, storesCreateArgs<ExtArgs>>): Prisma.Prisma__storesClient<runtime.Types.Result.GetResult<Prisma.$storesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Stores.
   * @param {storesCreateManyArgs} args - Arguments to create many Stores.
   * @example
   * // Create many Stores
   * const stores = await prisma.stores.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends storesCreateManyArgs>(args?: Prisma.SelectSubset<T, storesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Stores and returns the data saved in the database.
   * @param {storesCreateManyAndReturnArgs} args - Arguments to create many Stores.
   * @example
   * // Create many Stores
   * const stores = await prisma.stores.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Stores and only return the `shop`
   * const storesWithShopOnly = await prisma.stores.createManyAndReturn({
   *   select: { shop: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends storesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, storesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$storesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Stores.
   * @param {storesDeleteArgs} args - Arguments to delete one Stores.
   * @example
   * // Delete one Stores
   * const Stores = await prisma.stores.delete({
   *   where: {
   *     // ... filter to delete one Stores
   *   }
   * })
   * 
   */
  delete<T extends storesDeleteArgs>(args: Prisma.SelectSubset<T, storesDeleteArgs<ExtArgs>>): Prisma.Prisma__storesClient<runtime.Types.Result.GetResult<Prisma.$storesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Stores.
   * @param {storesUpdateArgs} args - Arguments to update one Stores.
   * @example
   * // Update one Stores
   * const stores = await prisma.stores.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends storesUpdateArgs>(args: Prisma.SelectSubset<T, storesUpdateArgs<ExtArgs>>): Prisma.Prisma__storesClient<runtime.Types.Result.GetResult<Prisma.$storesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Stores.
   * @param {storesDeleteManyArgs} args - Arguments to filter Stores to delete.
   * @example
   * // Delete a few Stores
   * const { count } = await prisma.stores.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends storesDeleteManyArgs>(args?: Prisma.SelectSubset<T, storesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Stores.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {storesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Stores
   * const stores = await prisma.stores.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends storesUpdateManyArgs>(args: Prisma.SelectSubset<T, storesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Stores and returns the data updated in the database.
   * @param {storesUpdateManyAndReturnArgs} args - Arguments to update many Stores.
   * @example
   * // Update many Stores
   * const stores = await prisma.stores.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Stores and only return the `shop`
   * const storesWithShopOnly = await prisma.stores.updateManyAndReturn({
   *   select: { shop: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends storesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, storesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$storesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Stores.
   * @param {storesUpsertArgs} args - Arguments to update or create a Stores.
   * @example
   * // Update or create a Stores
   * const stores = await prisma.stores.upsert({
   *   create: {
   *     // ... data to create a Stores
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Stores we want to update
   *   }
   * })
   */
  upsert<T extends storesUpsertArgs>(args: Prisma.SelectSubset<T, storesUpsertArgs<ExtArgs>>): Prisma.Prisma__storesClient<runtime.Types.Result.GetResult<Prisma.$storesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Stores.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {storesCountArgs} args - Arguments to filter Stores to count.
   * @example
   * // Count the number of Stores
   * const count = await prisma.stores.count({
   *   where: {
   *     // ... the filter for the Stores we want to count
   *   }
   * })
  **/
  count<T extends storesCountArgs>(
    args?: Prisma.Subset<T, storesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StoresCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Stores.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoresAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StoresAggregateArgs>(args: Prisma.Subset<T, StoresAggregateArgs>): Prisma.PrismaPromise<GetStoresAggregateType<T>>

  /**
   * Group by Stores.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {storesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends storesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: storesGroupByArgs['orderBy'] }
      : { orderBy?: storesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, storesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStoresGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the stores model
 */
readonly fields: storesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for stores.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__storesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  settings<T extends Prisma.stores$settingsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.stores$settingsArgs<ExtArgs>>): Prisma.Prisma__store_settingsClient<runtime.Types.Result.GetResult<Prisma.$store_settingsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  wishlists<T extends Prisma.stores$wishlistsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.stores$wishlistsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlistPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  events<T extends Prisma.stores$eventsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.stores$eventsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlist_eventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  syncOperations<T extends Prisma.stores$syncOperationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.stores$syncOperationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlist_sync_operationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the stores model
 */
export interface storesFieldRefs {
  readonly shop: Prisma.FieldRef<"stores", 'String'>
  readonly isActive: Prisma.FieldRef<"stores", 'Boolean'>
  readonly installedAt: Prisma.FieldRef<"stores", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"stores", 'DateTime'>
}
    

// Custom InputTypes
/**
 * stores findUnique
 */
export type storesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the stores
   */
  select?: Prisma.storesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the stores
   */
  omit?: Prisma.storesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.storesInclude<ExtArgs> | null
  /**
   * Filter, which stores to fetch.
   */
  where: Prisma.storesWhereUniqueInput
}

/**
 * stores findUniqueOrThrow
 */
export type storesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the stores
   */
  select?: Prisma.storesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the stores
   */
  omit?: Prisma.storesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.storesInclude<ExtArgs> | null
  /**
   * Filter, which stores to fetch.
   */
  where: Prisma.storesWhereUniqueInput
}

/**
 * stores findFirst
 */
export type storesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the stores
   */
  select?: Prisma.storesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the stores
   */
  omit?: Prisma.storesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.storesInclude<ExtArgs> | null
  /**
   * Filter, which stores to fetch.
   */
  where?: Prisma.storesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of stores to fetch.
   */
  orderBy?: Prisma.storesOrderByWithRelationInput | Prisma.storesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for stores.
   */
  cursor?: Prisma.storesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` stores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` stores.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of stores.
   */
  distinct?: Prisma.StoresScalarFieldEnum | Prisma.StoresScalarFieldEnum[]
}

/**
 * stores findFirstOrThrow
 */
export type storesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the stores
   */
  select?: Prisma.storesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the stores
   */
  omit?: Prisma.storesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.storesInclude<ExtArgs> | null
  /**
   * Filter, which stores to fetch.
   */
  where?: Prisma.storesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of stores to fetch.
   */
  orderBy?: Prisma.storesOrderByWithRelationInput | Prisma.storesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for stores.
   */
  cursor?: Prisma.storesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` stores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` stores.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of stores.
   */
  distinct?: Prisma.StoresScalarFieldEnum | Prisma.StoresScalarFieldEnum[]
}

/**
 * stores findMany
 */
export type storesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the stores
   */
  select?: Prisma.storesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the stores
   */
  omit?: Prisma.storesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.storesInclude<ExtArgs> | null
  /**
   * Filter, which stores to fetch.
   */
  where?: Prisma.storesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of stores to fetch.
   */
  orderBy?: Prisma.storesOrderByWithRelationInput | Prisma.storesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing stores.
   */
  cursor?: Prisma.storesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` stores from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` stores.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of stores.
   */
  distinct?: Prisma.StoresScalarFieldEnum | Prisma.StoresScalarFieldEnum[]
}

/**
 * stores create
 */
export type storesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the stores
   */
  select?: Prisma.storesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the stores
   */
  omit?: Prisma.storesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.storesInclude<ExtArgs> | null
  /**
   * The data needed to create a stores.
   */
  data: Prisma.XOR<Prisma.storesCreateInput, Prisma.storesUncheckedCreateInput>
}

/**
 * stores createMany
 */
export type storesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many stores.
   */
  data: Prisma.storesCreateManyInput | Prisma.storesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * stores createManyAndReturn
 */
export type storesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the stores
   */
  select?: Prisma.storesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the stores
   */
  omit?: Prisma.storesOmit<ExtArgs> | null
  /**
   * The data used to create many stores.
   */
  data: Prisma.storesCreateManyInput | Prisma.storesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * stores update
 */
export type storesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the stores
   */
  select?: Prisma.storesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the stores
   */
  omit?: Prisma.storesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.storesInclude<ExtArgs> | null
  /**
   * The data needed to update a stores.
   */
  data: Prisma.XOR<Prisma.storesUpdateInput, Prisma.storesUncheckedUpdateInput>
  /**
   * Choose, which stores to update.
   */
  where: Prisma.storesWhereUniqueInput
}

/**
 * stores updateMany
 */
export type storesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update stores.
   */
  data: Prisma.XOR<Prisma.storesUpdateManyMutationInput, Prisma.storesUncheckedUpdateManyInput>
  /**
   * Filter which stores to update
   */
  where?: Prisma.storesWhereInput
  /**
   * Limit how many stores to update.
   */
  limit?: number
}

/**
 * stores updateManyAndReturn
 */
export type storesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the stores
   */
  select?: Prisma.storesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the stores
   */
  omit?: Prisma.storesOmit<ExtArgs> | null
  /**
   * The data used to update stores.
   */
  data: Prisma.XOR<Prisma.storesUpdateManyMutationInput, Prisma.storesUncheckedUpdateManyInput>
  /**
   * Filter which stores to update
   */
  where?: Prisma.storesWhereInput
  /**
   * Limit how many stores to update.
   */
  limit?: number
}

/**
 * stores upsert
 */
export type storesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the stores
   */
  select?: Prisma.storesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the stores
   */
  omit?: Prisma.storesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.storesInclude<ExtArgs> | null
  /**
   * The filter to search for the stores to update in case it exists.
   */
  where: Prisma.storesWhereUniqueInput
  /**
   * In case the stores found by the `where` argument doesn't exist, create a new stores with this data.
   */
  create: Prisma.XOR<Prisma.storesCreateInput, Prisma.storesUncheckedCreateInput>
  /**
   * In case the stores was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.storesUpdateInput, Prisma.storesUncheckedUpdateInput>
}

/**
 * stores delete
 */
export type storesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the stores
   */
  select?: Prisma.storesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the stores
   */
  omit?: Prisma.storesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.storesInclude<ExtArgs> | null
  /**
   * Filter which stores to delete.
   */
  where: Prisma.storesWhereUniqueInput
}

/**
 * stores deleteMany
 */
export type storesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which stores to delete
   */
  where?: Prisma.storesWhereInput
  /**
   * Limit how many stores to delete.
   */
  limit?: number
}

/**
 * stores.settings
 */
export type stores$settingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the store_settings
   */
  select?: Prisma.store_settingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the store_settings
   */
  omit?: Prisma.store_settingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.store_settingsInclude<ExtArgs> | null
  where?: Prisma.store_settingsWhereInput
}

/**
 * stores.wishlists
 */
export type stores$wishlistsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist
   */
  select?: Prisma.wishlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist
   */
  omit?: Prisma.wishlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlistInclude<ExtArgs> | null
  where?: Prisma.wishlistWhereInput
  orderBy?: Prisma.wishlistOrderByWithRelationInput | Prisma.wishlistOrderByWithRelationInput[]
  cursor?: Prisma.wishlistWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.WishlistScalarFieldEnum | Prisma.WishlistScalarFieldEnum[]
}

/**
 * stores.events
 */
export type stores$eventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_event
   */
  select?: Prisma.wishlist_eventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_event
   */
  omit?: Prisma.wishlist_eventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_eventInclude<ExtArgs> | null
  where?: Prisma.wishlist_eventWhereInput
  orderBy?: Prisma.wishlist_eventOrderByWithRelationInput | Prisma.wishlist_eventOrderByWithRelationInput[]
  cursor?: Prisma.wishlist_eventWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Wishlist_eventScalarFieldEnum | Prisma.Wishlist_eventScalarFieldEnum[]
}

/**
 * stores.syncOperations
 */
export type stores$syncOperationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_sync_operation
   */
  select?: Prisma.wishlist_sync_operationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_sync_operation
   */
  omit?: Prisma.wishlist_sync_operationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_sync_operationInclude<ExtArgs> | null
  where?: Prisma.wishlist_sync_operationWhereInput
  orderBy?: Prisma.wishlist_sync_operationOrderByWithRelationInput | Prisma.wishlist_sync_operationOrderByWithRelationInput[]
  cursor?: Prisma.wishlist_sync_operationWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Wishlist_sync_operationScalarFieldEnum | Prisma.Wishlist_sync_operationScalarFieldEnum[]
}

/**
 * stores without action
 */
export type storesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the stores
   */
  select?: Prisma.storesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the stores
   */
  omit?: Prisma.storesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.storesInclude<ExtArgs> | null
}
