
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `wishlist_event` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model wishlist_event
 * 
 */
export type wishlist_eventModel = runtime.Types.Result.DefaultSelection<Prisma.$wishlist_eventPayload>

export type AggregateWishlist_event = {
  _count: Wishlist_eventCountAggregateOutputType | null
  _avg: Wishlist_eventAvgAggregateOutputType | null
  _sum: Wishlist_eventSumAggregateOutputType | null
  _min: Wishlist_eventMinAggregateOutputType | null
  _max: Wishlist_eventMaxAggregateOutputType | null
}

export type Wishlist_eventAvgAggregateOutputType = {
  value: runtime.Decimal | null
}

export type Wishlist_eventSumAggregateOutputType = {
  value: runtime.Decimal | null
}

export type Wishlist_eventMinAggregateOutputType = {
  id: string | null
  shop: string | null
  wishlistId: string | null
  type: string | null
  productId: string | null
  variantId: string | null
  value: runtime.Decimal | null
  createdAt: Date | null
}

export type Wishlist_eventMaxAggregateOutputType = {
  id: string | null
  shop: string | null
  wishlistId: string | null
  type: string | null
  productId: string | null
  variantId: string | null
  value: runtime.Decimal | null
  createdAt: Date | null
}

export type Wishlist_eventCountAggregateOutputType = {
  id: number
  shop: number
  wishlistId: number
  type: number
  productId: number
  variantId: number
  value: number
  createdAt: number
  _all: number
}


export type Wishlist_eventAvgAggregateInputType = {
  value?: true
}

export type Wishlist_eventSumAggregateInputType = {
  value?: true
}

export type Wishlist_eventMinAggregateInputType = {
  id?: true
  shop?: true
  wishlistId?: true
  type?: true
  productId?: true
  variantId?: true
  value?: true
  createdAt?: true
}

export type Wishlist_eventMaxAggregateInputType = {
  id?: true
  shop?: true
  wishlistId?: true
  type?: true
  productId?: true
  variantId?: true
  value?: true
  createdAt?: true
}

export type Wishlist_eventCountAggregateInputType = {
  id?: true
  shop?: true
  wishlistId?: true
  type?: true
  productId?: true
  variantId?: true
  value?: true
  createdAt?: true
  _all?: true
}

export type Wishlist_eventAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which wishlist_event to aggregate.
   */
  where?: Prisma.wishlist_eventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlist_events to fetch.
   */
  orderBy?: Prisma.wishlist_eventOrderByWithRelationInput | Prisma.wishlist_eventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.wishlist_eventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlist_events from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlist_events.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned wishlist_events
  **/
  _count?: true | Wishlist_eventCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Wishlist_eventAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Wishlist_eventSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Wishlist_eventMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Wishlist_eventMaxAggregateInputType
}

export type GetWishlist_eventAggregateType<T extends Wishlist_eventAggregateArgs> = {
      [P in keyof T & keyof AggregateWishlist_event]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWishlist_event[P]>
    : Prisma.GetScalarType<T[P], AggregateWishlist_event[P]>
}




export type wishlist_eventGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.wishlist_eventWhereInput
  orderBy?: Prisma.wishlist_eventOrderByWithAggregationInput | Prisma.wishlist_eventOrderByWithAggregationInput[]
  by: Prisma.Wishlist_eventScalarFieldEnum[] | Prisma.Wishlist_eventScalarFieldEnum
  having?: Prisma.wishlist_eventScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Wishlist_eventCountAggregateInputType | true
  _avg?: Wishlist_eventAvgAggregateInputType
  _sum?: Wishlist_eventSumAggregateInputType
  _min?: Wishlist_eventMinAggregateInputType
  _max?: Wishlist_eventMaxAggregateInputType
}

export type Wishlist_eventGroupByOutputType = {
  id: string
  shop: string
  wishlistId: string | null
  type: string
  productId: string | null
  variantId: string | null
  value: runtime.Decimal | null
  createdAt: Date
  _count: Wishlist_eventCountAggregateOutputType | null
  _avg: Wishlist_eventAvgAggregateOutputType | null
  _sum: Wishlist_eventSumAggregateOutputType | null
  _min: Wishlist_eventMinAggregateOutputType | null
  _max: Wishlist_eventMaxAggregateOutputType | null
}

export type GetWishlist_eventGroupByPayload<T extends wishlist_eventGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Wishlist_eventGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Wishlist_eventGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Wishlist_eventGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Wishlist_eventGroupByOutputType[P]>
      }
    >
  >



export type wishlist_eventWhereInput = {
  AND?: Prisma.wishlist_eventWhereInput | Prisma.wishlist_eventWhereInput[]
  OR?: Prisma.wishlist_eventWhereInput[]
  NOT?: Prisma.wishlist_eventWhereInput | Prisma.wishlist_eventWhereInput[]
  id?: Prisma.StringFilter<"wishlist_event"> | string
  shop?: Prisma.StringFilter<"wishlist_event"> | string
  wishlistId?: Prisma.StringNullableFilter<"wishlist_event"> | string | null
  type?: Prisma.StringFilter<"wishlist_event"> | string
  productId?: Prisma.StringNullableFilter<"wishlist_event"> | string | null
  variantId?: Prisma.StringNullableFilter<"wishlist_event"> | string | null
  value?: Prisma.DecimalNullableFilter<"wishlist_event"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeFilter<"wishlist_event"> | Date | string
  store?: Prisma.XOR<Prisma.StoresScalarRelationFilter, Prisma.storesWhereInput>
  wishlist?: Prisma.XOR<Prisma.WishlistNullableScalarRelationFilter, Prisma.wishlistWhereInput> | null
}

export type wishlist_eventOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  shop?: Prisma.SortOrder
  wishlistId?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  productId?: Prisma.SortOrderInput | Prisma.SortOrder
  variantId?: Prisma.SortOrderInput | Prisma.SortOrder
  value?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  store?: Prisma.storesOrderByWithRelationInput
  wishlist?: Prisma.wishlistOrderByWithRelationInput
}

export type wishlist_eventWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.wishlist_eventWhereInput | Prisma.wishlist_eventWhereInput[]
  OR?: Prisma.wishlist_eventWhereInput[]
  NOT?: Prisma.wishlist_eventWhereInput | Prisma.wishlist_eventWhereInput[]
  shop?: Prisma.StringFilter<"wishlist_event"> | string
  wishlistId?: Prisma.StringNullableFilter<"wishlist_event"> | string | null
  type?: Prisma.StringFilter<"wishlist_event"> | string
  productId?: Prisma.StringNullableFilter<"wishlist_event"> | string | null
  variantId?: Prisma.StringNullableFilter<"wishlist_event"> | string | null
  value?: Prisma.DecimalNullableFilter<"wishlist_event"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeFilter<"wishlist_event"> | Date | string
  store?: Prisma.XOR<Prisma.StoresScalarRelationFilter, Prisma.storesWhereInput>
  wishlist?: Prisma.XOR<Prisma.WishlistNullableScalarRelationFilter, Prisma.wishlistWhereInput> | null
}, "id">

export type wishlist_eventOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  shop?: Prisma.SortOrder
  wishlistId?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  productId?: Prisma.SortOrderInput | Prisma.SortOrder
  variantId?: Prisma.SortOrderInput | Prisma.SortOrder
  value?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.wishlist_eventCountOrderByAggregateInput
  _avg?: Prisma.wishlist_eventAvgOrderByAggregateInput
  _max?: Prisma.wishlist_eventMaxOrderByAggregateInput
  _min?: Prisma.wishlist_eventMinOrderByAggregateInput
  _sum?: Prisma.wishlist_eventSumOrderByAggregateInput
}

export type wishlist_eventScalarWhereWithAggregatesInput = {
  AND?: Prisma.wishlist_eventScalarWhereWithAggregatesInput | Prisma.wishlist_eventScalarWhereWithAggregatesInput[]
  OR?: Prisma.wishlist_eventScalarWhereWithAggregatesInput[]
  NOT?: Prisma.wishlist_eventScalarWhereWithAggregatesInput | Prisma.wishlist_eventScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"wishlist_event"> | string
  shop?: Prisma.StringWithAggregatesFilter<"wishlist_event"> | string
  wishlistId?: Prisma.StringNullableWithAggregatesFilter<"wishlist_event"> | string | null
  type?: Prisma.StringWithAggregatesFilter<"wishlist_event"> | string
  productId?: Prisma.StringNullableWithAggregatesFilter<"wishlist_event"> | string | null
  variantId?: Prisma.StringNullableWithAggregatesFilter<"wishlist_event"> | string | null
  value?: Prisma.DecimalNullableWithAggregatesFilter<"wishlist_event"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"wishlist_event"> | Date | string
}

export type wishlist_eventCreateInput = {
  id?: string
  type: string
  productId?: string | null
  variantId?: string | null
  value?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Date | string
  store: Prisma.storesCreateNestedOneWithoutEventsInput
  wishlist?: Prisma.wishlistCreateNestedOneWithoutEventsInput
}

export type wishlist_eventUncheckedCreateInput = {
  id?: string
  shop: string
  wishlistId?: string | null
  type: string
  productId?: string | null
  variantId?: string | null
  value?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Date | string
}

export type wishlist_eventUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  variantId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  value?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  store?: Prisma.storesUpdateOneRequiredWithoutEventsNestedInput
  wishlist?: Prisma.wishlistUpdateOneWithoutEventsNestedInput
}

export type wishlist_eventUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  wishlistId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  variantId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  value?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type wishlist_eventCreateManyInput = {
  id?: string
  shop: string
  wishlistId?: string | null
  type: string
  productId?: string | null
  variantId?: string | null
  value?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Date | string
}

export type wishlist_eventUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  variantId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  value?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type wishlist_eventUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  wishlistId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  variantId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  value?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Wishlist_eventListRelationFilter = {
  every?: Prisma.wishlist_eventWhereInput
  some?: Prisma.wishlist_eventWhereInput
  none?: Prisma.wishlist_eventWhereInput
}

export type wishlist_eventOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type wishlist_eventCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  shop?: Prisma.SortOrder
  wishlistId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  variantId?: Prisma.SortOrder
  value?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type wishlist_eventAvgOrderByAggregateInput = {
  value?: Prisma.SortOrder
}

export type wishlist_eventMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  shop?: Prisma.SortOrder
  wishlistId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  variantId?: Prisma.SortOrder
  value?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type wishlist_eventMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  shop?: Prisma.SortOrder
  wishlistId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  variantId?: Prisma.SortOrder
  value?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type wishlist_eventSumOrderByAggregateInput = {
  value?: Prisma.SortOrder
}

export type wishlist_eventCreateNestedManyWithoutStoreInput = {
  create?: Prisma.XOR<Prisma.wishlist_eventCreateWithoutStoreInput, Prisma.wishlist_eventUncheckedCreateWithoutStoreInput> | Prisma.wishlist_eventCreateWithoutStoreInput[] | Prisma.wishlist_eventUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.wishlist_eventCreateOrConnectWithoutStoreInput | Prisma.wishlist_eventCreateOrConnectWithoutStoreInput[]
  createMany?: Prisma.wishlist_eventCreateManyStoreInputEnvelope
  connect?: Prisma.wishlist_eventWhereUniqueInput | Prisma.wishlist_eventWhereUniqueInput[]
}

export type wishlist_eventUncheckedCreateNestedManyWithoutStoreInput = {
  create?: Prisma.XOR<Prisma.wishlist_eventCreateWithoutStoreInput, Prisma.wishlist_eventUncheckedCreateWithoutStoreInput> | Prisma.wishlist_eventCreateWithoutStoreInput[] | Prisma.wishlist_eventUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.wishlist_eventCreateOrConnectWithoutStoreInput | Prisma.wishlist_eventCreateOrConnectWithoutStoreInput[]
  createMany?: Prisma.wishlist_eventCreateManyStoreInputEnvelope
  connect?: Prisma.wishlist_eventWhereUniqueInput | Prisma.wishlist_eventWhereUniqueInput[]
}

export type wishlist_eventUpdateManyWithoutStoreNestedInput = {
  create?: Prisma.XOR<Prisma.wishlist_eventCreateWithoutStoreInput, Prisma.wishlist_eventUncheckedCreateWithoutStoreInput> | Prisma.wishlist_eventCreateWithoutStoreInput[] | Prisma.wishlist_eventUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.wishlist_eventCreateOrConnectWithoutStoreInput | Prisma.wishlist_eventCreateOrConnectWithoutStoreInput[]
  upsert?: Prisma.wishlist_eventUpsertWithWhereUniqueWithoutStoreInput | Prisma.wishlist_eventUpsertWithWhereUniqueWithoutStoreInput[]
  createMany?: Prisma.wishlist_eventCreateManyStoreInputEnvelope
  set?: Prisma.wishlist_eventWhereUniqueInput | Prisma.wishlist_eventWhereUniqueInput[]
  disconnect?: Prisma.wishlist_eventWhereUniqueInput | Prisma.wishlist_eventWhereUniqueInput[]
  delete?: Prisma.wishlist_eventWhereUniqueInput | Prisma.wishlist_eventWhereUniqueInput[]
  connect?: Prisma.wishlist_eventWhereUniqueInput | Prisma.wishlist_eventWhereUniqueInput[]
  update?: Prisma.wishlist_eventUpdateWithWhereUniqueWithoutStoreInput | Prisma.wishlist_eventUpdateWithWhereUniqueWithoutStoreInput[]
  updateMany?: Prisma.wishlist_eventUpdateManyWithWhereWithoutStoreInput | Prisma.wishlist_eventUpdateManyWithWhereWithoutStoreInput[]
  deleteMany?: Prisma.wishlist_eventScalarWhereInput | Prisma.wishlist_eventScalarWhereInput[]
}

export type wishlist_eventUncheckedUpdateManyWithoutStoreNestedInput = {
  create?: Prisma.XOR<Prisma.wishlist_eventCreateWithoutStoreInput, Prisma.wishlist_eventUncheckedCreateWithoutStoreInput> | Prisma.wishlist_eventCreateWithoutStoreInput[] | Prisma.wishlist_eventUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.wishlist_eventCreateOrConnectWithoutStoreInput | Prisma.wishlist_eventCreateOrConnectWithoutStoreInput[]
  upsert?: Prisma.wishlist_eventUpsertWithWhereUniqueWithoutStoreInput | Prisma.wishlist_eventUpsertWithWhereUniqueWithoutStoreInput[]
  createMany?: Prisma.wishlist_eventCreateManyStoreInputEnvelope
  set?: Prisma.wishlist_eventWhereUniqueInput | Prisma.wishlist_eventWhereUniqueInput[]
  disconnect?: Prisma.wishlist_eventWhereUniqueInput | Prisma.wishlist_eventWhereUniqueInput[]
  delete?: Prisma.wishlist_eventWhereUniqueInput | Prisma.wishlist_eventWhereUniqueInput[]
  connect?: Prisma.wishlist_eventWhereUniqueInput | Prisma.wishlist_eventWhereUniqueInput[]
  update?: Prisma.wishlist_eventUpdateWithWhereUniqueWithoutStoreInput | Prisma.wishlist_eventUpdateWithWhereUniqueWithoutStoreInput[]
  updateMany?: Prisma.wishlist_eventUpdateManyWithWhereWithoutStoreInput | Prisma.wishlist_eventUpdateManyWithWhereWithoutStoreInput[]
  deleteMany?: Prisma.wishlist_eventScalarWhereInput | Prisma.wishlist_eventScalarWhereInput[]
}

export type wishlist_eventCreateNestedManyWithoutWishlistInput = {
  create?: Prisma.XOR<Prisma.wishlist_eventCreateWithoutWishlistInput, Prisma.wishlist_eventUncheckedCreateWithoutWishlistInput> | Prisma.wishlist_eventCreateWithoutWishlistInput[] | Prisma.wishlist_eventUncheckedCreateWithoutWishlistInput[]
  connectOrCreate?: Prisma.wishlist_eventCreateOrConnectWithoutWishlistInput | Prisma.wishlist_eventCreateOrConnectWithoutWishlistInput[]
  createMany?: Prisma.wishlist_eventCreateManyWishlistInputEnvelope
  connect?: Prisma.wishlist_eventWhereUniqueInput | Prisma.wishlist_eventWhereUniqueInput[]
}

export type wishlist_eventUncheckedCreateNestedManyWithoutWishlistInput = {
  create?: Prisma.XOR<Prisma.wishlist_eventCreateWithoutWishlistInput, Prisma.wishlist_eventUncheckedCreateWithoutWishlistInput> | Prisma.wishlist_eventCreateWithoutWishlistInput[] | Prisma.wishlist_eventUncheckedCreateWithoutWishlistInput[]
  connectOrCreate?: Prisma.wishlist_eventCreateOrConnectWithoutWishlistInput | Prisma.wishlist_eventCreateOrConnectWithoutWishlistInput[]
  createMany?: Prisma.wishlist_eventCreateManyWishlistInputEnvelope
  connect?: Prisma.wishlist_eventWhereUniqueInput | Prisma.wishlist_eventWhereUniqueInput[]
}

export type wishlist_eventUpdateManyWithoutWishlistNestedInput = {
  create?: Prisma.XOR<Prisma.wishlist_eventCreateWithoutWishlistInput, Prisma.wishlist_eventUncheckedCreateWithoutWishlistInput> | Prisma.wishlist_eventCreateWithoutWishlistInput[] | Prisma.wishlist_eventUncheckedCreateWithoutWishlistInput[]
  connectOrCreate?: Prisma.wishlist_eventCreateOrConnectWithoutWishlistInput | Prisma.wishlist_eventCreateOrConnectWithoutWishlistInput[]
  upsert?: Prisma.wishlist_eventUpsertWithWhereUniqueWithoutWishlistInput | Prisma.wishlist_eventUpsertWithWhereUniqueWithoutWishlistInput[]
  createMany?: Prisma.wishlist_eventCreateManyWishlistInputEnvelope
  set?: Prisma.wishlist_eventWhereUniqueInput | Prisma.wishlist_eventWhereUniqueInput[]
  disconnect?: Prisma.wishlist_eventWhereUniqueInput | Prisma.wishlist_eventWhereUniqueInput[]
  delete?: Prisma.wishlist_eventWhereUniqueInput | Prisma.wishlist_eventWhereUniqueInput[]
  connect?: Prisma.wishlist_eventWhereUniqueInput | Prisma.wishlist_eventWhereUniqueInput[]
  update?: Prisma.wishlist_eventUpdateWithWhereUniqueWithoutWishlistInput | Prisma.wishlist_eventUpdateWithWhereUniqueWithoutWishlistInput[]
  updateMany?: Prisma.wishlist_eventUpdateManyWithWhereWithoutWishlistInput | Prisma.wishlist_eventUpdateManyWithWhereWithoutWishlistInput[]
  deleteMany?: Prisma.wishlist_eventScalarWhereInput | Prisma.wishlist_eventScalarWhereInput[]
}

export type wishlist_eventUncheckedUpdateManyWithoutWishlistNestedInput = {
  create?: Prisma.XOR<Prisma.wishlist_eventCreateWithoutWishlistInput, Prisma.wishlist_eventUncheckedCreateWithoutWishlistInput> | Prisma.wishlist_eventCreateWithoutWishlistInput[] | Prisma.wishlist_eventUncheckedCreateWithoutWishlistInput[]
  connectOrCreate?: Prisma.wishlist_eventCreateOrConnectWithoutWishlistInput | Prisma.wishlist_eventCreateOrConnectWithoutWishlistInput[]
  upsert?: Prisma.wishlist_eventUpsertWithWhereUniqueWithoutWishlistInput | Prisma.wishlist_eventUpsertWithWhereUniqueWithoutWishlistInput[]
  createMany?: Prisma.wishlist_eventCreateManyWishlistInputEnvelope
  set?: Prisma.wishlist_eventWhereUniqueInput | Prisma.wishlist_eventWhereUniqueInput[]
  disconnect?: Prisma.wishlist_eventWhereUniqueInput | Prisma.wishlist_eventWhereUniqueInput[]
  delete?: Prisma.wishlist_eventWhereUniqueInput | Prisma.wishlist_eventWhereUniqueInput[]
  connect?: Prisma.wishlist_eventWhereUniqueInput | Prisma.wishlist_eventWhereUniqueInput[]
  update?: Prisma.wishlist_eventUpdateWithWhereUniqueWithoutWishlistInput | Prisma.wishlist_eventUpdateWithWhereUniqueWithoutWishlistInput[]
  updateMany?: Prisma.wishlist_eventUpdateManyWithWhereWithoutWishlistInput | Prisma.wishlist_eventUpdateManyWithWhereWithoutWishlistInput[]
  deleteMany?: Prisma.wishlist_eventScalarWhereInput | Prisma.wishlist_eventScalarWhereInput[]
}

export type NullableDecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type wishlist_eventCreateWithoutStoreInput = {
  id?: string
  type: string
  productId?: string | null
  variantId?: string | null
  value?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Date | string
  wishlist?: Prisma.wishlistCreateNestedOneWithoutEventsInput
}

export type wishlist_eventUncheckedCreateWithoutStoreInput = {
  id?: string
  wishlistId?: string | null
  type: string
  productId?: string | null
  variantId?: string | null
  value?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Date | string
}

export type wishlist_eventCreateOrConnectWithoutStoreInput = {
  where: Prisma.wishlist_eventWhereUniqueInput
  create: Prisma.XOR<Prisma.wishlist_eventCreateWithoutStoreInput, Prisma.wishlist_eventUncheckedCreateWithoutStoreInput>
}

export type wishlist_eventCreateManyStoreInputEnvelope = {
  data: Prisma.wishlist_eventCreateManyStoreInput | Prisma.wishlist_eventCreateManyStoreInput[]
  skipDuplicates?: boolean
}

export type wishlist_eventUpsertWithWhereUniqueWithoutStoreInput = {
  where: Prisma.wishlist_eventWhereUniqueInput
  update: Prisma.XOR<Prisma.wishlist_eventUpdateWithoutStoreInput, Prisma.wishlist_eventUncheckedUpdateWithoutStoreInput>
  create: Prisma.XOR<Prisma.wishlist_eventCreateWithoutStoreInput, Prisma.wishlist_eventUncheckedCreateWithoutStoreInput>
}

export type wishlist_eventUpdateWithWhereUniqueWithoutStoreInput = {
  where: Prisma.wishlist_eventWhereUniqueInput
  data: Prisma.XOR<Prisma.wishlist_eventUpdateWithoutStoreInput, Prisma.wishlist_eventUncheckedUpdateWithoutStoreInput>
}

export type wishlist_eventUpdateManyWithWhereWithoutStoreInput = {
  where: Prisma.wishlist_eventScalarWhereInput
  data: Prisma.XOR<Prisma.wishlist_eventUpdateManyMutationInput, Prisma.wishlist_eventUncheckedUpdateManyWithoutStoreInput>
}

export type wishlist_eventScalarWhereInput = {
  AND?: Prisma.wishlist_eventScalarWhereInput | Prisma.wishlist_eventScalarWhereInput[]
  OR?: Prisma.wishlist_eventScalarWhereInput[]
  NOT?: Prisma.wishlist_eventScalarWhereInput | Prisma.wishlist_eventScalarWhereInput[]
  id?: Prisma.StringFilter<"wishlist_event"> | string
  shop?: Prisma.StringFilter<"wishlist_event"> | string
  wishlistId?: Prisma.StringNullableFilter<"wishlist_event"> | string | null
  type?: Prisma.StringFilter<"wishlist_event"> | string
  productId?: Prisma.StringNullableFilter<"wishlist_event"> | string | null
  variantId?: Prisma.StringNullableFilter<"wishlist_event"> | string | null
  value?: Prisma.DecimalNullableFilter<"wishlist_event"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeFilter<"wishlist_event"> | Date | string
}

export type wishlist_eventCreateWithoutWishlistInput = {
  id?: string
  type: string
  productId?: string | null
  variantId?: string | null
  value?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Date | string
  store: Prisma.storesCreateNestedOneWithoutEventsInput
}

export type wishlist_eventUncheckedCreateWithoutWishlistInput = {
  id?: string
  shop: string
  type: string
  productId?: string | null
  variantId?: string | null
  value?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Date | string
}

export type wishlist_eventCreateOrConnectWithoutWishlistInput = {
  where: Prisma.wishlist_eventWhereUniqueInput
  create: Prisma.XOR<Prisma.wishlist_eventCreateWithoutWishlistInput, Prisma.wishlist_eventUncheckedCreateWithoutWishlistInput>
}

export type wishlist_eventCreateManyWishlistInputEnvelope = {
  data: Prisma.wishlist_eventCreateManyWishlistInput | Prisma.wishlist_eventCreateManyWishlistInput[]
  skipDuplicates?: boolean
}

export type wishlist_eventUpsertWithWhereUniqueWithoutWishlistInput = {
  where: Prisma.wishlist_eventWhereUniqueInput
  update: Prisma.XOR<Prisma.wishlist_eventUpdateWithoutWishlistInput, Prisma.wishlist_eventUncheckedUpdateWithoutWishlistInput>
  create: Prisma.XOR<Prisma.wishlist_eventCreateWithoutWishlistInput, Prisma.wishlist_eventUncheckedCreateWithoutWishlistInput>
}

export type wishlist_eventUpdateWithWhereUniqueWithoutWishlistInput = {
  where: Prisma.wishlist_eventWhereUniqueInput
  data: Prisma.XOR<Prisma.wishlist_eventUpdateWithoutWishlistInput, Prisma.wishlist_eventUncheckedUpdateWithoutWishlistInput>
}

export type wishlist_eventUpdateManyWithWhereWithoutWishlistInput = {
  where: Prisma.wishlist_eventScalarWhereInput
  data: Prisma.XOR<Prisma.wishlist_eventUpdateManyMutationInput, Prisma.wishlist_eventUncheckedUpdateManyWithoutWishlistInput>
}

export type wishlist_eventCreateManyStoreInput = {
  id?: string
  wishlistId?: string | null
  type: string
  productId?: string | null
  variantId?: string | null
  value?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Date | string
}

export type wishlist_eventUpdateWithoutStoreInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  variantId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  value?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  wishlist?: Prisma.wishlistUpdateOneWithoutEventsNestedInput
}

export type wishlist_eventUncheckedUpdateWithoutStoreInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  wishlistId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  variantId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  value?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type wishlist_eventUncheckedUpdateManyWithoutStoreInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  wishlistId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  variantId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  value?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type wishlist_eventCreateManyWishlistInput = {
  id?: string
  shop: string
  type: string
  productId?: string | null
  variantId?: string | null
  value?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Date | string
}

export type wishlist_eventUpdateWithoutWishlistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  variantId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  value?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  store?: Prisma.storesUpdateOneRequiredWithoutEventsNestedInput
}

export type wishlist_eventUncheckedUpdateWithoutWishlistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  variantId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  value?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type wishlist_eventUncheckedUpdateManyWithoutWishlistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  variantId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  value?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type wishlist_eventSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  shop?: boolean
  wishlistId?: boolean
  type?: boolean
  productId?: boolean
  variantId?: boolean
  value?: boolean
  createdAt?: boolean
  store?: boolean | Prisma.storesDefaultArgs<ExtArgs>
  wishlist?: boolean | Prisma.wishlist_event$wishlistArgs<ExtArgs>
}, ExtArgs["result"]["wishlist_event"]>

export type wishlist_eventSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  shop?: boolean
  wishlistId?: boolean
  type?: boolean
  productId?: boolean
  variantId?: boolean
  value?: boolean
  createdAt?: boolean
  store?: boolean | Prisma.storesDefaultArgs<ExtArgs>
  wishlist?: boolean | Prisma.wishlist_event$wishlistArgs<ExtArgs>
}, ExtArgs["result"]["wishlist_event"]>

export type wishlist_eventSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  shop?: boolean
  wishlistId?: boolean
  type?: boolean
  productId?: boolean
  variantId?: boolean
  value?: boolean
  createdAt?: boolean
  store?: boolean | Prisma.storesDefaultArgs<ExtArgs>
  wishlist?: boolean | Prisma.wishlist_event$wishlistArgs<ExtArgs>
}, ExtArgs["result"]["wishlist_event"]>

export type wishlist_eventSelectScalar = {
  id?: boolean
  shop?: boolean
  wishlistId?: boolean
  type?: boolean
  productId?: boolean
  variantId?: boolean
  value?: boolean
  createdAt?: boolean
}

export type wishlist_eventOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "shop" | "wishlistId" | "type" | "productId" | "variantId" | "value" | "createdAt", ExtArgs["result"]["wishlist_event"]>
export type wishlist_eventInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  store?: boolean | Prisma.storesDefaultArgs<ExtArgs>
  wishlist?: boolean | Prisma.wishlist_event$wishlistArgs<ExtArgs>
}
export type wishlist_eventIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  store?: boolean | Prisma.storesDefaultArgs<ExtArgs>
  wishlist?: boolean | Prisma.wishlist_event$wishlistArgs<ExtArgs>
}
export type wishlist_eventIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  store?: boolean | Prisma.storesDefaultArgs<ExtArgs>
  wishlist?: boolean | Prisma.wishlist_event$wishlistArgs<ExtArgs>
}

export type $wishlist_eventPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "wishlist_event"
  objects: {
    store: Prisma.$storesPayload<ExtArgs>
    wishlist: Prisma.$wishlistPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    shop: string
    wishlistId: string | null
    type: string
    productId: string | null
    variantId: string | null
    value: runtime.Decimal | null
    createdAt: Date
  }, ExtArgs["result"]["wishlist_event"]>
  composites: {}
}

export type wishlist_eventGetPayload<S extends boolean | null | undefined | wishlist_eventDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$wishlist_eventPayload, S>

export type wishlist_eventCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<wishlist_eventFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Wishlist_eventCountAggregateInputType | true
  }

export interface wishlist_eventDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['wishlist_event'], meta: { name: 'wishlist_event' } }
  /**
   * Find zero or one Wishlist_event that matches the filter.
   * @param {wishlist_eventFindUniqueArgs} args - Arguments to find a Wishlist_event
   * @example
   * // Get one Wishlist_event
   * const wishlist_event = await prisma.wishlist_event.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends wishlist_eventFindUniqueArgs>(args: Prisma.SelectSubset<T, wishlist_eventFindUniqueArgs<ExtArgs>>): Prisma.Prisma__wishlist_eventClient<runtime.Types.Result.GetResult<Prisma.$wishlist_eventPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Wishlist_event that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {wishlist_eventFindUniqueOrThrowArgs} args - Arguments to find a Wishlist_event
   * @example
   * // Get one Wishlist_event
   * const wishlist_event = await prisma.wishlist_event.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends wishlist_eventFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, wishlist_eventFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__wishlist_eventClient<runtime.Types.Result.GetResult<Prisma.$wishlist_eventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Wishlist_event that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_eventFindFirstArgs} args - Arguments to find a Wishlist_event
   * @example
   * // Get one Wishlist_event
   * const wishlist_event = await prisma.wishlist_event.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends wishlist_eventFindFirstArgs>(args?: Prisma.SelectSubset<T, wishlist_eventFindFirstArgs<ExtArgs>>): Prisma.Prisma__wishlist_eventClient<runtime.Types.Result.GetResult<Prisma.$wishlist_eventPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Wishlist_event that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_eventFindFirstOrThrowArgs} args - Arguments to find a Wishlist_event
   * @example
   * // Get one Wishlist_event
   * const wishlist_event = await prisma.wishlist_event.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends wishlist_eventFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, wishlist_eventFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__wishlist_eventClient<runtime.Types.Result.GetResult<Prisma.$wishlist_eventPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Wishlist_events that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_eventFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Wishlist_events
   * const wishlist_events = await prisma.wishlist_event.findMany()
   * 
   * // Get first 10 Wishlist_events
   * const wishlist_events = await prisma.wishlist_event.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const wishlist_eventWithIdOnly = await prisma.wishlist_event.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends wishlist_eventFindManyArgs>(args?: Prisma.SelectSubset<T, wishlist_eventFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlist_eventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Wishlist_event.
   * @param {wishlist_eventCreateArgs} args - Arguments to create a Wishlist_event.
   * @example
   * // Create one Wishlist_event
   * const Wishlist_event = await prisma.wishlist_event.create({
   *   data: {
   *     // ... data to create a Wishlist_event
   *   }
   * })
   * 
   */
  create<T extends wishlist_eventCreateArgs>(args: Prisma.SelectSubset<T, wishlist_eventCreateArgs<ExtArgs>>): Prisma.Prisma__wishlist_eventClient<runtime.Types.Result.GetResult<Prisma.$wishlist_eventPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Wishlist_events.
   * @param {wishlist_eventCreateManyArgs} args - Arguments to create many Wishlist_events.
   * @example
   * // Create many Wishlist_events
   * const wishlist_event = await prisma.wishlist_event.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends wishlist_eventCreateManyArgs>(args?: Prisma.SelectSubset<T, wishlist_eventCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Wishlist_events and returns the data saved in the database.
   * @param {wishlist_eventCreateManyAndReturnArgs} args - Arguments to create many Wishlist_events.
   * @example
   * // Create many Wishlist_events
   * const wishlist_event = await prisma.wishlist_event.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Wishlist_events and only return the `id`
   * const wishlist_eventWithIdOnly = await prisma.wishlist_event.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends wishlist_eventCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, wishlist_eventCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlist_eventPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Wishlist_event.
   * @param {wishlist_eventDeleteArgs} args - Arguments to delete one Wishlist_event.
   * @example
   * // Delete one Wishlist_event
   * const Wishlist_event = await prisma.wishlist_event.delete({
   *   where: {
   *     // ... filter to delete one Wishlist_event
   *   }
   * })
   * 
   */
  delete<T extends wishlist_eventDeleteArgs>(args: Prisma.SelectSubset<T, wishlist_eventDeleteArgs<ExtArgs>>): Prisma.Prisma__wishlist_eventClient<runtime.Types.Result.GetResult<Prisma.$wishlist_eventPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Wishlist_event.
   * @param {wishlist_eventUpdateArgs} args - Arguments to update one Wishlist_event.
   * @example
   * // Update one Wishlist_event
   * const wishlist_event = await prisma.wishlist_event.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends wishlist_eventUpdateArgs>(args: Prisma.SelectSubset<T, wishlist_eventUpdateArgs<ExtArgs>>): Prisma.Prisma__wishlist_eventClient<runtime.Types.Result.GetResult<Prisma.$wishlist_eventPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Wishlist_events.
   * @param {wishlist_eventDeleteManyArgs} args - Arguments to filter Wishlist_events to delete.
   * @example
   * // Delete a few Wishlist_events
   * const { count } = await prisma.wishlist_event.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends wishlist_eventDeleteManyArgs>(args?: Prisma.SelectSubset<T, wishlist_eventDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Wishlist_events.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_eventUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Wishlist_events
   * const wishlist_event = await prisma.wishlist_event.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends wishlist_eventUpdateManyArgs>(args: Prisma.SelectSubset<T, wishlist_eventUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Wishlist_events and returns the data updated in the database.
   * @param {wishlist_eventUpdateManyAndReturnArgs} args - Arguments to update many Wishlist_events.
   * @example
   * // Update many Wishlist_events
   * const wishlist_event = await prisma.wishlist_event.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Wishlist_events and only return the `id`
   * const wishlist_eventWithIdOnly = await prisma.wishlist_event.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends wishlist_eventUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, wishlist_eventUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlist_eventPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Wishlist_event.
   * @param {wishlist_eventUpsertArgs} args - Arguments to update or create a Wishlist_event.
   * @example
   * // Update or create a Wishlist_event
   * const wishlist_event = await prisma.wishlist_event.upsert({
   *   create: {
   *     // ... data to create a Wishlist_event
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Wishlist_event we want to update
   *   }
   * })
   */
  upsert<T extends wishlist_eventUpsertArgs>(args: Prisma.SelectSubset<T, wishlist_eventUpsertArgs<ExtArgs>>): Prisma.Prisma__wishlist_eventClient<runtime.Types.Result.GetResult<Prisma.$wishlist_eventPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Wishlist_events.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_eventCountArgs} args - Arguments to filter Wishlist_events to count.
   * @example
   * // Count the number of Wishlist_events
   * const count = await prisma.wishlist_event.count({
   *   where: {
   *     // ... the filter for the Wishlist_events we want to count
   *   }
   * })
  **/
  count<T extends wishlist_eventCountArgs>(
    args?: Prisma.Subset<T, wishlist_eventCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Wishlist_eventCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Wishlist_event.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Wishlist_eventAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Wishlist_eventAggregateArgs>(args: Prisma.Subset<T, Wishlist_eventAggregateArgs>): Prisma.PrismaPromise<GetWishlist_eventAggregateType<T>>

  /**
   * Group by Wishlist_event.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_eventGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends wishlist_eventGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: wishlist_eventGroupByArgs['orderBy'] }
      : { orderBy?: wishlist_eventGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, wishlist_eventGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWishlist_eventGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the wishlist_event model
 */
readonly fields: wishlist_eventFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for wishlist_event.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__wishlist_eventClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  store<T extends Prisma.storesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.storesDefaultArgs<ExtArgs>>): Prisma.Prisma__storesClient<runtime.Types.Result.GetResult<Prisma.$storesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  wishlist<T extends Prisma.wishlist_event$wishlistArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.wishlist_event$wishlistArgs<ExtArgs>>): Prisma.Prisma__wishlistClient<runtime.Types.Result.GetResult<Prisma.$wishlistPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the wishlist_event model
 */
export interface wishlist_eventFieldRefs {
  readonly id: Prisma.FieldRef<"wishlist_event", 'String'>
  readonly shop: Prisma.FieldRef<"wishlist_event", 'String'>
  readonly wishlistId: Prisma.FieldRef<"wishlist_event", 'String'>
  readonly type: Prisma.FieldRef<"wishlist_event", 'String'>
  readonly productId: Prisma.FieldRef<"wishlist_event", 'String'>
  readonly variantId: Prisma.FieldRef<"wishlist_event", 'String'>
  readonly value: Prisma.FieldRef<"wishlist_event", 'Decimal'>
  readonly createdAt: Prisma.FieldRef<"wishlist_event", 'DateTime'>
}
    

// Custom InputTypes
/**
 * wishlist_event findUnique
 */
export type wishlist_eventFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_event
   */
  select?: Prisma.wishlist_eventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_event
   */
  omit?: Prisma.wishlist_eventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_eventInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_event to fetch.
   */
  where: Prisma.wishlist_eventWhereUniqueInput
}

/**
 * wishlist_event findUniqueOrThrow
 */
export type wishlist_eventFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_event
   */
  select?: Prisma.wishlist_eventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_event
   */
  omit?: Prisma.wishlist_eventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_eventInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_event to fetch.
   */
  where: Prisma.wishlist_eventWhereUniqueInput
}

/**
 * wishlist_event findFirst
 */
export type wishlist_eventFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_event
   */
  select?: Prisma.wishlist_eventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_event
   */
  omit?: Prisma.wishlist_eventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_eventInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_event to fetch.
   */
  where?: Prisma.wishlist_eventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlist_events to fetch.
   */
  orderBy?: Prisma.wishlist_eventOrderByWithRelationInput | Prisma.wishlist_eventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for wishlist_events.
   */
  cursor?: Prisma.wishlist_eventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlist_events from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlist_events.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of wishlist_events.
   */
  distinct?: Prisma.Wishlist_eventScalarFieldEnum | Prisma.Wishlist_eventScalarFieldEnum[]
}

/**
 * wishlist_event findFirstOrThrow
 */
export type wishlist_eventFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_event
   */
  select?: Prisma.wishlist_eventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_event
   */
  omit?: Prisma.wishlist_eventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_eventInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_event to fetch.
   */
  where?: Prisma.wishlist_eventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlist_events to fetch.
   */
  orderBy?: Prisma.wishlist_eventOrderByWithRelationInput | Prisma.wishlist_eventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for wishlist_events.
   */
  cursor?: Prisma.wishlist_eventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlist_events from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlist_events.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of wishlist_events.
   */
  distinct?: Prisma.Wishlist_eventScalarFieldEnum | Prisma.Wishlist_eventScalarFieldEnum[]
}

/**
 * wishlist_event findMany
 */
export type wishlist_eventFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_event
   */
  select?: Prisma.wishlist_eventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_event
   */
  omit?: Prisma.wishlist_eventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_eventInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_events to fetch.
   */
  where?: Prisma.wishlist_eventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlist_events to fetch.
   */
  orderBy?: Prisma.wishlist_eventOrderByWithRelationInput | Prisma.wishlist_eventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing wishlist_events.
   */
  cursor?: Prisma.wishlist_eventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlist_events from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlist_events.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of wishlist_events.
   */
  distinct?: Prisma.Wishlist_eventScalarFieldEnum | Prisma.Wishlist_eventScalarFieldEnum[]
}

/**
 * wishlist_event create
 */
export type wishlist_eventCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_event
   */
  select?: Prisma.wishlist_eventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_event
   */
  omit?: Prisma.wishlist_eventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_eventInclude<ExtArgs> | null
  /**
   * The data needed to create a wishlist_event.
   */
  data: Prisma.XOR<Prisma.wishlist_eventCreateInput, Prisma.wishlist_eventUncheckedCreateInput>
}

/**
 * wishlist_event createMany
 */
export type wishlist_eventCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many wishlist_events.
   */
  data: Prisma.wishlist_eventCreateManyInput | Prisma.wishlist_eventCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * wishlist_event createManyAndReturn
 */
export type wishlist_eventCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_event
   */
  select?: Prisma.wishlist_eventSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_event
   */
  omit?: Prisma.wishlist_eventOmit<ExtArgs> | null
  /**
   * The data used to create many wishlist_events.
   */
  data: Prisma.wishlist_eventCreateManyInput | Prisma.wishlist_eventCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_eventIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * wishlist_event update
 */
export type wishlist_eventUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_event
   */
  select?: Prisma.wishlist_eventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_event
   */
  omit?: Prisma.wishlist_eventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_eventInclude<ExtArgs> | null
  /**
   * The data needed to update a wishlist_event.
   */
  data: Prisma.XOR<Prisma.wishlist_eventUpdateInput, Prisma.wishlist_eventUncheckedUpdateInput>
  /**
   * Choose, which wishlist_event to update.
   */
  where: Prisma.wishlist_eventWhereUniqueInput
}

/**
 * wishlist_event updateMany
 */
export type wishlist_eventUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update wishlist_events.
   */
  data: Prisma.XOR<Prisma.wishlist_eventUpdateManyMutationInput, Prisma.wishlist_eventUncheckedUpdateManyInput>
  /**
   * Filter which wishlist_events to update
   */
  where?: Prisma.wishlist_eventWhereInput
  /**
   * Limit how many wishlist_events to update.
   */
  limit?: number
}

/**
 * wishlist_event updateManyAndReturn
 */
export type wishlist_eventUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_event
   */
  select?: Prisma.wishlist_eventSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_event
   */
  omit?: Prisma.wishlist_eventOmit<ExtArgs> | null
  /**
   * The data used to update wishlist_events.
   */
  data: Prisma.XOR<Prisma.wishlist_eventUpdateManyMutationInput, Prisma.wishlist_eventUncheckedUpdateManyInput>
  /**
   * Filter which wishlist_events to update
   */
  where?: Prisma.wishlist_eventWhereInput
  /**
   * Limit how many wishlist_events to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_eventIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * wishlist_event upsert
 */
export type wishlist_eventUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_event
   */
  select?: Prisma.wishlist_eventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_event
   */
  omit?: Prisma.wishlist_eventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_eventInclude<ExtArgs> | null
  /**
   * The filter to search for the wishlist_event to update in case it exists.
   */
  where: Prisma.wishlist_eventWhereUniqueInput
  /**
   * In case the wishlist_event found by the `where` argument doesn't exist, create a new wishlist_event with this data.
   */
  create: Prisma.XOR<Prisma.wishlist_eventCreateInput, Prisma.wishlist_eventUncheckedCreateInput>
  /**
   * In case the wishlist_event was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.wishlist_eventUpdateInput, Prisma.wishlist_eventUncheckedUpdateInput>
}

/**
 * wishlist_event delete
 */
export type wishlist_eventDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_event
   */
  select?: Prisma.wishlist_eventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_event
   */
  omit?: Prisma.wishlist_eventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_eventInclude<ExtArgs> | null
  /**
   * Filter which wishlist_event to delete.
   */
  where: Prisma.wishlist_eventWhereUniqueInput
}

/**
 * wishlist_event deleteMany
 */
export type wishlist_eventDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which wishlist_events to delete
   */
  where?: Prisma.wishlist_eventWhereInput
  /**
   * Limit how many wishlist_events to delete.
   */
  limit?: number
}

/**
 * wishlist_event.wishlist
 */
export type wishlist_event$wishlistArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist
   */
  select?: Prisma.wishlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist
   */
  omit?: Prisma.wishlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlistInclude<ExtArgs> | null
  where?: Prisma.wishlistWhereInput
}

/**
 * wishlist_event without action
 */
export type wishlist_eventDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_event
   */
  select?: Prisma.wishlist_eventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_event
   */
  omit?: Prisma.wishlist_eventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_eventInclude<ExtArgs> | null
}
