
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `wishlist_item` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model wishlist_item
 * 
 */
export type wishlist_itemModel = runtime.Types.Result.DefaultSelection<Prisma.$wishlist_itemPayload>

export type AggregateWishlist_item = {
  _count: Wishlist_itemCountAggregateOutputType | null
  _avg: Wishlist_itemAvgAggregateOutputType | null
  _sum: Wishlist_itemSumAggregateOutputType | null
  _min: Wishlist_itemMinAggregateOutputType | null
  _max: Wishlist_itemMaxAggregateOutputType | null
}

export type Wishlist_itemAvgAggregateOutputType = {
  price: runtime.Decimal | null
}

export type Wishlist_itemSumAggregateOutputType = {
  price: runtime.Decimal | null
}

export type Wishlist_itemMinAggregateOutputType = {
  id: string | null
  wishlistId: string | null
  productId: string | null
  variantId: string | null
  productHandle: string | null
  title: string | null
  variantTitle: string | null
  productUrl: string | null
  imageUrl: string | null
  imageAlt: string | null
  price: runtime.Decimal | null
  currency: string | null
  available: boolean | null
  addedAt: Date | null
  updatedAt: Date | null
}

export type Wishlist_itemMaxAggregateOutputType = {
  id: string | null
  wishlistId: string | null
  productId: string | null
  variantId: string | null
  productHandle: string | null
  title: string | null
  variantTitle: string | null
  productUrl: string | null
  imageUrl: string | null
  imageAlt: string | null
  price: runtime.Decimal | null
  currency: string | null
  available: boolean | null
  addedAt: Date | null
  updatedAt: Date | null
}

export type Wishlist_itemCountAggregateOutputType = {
  id: number
  wishlistId: number
  productId: number
  variantId: number
  productHandle: number
  title: number
  variantTitle: number
  productUrl: number
  imageUrl: number
  imageAlt: number
  price: number
  currency: number
  available: number
  addedAt: number
  updatedAt: number
  _all: number
}


export type Wishlist_itemAvgAggregateInputType = {
  price?: true
}

export type Wishlist_itemSumAggregateInputType = {
  price?: true
}

export type Wishlist_itemMinAggregateInputType = {
  id?: true
  wishlistId?: true
  productId?: true
  variantId?: true
  productHandle?: true
  title?: true
  variantTitle?: true
  productUrl?: true
  imageUrl?: true
  imageAlt?: true
  price?: true
  currency?: true
  available?: true
  addedAt?: true
  updatedAt?: true
}

export type Wishlist_itemMaxAggregateInputType = {
  id?: true
  wishlistId?: true
  productId?: true
  variantId?: true
  productHandle?: true
  title?: true
  variantTitle?: true
  productUrl?: true
  imageUrl?: true
  imageAlt?: true
  price?: true
  currency?: true
  available?: true
  addedAt?: true
  updatedAt?: true
}

export type Wishlist_itemCountAggregateInputType = {
  id?: true
  wishlistId?: true
  productId?: true
  variantId?: true
  productHandle?: true
  title?: true
  variantTitle?: true
  productUrl?: true
  imageUrl?: true
  imageAlt?: true
  price?: true
  currency?: true
  available?: true
  addedAt?: true
  updatedAt?: true
  _all?: true
}

export type Wishlist_itemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which wishlist_item to aggregate.
   */
  where?: Prisma.wishlist_itemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlist_items to fetch.
   */
  orderBy?: Prisma.wishlist_itemOrderByWithRelationInput | Prisma.wishlist_itemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.wishlist_itemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlist_items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlist_items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned wishlist_items
  **/
  _count?: true | Wishlist_itemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Wishlist_itemAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Wishlist_itemSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Wishlist_itemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Wishlist_itemMaxAggregateInputType
}

export type GetWishlist_itemAggregateType<T extends Wishlist_itemAggregateArgs> = {
      [P in keyof T & keyof AggregateWishlist_item]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWishlist_item[P]>
    : Prisma.GetScalarType<T[P], AggregateWishlist_item[P]>
}




export type wishlist_itemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.wishlist_itemWhereInput
  orderBy?: Prisma.wishlist_itemOrderByWithAggregationInput | Prisma.wishlist_itemOrderByWithAggregationInput[]
  by: Prisma.Wishlist_itemScalarFieldEnum[] | Prisma.Wishlist_itemScalarFieldEnum
  having?: Prisma.wishlist_itemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Wishlist_itemCountAggregateInputType | true
  _avg?: Wishlist_itemAvgAggregateInputType
  _sum?: Wishlist_itemSumAggregateInputType
  _min?: Wishlist_itemMinAggregateInputType
  _max?: Wishlist_itemMaxAggregateInputType
}

export type Wishlist_itemGroupByOutputType = {
  id: string
  wishlistId: string
  productId: string
  variantId: string
  productHandle: string
  title: string
  variantTitle: string | null
  productUrl: string
  imageUrl: string | null
  imageAlt: string | null
  price: runtime.Decimal
  currency: string
  available: boolean
  addedAt: Date
  updatedAt: Date
  _count: Wishlist_itemCountAggregateOutputType | null
  _avg: Wishlist_itemAvgAggregateOutputType | null
  _sum: Wishlist_itemSumAggregateOutputType | null
  _min: Wishlist_itemMinAggregateOutputType | null
  _max: Wishlist_itemMaxAggregateOutputType | null
}

export type GetWishlist_itemGroupByPayload<T extends wishlist_itemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Wishlist_itemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Wishlist_itemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Wishlist_itemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Wishlist_itemGroupByOutputType[P]>
      }
    >
  >



export type wishlist_itemWhereInput = {
  AND?: Prisma.wishlist_itemWhereInput | Prisma.wishlist_itemWhereInput[]
  OR?: Prisma.wishlist_itemWhereInput[]
  NOT?: Prisma.wishlist_itemWhereInput | Prisma.wishlist_itemWhereInput[]
  id?: Prisma.StringFilter<"wishlist_item"> | string
  wishlistId?: Prisma.StringFilter<"wishlist_item"> | string
  productId?: Prisma.StringFilter<"wishlist_item"> | string
  variantId?: Prisma.StringFilter<"wishlist_item"> | string
  productHandle?: Prisma.StringFilter<"wishlist_item"> | string
  title?: Prisma.StringFilter<"wishlist_item"> | string
  variantTitle?: Prisma.StringNullableFilter<"wishlist_item"> | string | null
  productUrl?: Prisma.StringFilter<"wishlist_item"> | string
  imageUrl?: Prisma.StringNullableFilter<"wishlist_item"> | string | null
  imageAlt?: Prisma.StringNullableFilter<"wishlist_item"> | string | null
  price?: Prisma.DecimalFilter<"wishlist_item"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFilter<"wishlist_item"> | string
  available?: Prisma.BoolFilter<"wishlist_item"> | boolean
  addedAt?: Prisma.DateTimeFilter<"wishlist_item"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"wishlist_item"> | Date | string
  wishlist?: Prisma.XOR<Prisma.WishlistScalarRelationFilter, Prisma.wishlistWhereInput>
}

export type wishlist_itemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  wishlistId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  variantId?: Prisma.SortOrder
  productHandle?: Prisma.SortOrder
  title?: Prisma.SortOrder
  variantTitle?: Prisma.SortOrderInput | Prisma.SortOrder
  productUrl?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  imageAlt?: Prisma.SortOrderInput | Prisma.SortOrder
  price?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  available?: Prisma.SortOrder
  addedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  wishlist?: Prisma.wishlistOrderByWithRelationInput
}

export type wishlist_itemWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  wishlistId_variantId?: Prisma.wishlist_itemWishlistIdVariantIdCompoundUniqueInput
  AND?: Prisma.wishlist_itemWhereInput | Prisma.wishlist_itemWhereInput[]
  OR?: Prisma.wishlist_itemWhereInput[]
  NOT?: Prisma.wishlist_itemWhereInput | Prisma.wishlist_itemWhereInput[]
  wishlistId?: Prisma.StringFilter<"wishlist_item"> | string
  productId?: Prisma.StringFilter<"wishlist_item"> | string
  variantId?: Prisma.StringFilter<"wishlist_item"> | string
  productHandle?: Prisma.StringFilter<"wishlist_item"> | string
  title?: Prisma.StringFilter<"wishlist_item"> | string
  variantTitle?: Prisma.StringNullableFilter<"wishlist_item"> | string | null
  productUrl?: Prisma.StringFilter<"wishlist_item"> | string
  imageUrl?: Prisma.StringNullableFilter<"wishlist_item"> | string | null
  imageAlt?: Prisma.StringNullableFilter<"wishlist_item"> | string | null
  price?: Prisma.DecimalFilter<"wishlist_item"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFilter<"wishlist_item"> | string
  available?: Prisma.BoolFilter<"wishlist_item"> | boolean
  addedAt?: Prisma.DateTimeFilter<"wishlist_item"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"wishlist_item"> | Date | string
  wishlist?: Prisma.XOR<Prisma.WishlistScalarRelationFilter, Prisma.wishlistWhereInput>
}, "id" | "wishlistId_variantId">

export type wishlist_itemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  wishlistId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  variantId?: Prisma.SortOrder
  productHandle?: Prisma.SortOrder
  title?: Prisma.SortOrder
  variantTitle?: Prisma.SortOrderInput | Prisma.SortOrder
  productUrl?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  imageAlt?: Prisma.SortOrderInput | Prisma.SortOrder
  price?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  available?: Prisma.SortOrder
  addedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.wishlist_itemCountOrderByAggregateInput
  _avg?: Prisma.wishlist_itemAvgOrderByAggregateInput
  _max?: Prisma.wishlist_itemMaxOrderByAggregateInput
  _min?: Prisma.wishlist_itemMinOrderByAggregateInput
  _sum?: Prisma.wishlist_itemSumOrderByAggregateInput
}

export type wishlist_itemScalarWhereWithAggregatesInput = {
  AND?: Prisma.wishlist_itemScalarWhereWithAggregatesInput | Prisma.wishlist_itemScalarWhereWithAggregatesInput[]
  OR?: Prisma.wishlist_itemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.wishlist_itemScalarWhereWithAggregatesInput | Prisma.wishlist_itemScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"wishlist_item"> | string
  wishlistId?: Prisma.StringWithAggregatesFilter<"wishlist_item"> | string
  productId?: Prisma.StringWithAggregatesFilter<"wishlist_item"> | string
  variantId?: Prisma.StringWithAggregatesFilter<"wishlist_item"> | string
  productHandle?: Prisma.StringWithAggregatesFilter<"wishlist_item"> | string
  title?: Prisma.StringWithAggregatesFilter<"wishlist_item"> | string
  variantTitle?: Prisma.StringNullableWithAggregatesFilter<"wishlist_item"> | string | null
  productUrl?: Prisma.StringWithAggregatesFilter<"wishlist_item"> | string
  imageUrl?: Prisma.StringNullableWithAggregatesFilter<"wishlist_item"> | string | null
  imageAlt?: Prisma.StringNullableWithAggregatesFilter<"wishlist_item"> | string | null
  price?: Prisma.DecimalWithAggregatesFilter<"wishlist_item"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringWithAggregatesFilter<"wishlist_item"> | string
  available?: Prisma.BoolWithAggregatesFilter<"wishlist_item"> | boolean
  addedAt?: Prisma.DateTimeWithAggregatesFilter<"wishlist_item"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"wishlist_item"> | Date | string
}

export type wishlist_itemCreateInput = {
  id?: string
  productId: string
  variantId: string
  productHandle: string
  title: string
  variantTitle?: string | null
  productUrl: string
  imageUrl?: string | null
  imageAlt?: string | null
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: string
  available?: boolean
  addedAt?: Date | string
  updatedAt?: Date | string
  wishlist: Prisma.wishlistCreateNestedOneWithoutItemsInput
}

export type wishlist_itemUncheckedCreateInput = {
  id?: string
  wishlistId: string
  productId: string
  variantId: string
  productHandle: string
  title: string
  variantTitle?: string | null
  productUrl: string
  imageUrl?: string | null
  imageAlt?: string | null
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: string
  available?: boolean
  addedAt?: Date | string
  updatedAt?: Date | string
}

export type wishlist_itemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  variantId?: Prisma.StringFieldUpdateOperationsInput | string
  productHandle?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  variantTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  productUrl?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageAlt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  available?: Prisma.BoolFieldUpdateOperationsInput | boolean
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  wishlist?: Prisma.wishlistUpdateOneRequiredWithoutItemsNestedInput
}

export type wishlist_itemUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  wishlistId?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  variantId?: Prisma.StringFieldUpdateOperationsInput | string
  productHandle?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  variantTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  productUrl?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageAlt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  available?: Prisma.BoolFieldUpdateOperationsInput | boolean
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type wishlist_itemCreateManyInput = {
  id?: string
  wishlistId: string
  productId: string
  variantId: string
  productHandle: string
  title: string
  variantTitle?: string | null
  productUrl: string
  imageUrl?: string | null
  imageAlt?: string | null
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: string
  available?: boolean
  addedAt?: Date | string
  updatedAt?: Date | string
}

export type wishlist_itemUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  variantId?: Prisma.StringFieldUpdateOperationsInput | string
  productHandle?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  variantTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  productUrl?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageAlt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  available?: Prisma.BoolFieldUpdateOperationsInput | boolean
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type wishlist_itemUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  wishlistId?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  variantId?: Prisma.StringFieldUpdateOperationsInput | string
  productHandle?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  variantTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  productUrl?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageAlt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  available?: Prisma.BoolFieldUpdateOperationsInput | boolean
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Wishlist_itemListRelationFilter = {
  every?: Prisma.wishlist_itemWhereInput
  some?: Prisma.wishlist_itemWhereInput
  none?: Prisma.wishlist_itemWhereInput
}

export type wishlist_itemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type wishlist_itemWishlistIdVariantIdCompoundUniqueInput = {
  wishlistId: string
  variantId: string
}

export type wishlist_itemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  wishlistId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  variantId?: Prisma.SortOrder
  productHandle?: Prisma.SortOrder
  title?: Prisma.SortOrder
  variantTitle?: Prisma.SortOrder
  productUrl?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  imageAlt?: Prisma.SortOrder
  price?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  available?: Prisma.SortOrder
  addedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type wishlist_itemAvgOrderByAggregateInput = {
  price?: Prisma.SortOrder
}

export type wishlist_itemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  wishlistId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  variantId?: Prisma.SortOrder
  productHandle?: Prisma.SortOrder
  title?: Prisma.SortOrder
  variantTitle?: Prisma.SortOrder
  productUrl?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  imageAlt?: Prisma.SortOrder
  price?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  available?: Prisma.SortOrder
  addedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type wishlist_itemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  wishlistId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  variantId?: Prisma.SortOrder
  productHandle?: Prisma.SortOrder
  title?: Prisma.SortOrder
  variantTitle?: Prisma.SortOrder
  productUrl?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  imageAlt?: Prisma.SortOrder
  price?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  available?: Prisma.SortOrder
  addedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type wishlist_itemSumOrderByAggregateInput = {
  price?: Prisma.SortOrder
}

export type wishlist_itemCreateNestedManyWithoutWishlistInput = {
  create?: Prisma.XOR<Prisma.wishlist_itemCreateWithoutWishlistInput, Prisma.wishlist_itemUncheckedCreateWithoutWishlistInput> | Prisma.wishlist_itemCreateWithoutWishlistInput[] | Prisma.wishlist_itemUncheckedCreateWithoutWishlistInput[]
  connectOrCreate?: Prisma.wishlist_itemCreateOrConnectWithoutWishlistInput | Prisma.wishlist_itemCreateOrConnectWithoutWishlistInput[]
  createMany?: Prisma.wishlist_itemCreateManyWishlistInputEnvelope
  connect?: Prisma.wishlist_itemWhereUniqueInput | Prisma.wishlist_itemWhereUniqueInput[]
}

export type wishlist_itemUncheckedCreateNestedManyWithoutWishlistInput = {
  create?: Prisma.XOR<Prisma.wishlist_itemCreateWithoutWishlistInput, Prisma.wishlist_itemUncheckedCreateWithoutWishlistInput> | Prisma.wishlist_itemCreateWithoutWishlistInput[] | Prisma.wishlist_itemUncheckedCreateWithoutWishlistInput[]
  connectOrCreate?: Prisma.wishlist_itemCreateOrConnectWithoutWishlistInput | Prisma.wishlist_itemCreateOrConnectWithoutWishlistInput[]
  createMany?: Prisma.wishlist_itemCreateManyWishlistInputEnvelope
  connect?: Prisma.wishlist_itemWhereUniqueInput | Prisma.wishlist_itemWhereUniqueInput[]
}

export type wishlist_itemUpdateManyWithoutWishlistNestedInput = {
  create?: Prisma.XOR<Prisma.wishlist_itemCreateWithoutWishlistInput, Prisma.wishlist_itemUncheckedCreateWithoutWishlistInput> | Prisma.wishlist_itemCreateWithoutWishlistInput[] | Prisma.wishlist_itemUncheckedCreateWithoutWishlistInput[]
  connectOrCreate?: Prisma.wishlist_itemCreateOrConnectWithoutWishlistInput | Prisma.wishlist_itemCreateOrConnectWithoutWishlistInput[]
  upsert?: Prisma.wishlist_itemUpsertWithWhereUniqueWithoutWishlistInput | Prisma.wishlist_itemUpsertWithWhereUniqueWithoutWishlistInput[]
  createMany?: Prisma.wishlist_itemCreateManyWishlistInputEnvelope
  set?: Prisma.wishlist_itemWhereUniqueInput | Prisma.wishlist_itemWhereUniqueInput[]
  disconnect?: Prisma.wishlist_itemWhereUniqueInput | Prisma.wishlist_itemWhereUniqueInput[]
  delete?: Prisma.wishlist_itemWhereUniqueInput | Prisma.wishlist_itemWhereUniqueInput[]
  connect?: Prisma.wishlist_itemWhereUniqueInput | Prisma.wishlist_itemWhereUniqueInput[]
  update?: Prisma.wishlist_itemUpdateWithWhereUniqueWithoutWishlistInput | Prisma.wishlist_itemUpdateWithWhereUniqueWithoutWishlistInput[]
  updateMany?: Prisma.wishlist_itemUpdateManyWithWhereWithoutWishlistInput | Prisma.wishlist_itemUpdateManyWithWhereWithoutWishlistInput[]
  deleteMany?: Prisma.wishlist_itemScalarWhereInput | Prisma.wishlist_itemScalarWhereInput[]
}

export type wishlist_itemUncheckedUpdateManyWithoutWishlistNestedInput = {
  create?: Prisma.XOR<Prisma.wishlist_itemCreateWithoutWishlistInput, Prisma.wishlist_itemUncheckedCreateWithoutWishlistInput> | Prisma.wishlist_itemCreateWithoutWishlistInput[] | Prisma.wishlist_itemUncheckedCreateWithoutWishlistInput[]
  connectOrCreate?: Prisma.wishlist_itemCreateOrConnectWithoutWishlistInput | Prisma.wishlist_itemCreateOrConnectWithoutWishlistInput[]
  upsert?: Prisma.wishlist_itemUpsertWithWhereUniqueWithoutWishlistInput | Prisma.wishlist_itemUpsertWithWhereUniqueWithoutWishlistInput[]
  createMany?: Prisma.wishlist_itemCreateManyWishlistInputEnvelope
  set?: Prisma.wishlist_itemWhereUniqueInput | Prisma.wishlist_itemWhereUniqueInput[]
  disconnect?: Prisma.wishlist_itemWhereUniqueInput | Prisma.wishlist_itemWhereUniqueInput[]
  delete?: Prisma.wishlist_itemWhereUniqueInput | Prisma.wishlist_itemWhereUniqueInput[]
  connect?: Prisma.wishlist_itemWhereUniqueInput | Prisma.wishlist_itemWhereUniqueInput[]
  update?: Prisma.wishlist_itemUpdateWithWhereUniqueWithoutWishlistInput | Prisma.wishlist_itemUpdateWithWhereUniqueWithoutWishlistInput[]
  updateMany?: Prisma.wishlist_itemUpdateManyWithWhereWithoutWishlistInput | Prisma.wishlist_itemUpdateManyWithWhereWithoutWishlistInput[]
  deleteMany?: Prisma.wishlist_itemScalarWhereInput | Prisma.wishlist_itemScalarWhereInput[]
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type wishlist_itemCreateWithoutWishlistInput = {
  id?: string
  productId: string
  variantId: string
  productHandle: string
  title: string
  variantTitle?: string | null
  productUrl: string
  imageUrl?: string | null
  imageAlt?: string | null
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: string
  available?: boolean
  addedAt?: Date | string
  updatedAt?: Date | string
}

export type wishlist_itemUncheckedCreateWithoutWishlistInput = {
  id?: string
  productId: string
  variantId: string
  productHandle: string
  title: string
  variantTitle?: string | null
  productUrl: string
  imageUrl?: string | null
  imageAlt?: string | null
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: string
  available?: boolean
  addedAt?: Date | string
  updatedAt?: Date | string
}

export type wishlist_itemCreateOrConnectWithoutWishlistInput = {
  where: Prisma.wishlist_itemWhereUniqueInput
  create: Prisma.XOR<Prisma.wishlist_itemCreateWithoutWishlistInput, Prisma.wishlist_itemUncheckedCreateWithoutWishlistInput>
}

export type wishlist_itemCreateManyWishlistInputEnvelope = {
  data: Prisma.wishlist_itemCreateManyWishlistInput | Prisma.wishlist_itemCreateManyWishlistInput[]
  skipDuplicates?: boolean
}

export type wishlist_itemUpsertWithWhereUniqueWithoutWishlistInput = {
  where: Prisma.wishlist_itemWhereUniqueInput
  update: Prisma.XOR<Prisma.wishlist_itemUpdateWithoutWishlistInput, Prisma.wishlist_itemUncheckedUpdateWithoutWishlistInput>
  create: Prisma.XOR<Prisma.wishlist_itemCreateWithoutWishlistInput, Prisma.wishlist_itemUncheckedCreateWithoutWishlistInput>
}

export type wishlist_itemUpdateWithWhereUniqueWithoutWishlistInput = {
  where: Prisma.wishlist_itemWhereUniqueInput
  data: Prisma.XOR<Prisma.wishlist_itemUpdateWithoutWishlistInput, Prisma.wishlist_itemUncheckedUpdateWithoutWishlistInput>
}

export type wishlist_itemUpdateManyWithWhereWithoutWishlistInput = {
  where: Prisma.wishlist_itemScalarWhereInput
  data: Prisma.XOR<Prisma.wishlist_itemUpdateManyMutationInput, Prisma.wishlist_itemUncheckedUpdateManyWithoutWishlistInput>
}

export type wishlist_itemScalarWhereInput = {
  AND?: Prisma.wishlist_itemScalarWhereInput | Prisma.wishlist_itemScalarWhereInput[]
  OR?: Prisma.wishlist_itemScalarWhereInput[]
  NOT?: Prisma.wishlist_itemScalarWhereInput | Prisma.wishlist_itemScalarWhereInput[]
  id?: Prisma.StringFilter<"wishlist_item"> | string
  wishlistId?: Prisma.StringFilter<"wishlist_item"> | string
  productId?: Prisma.StringFilter<"wishlist_item"> | string
  variantId?: Prisma.StringFilter<"wishlist_item"> | string
  productHandle?: Prisma.StringFilter<"wishlist_item"> | string
  title?: Prisma.StringFilter<"wishlist_item"> | string
  variantTitle?: Prisma.StringNullableFilter<"wishlist_item"> | string | null
  productUrl?: Prisma.StringFilter<"wishlist_item"> | string
  imageUrl?: Prisma.StringNullableFilter<"wishlist_item"> | string | null
  imageAlt?: Prisma.StringNullableFilter<"wishlist_item"> | string | null
  price?: Prisma.DecimalFilter<"wishlist_item"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFilter<"wishlist_item"> | string
  available?: Prisma.BoolFilter<"wishlist_item"> | boolean
  addedAt?: Prisma.DateTimeFilter<"wishlist_item"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"wishlist_item"> | Date | string
}

export type wishlist_itemCreateManyWishlistInput = {
  id?: string
  productId: string
  variantId: string
  productHandle: string
  title: string
  variantTitle?: string | null
  productUrl: string
  imageUrl?: string | null
  imageAlt?: string | null
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: string
  available?: boolean
  addedAt?: Date | string
  updatedAt?: Date | string
}

export type wishlist_itemUpdateWithoutWishlistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  variantId?: Prisma.StringFieldUpdateOperationsInput | string
  productHandle?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  variantTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  productUrl?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageAlt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  available?: Prisma.BoolFieldUpdateOperationsInput | boolean
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type wishlist_itemUncheckedUpdateWithoutWishlistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  variantId?: Prisma.StringFieldUpdateOperationsInput | string
  productHandle?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  variantTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  productUrl?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageAlt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  available?: Prisma.BoolFieldUpdateOperationsInput | boolean
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type wishlist_itemUncheckedUpdateManyWithoutWishlistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  variantId?: Prisma.StringFieldUpdateOperationsInput | string
  productHandle?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  variantTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  productUrl?: Prisma.StringFieldUpdateOperationsInput | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageAlt?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  available?: Prisma.BoolFieldUpdateOperationsInput | boolean
  addedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type wishlist_itemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  wishlistId?: boolean
  productId?: boolean
  variantId?: boolean
  productHandle?: boolean
  title?: boolean
  variantTitle?: boolean
  productUrl?: boolean
  imageUrl?: boolean
  imageAlt?: boolean
  price?: boolean
  currency?: boolean
  available?: boolean
  addedAt?: boolean
  updatedAt?: boolean
  wishlist?: boolean | Prisma.wishlistDefaultArgs<ExtArgs>
}, ExtArgs["result"]["wishlist_item"]>

export type wishlist_itemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  wishlistId?: boolean
  productId?: boolean
  variantId?: boolean
  productHandle?: boolean
  title?: boolean
  variantTitle?: boolean
  productUrl?: boolean
  imageUrl?: boolean
  imageAlt?: boolean
  price?: boolean
  currency?: boolean
  available?: boolean
  addedAt?: boolean
  updatedAt?: boolean
  wishlist?: boolean | Prisma.wishlistDefaultArgs<ExtArgs>
}, ExtArgs["result"]["wishlist_item"]>

export type wishlist_itemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  wishlistId?: boolean
  productId?: boolean
  variantId?: boolean
  productHandle?: boolean
  title?: boolean
  variantTitle?: boolean
  productUrl?: boolean
  imageUrl?: boolean
  imageAlt?: boolean
  price?: boolean
  currency?: boolean
  available?: boolean
  addedAt?: boolean
  updatedAt?: boolean
  wishlist?: boolean | Prisma.wishlistDefaultArgs<ExtArgs>
}, ExtArgs["result"]["wishlist_item"]>

export type wishlist_itemSelectScalar = {
  id?: boolean
  wishlistId?: boolean
  productId?: boolean
  variantId?: boolean
  productHandle?: boolean
  title?: boolean
  variantTitle?: boolean
  productUrl?: boolean
  imageUrl?: boolean
  imageAlt?: boolean
  price?: boolean
  currency?: boolean
  available?: boolean
  addedAt?: boolean
  updatedAt?: boolean
}

export type wishlist_itemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "wishlistId" | "productId" | "variantId" | "productHandle" | "title" | "variantTitle" | "productUrl" | "imageUrl" | "imageAlt" | "price" | "currency" | "available" | "addedAt" | "updatedAt", ExtArgs["result"]["wishlist_item"]>
export type wishlist_itemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  wishlist?: boolean | Prisma.wishlistDefaultArgs<ExtArgs>
}
export type wishlist_itemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  wishlist?: boolean | Prisma.wishlistDefaultArgs<ExtArgs>
}
export type wishlist_itemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  wishlist?: boolean | Prisma.wishlistDefaultArgs<ExtArgs>
}

export type $wishlist_itemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "wishlist_item"
  objects: {
    wishlist: Prisma.$wishlistPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    wishlistId: string
    productId: string
    variantId: string
    productHandle: string
    title: string
    variantTitle: string | null
    productUrl: string
    imageUrl: string | null
    imageAlt: string | null
    price: runtime.Decimal
    currency: string
    available: boolean
    addedAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["wishlist_item"]>
  composites: {}
}

export type wishlist_itemGetPayload<S extends boolean | null | undefined | wishlist_itemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$wishlist_itemPayload, S>

export type wishlist_itemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<wishlist_itemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Wishlist_itemCountAggregateInputType | true
  }

export interface wishlist_itemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['wishlist_item'], meta: { name: 'wishlist_item' } }
  /**
   * Find zero or one Wishlist_item that matches the filter.
   * @param {wishlist_itemFindUniqueArgs} args - Arguments to find a Wishlist_item
   * @example
   * // Get one Wishlist_item
   * const wishlist_item = await prisma.wishlist_item.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends wishlist_itemFindUniqueArgs>(args: Prisma.SelectSubset<T, wishlist_itemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__wishlist_itemClient<runtime.Types.Result.GetResult<Prisma.$wishlist_itemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Wishlist_item that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {wishlist_itemFindUniqueOrThrowArgs} args - Arguments to find a Wishlist_item
   * @example
   * // Get one Wishlist_item
   * const wishlist_item = await prisma.wishlist_item.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends wishlist_itemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, wishlist_itemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__wishlist_itemClient<runtime.Types.Result.GetResult<Prisma.$wishlist_itemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Wishlist_item that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_itemFindFirstArgs} args - Arguments to find a Wishlist_item
   * @example
   * // Get one Wishlist_item
   * const wishlist_item = await prisma.wishlist_item.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends wishlist_itemFindFirstArgs>(args?: Prisma.SelectSubset<T, wishlist_itemFindFirstArgs<ExtArgs>>): Prisma.Prisma__wishlist_itemClient<runtime.Types.Result.GetResult<Prisma.$wishlist_itemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Wishlist_item that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_itemFindFirstOrThrowArgs} args - Arguments to find a Wishlist_item
   * @example
   * // Get one Wishlist_item
   * const wishlist_item = await prisma.wishlist_item.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends wishlist_itemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, wishlist_itemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__wishlist_itemClient<runtime.Types.Result.GetResult<Prisma.$wishlist_itemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Wishlist_items that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_itemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Wishlist_items
   * const wishlist_items = await prisma.wishlist_item.findMany()
   * 
   * // Get first 10 Wishlist_items
   * const wishlist_items = await prisma.wishlist_item.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const wishlist_itemWithIdOnly = await prisma.wishlist_item.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends wishlist_itemFindManyArgs>(args?: Prisma.SelectSubset<T, wishlist_itemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlist_itemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Wishlist_item.
   * @param {wishlist_itemCreateArgs} args - Arguments to create a Wishlist_item.
   * @example
   * // Create one Wishlist_item
   * const Wishlist_item = await prisma.wishlist_item.create({
   *   data: {
   *     // ... data to create a Wishlist_item
   *   }
   * })
   * 
   */
  create<T extends wishlist_itemCreateArgs>(args: Prisma.SelectSubset<T, wishlist_itemCreateArgs<ExtArgs>>): Prisma.Prisma__wishlist_itemClient<runtime.Types.Result.GetResult<Prisma.$wishlist_itemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Wishlist_items.
   * @param {wishlist_itemCreateManyArgs} args - Arguments to create many Wishlist_items.
   * @example
   * // Create many Wishlist_items
   * const wishlist_item = await prisma.wishlist_item.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends wishlist_itemCreateManyArgs>(args?: Prisma.SelectSubset<T, wishlist_itemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Wishlist_items and returns the data saved in the database.
   * @param {wishlist_itemCreateManyAndReturnArgs} args - Arguments to create many Wishlist_items.
   * @example
   * // Create many Wishlist_items
   * const wishlist_item = await prisma.wishlist_item.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Wishlist_items and only return the `id`
   * const wishlist_itemWithIdOnly = await prisma.wishlist_item.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends wishlist_itemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, wishlist_itemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlist_itemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Wishlist_item.
   * @param {wishlist_itemDeleteArgs} args - Arguments to delete one Wishlist_item.
   * @example
   * // Delete one Wishlist_item
   * const Wishlist_item = await prisma.wishlist_item.delete({
   *   where: {
   *     // ... filter to delete one Wishlist_item
   *   }
   * })
   * 
   */
  delete<T extends wishlist_itemDeleteArgs>(args: Prisma.SelectSubset<T, wishlist_itemDeleteArgs<ExtArgs>>): Prisma.Prisma__wishlist_itemClient<runtime.Types.Result.GetResult<Prisma.$wishlist_itemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Wishlist_item.
   * @param {wishlist_itemUpdateArgs} args - Arguments to update one Wishlist_item.
   * @example
   * // Update one Wishlist_item
   * const wishlist_item = await prisma.wishlist_item.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends wishlist_itemUpdateArgs>(args: Prisma.SelectSubset<T, wishlist_itemUpdateArgs<ExtArgs>>): Prisma.Prisma__wishlist_itemClient<runtime.Types.Result.GetResult<Prisma.$wishlist_itemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Wishlist_items.
   * @param {wishlist_itemDeleteManyArgs} args - Arguments to filter Wishlist_items to delete.
   * @example
   * // Delete a few Wishlist_items
   * const { count } = await prisma.wishlist_item.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends wishlist_itemDeleteManyArgs>(args?: Prisma.SelectSubset<T, wishlist_itemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Wishlist_items.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_itemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Wishlist_items
   * const wishlist_item = await prisma.wishlist_item.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends wishlist_itemUpdateManyArgs>(args: Prisma.SelectSubset<T, wishlist_itemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Wishlist_items and returns the data updated in the database.
   * @param {wishlist_itemUpdateManyAndReturnArgs} args - Arguments to update many Wishlist_items.
   * @example
   * // Update many Wishlist_items
   * const wishlist_item = await prisma.wishlist_item.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Wishlist_items and only return the `id`
   * const wishlist_itemWithIdOnly = await prisma.wishlist_item.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends wishlist_itemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, wishlist_itemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlist_itemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Wishlist_item.
   * @param {wishlist_itemUpsertArgs} args - Arguments to update or create a Wishlist_item.
   * @example
   * // Update or create a Wishlist_item
   * const wishlist_item = await prisma.wishlist_item.upsert({
   *   create: {
   *     // ... data to create a Wishlist_item
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Wishlist_item we want to update
   *   }
   * })
   */
  upsert<T extends wishlist_itemUpsertArgs>(args: Prisma.SelectSubset<T, wishlist_itemUpsertArgs<ExtArgs>>): Prisma.Prisma__wishlist_itemClient<runtime.Types.Result.GetResult<Prisma.$wishlist_itemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Wishlist_items.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_itemCountArgs} args - Arguments to filter Wishlist_items to count.
   * @example
   * // Count the number of Wishlist_items
   * const count = await prisma.wishlist_item.count({
   *   where: {
   *     // ... the filter for the Wishlist_items we want to count
   *   }
   * })
  **/
  count<T extends wishlist_itemCountArgs>(
    args?: Prisma.Subset<T, wishlist_itemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Wishlist_itemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Wishlist_item.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Wishlist_itemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Wishlist_itemAggregateArgs>(args: Prisma.Subset<T, Wishlist_itemAggregateArgs>): Prisma.PrismaPromise<GetWishlist_itemAggregateType<T>>

  /**
   * Group by Wishlist_item.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_itemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends wishlist_itemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: wishlist_itemGroupByArgs['orderBy'] }
      : { orderBy?: wishlist_itemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, wishlist_itemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWishlist_itemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the wishlist_item model
 */
readonly fields: wishlist_itemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for wishlist_item.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__wishlist_itemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  wishlist<T extends Prisma.wishlistDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.wishlistDefaultArgs<ExtArgs>>): Prisma.Prisma__wishlistClient<runtime.Types.Result.GetResult<Prisma.$wishlistPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the wishlist_item model
 */
export interface wishlist_itemFieldRefs {
  readonly id: Prisma.FieldRef<"wishlist_item", 'String'>
  readonly wishlistId: Prisma.FieldRef<"wishlist_item", 'String'>
  readonly productId: Prisma.FieldRef<"wishlist_item", 'String'>
  readonly variantId: Prisma.FieldRef<"wishlist_item", 'String'>
  readonly productHandle: Prisma.FieldRef<"wishlist_item", 'String'>
  readonly title: Prisma.FieldRef<"wishlist_item", 'String'>
  readonly variantTitle: Prisma.FieldRef<"wishlist_item", 'String'>
  readonly productUrl: Prisma.FieldRef<"wishlist_item", 'String'>
  readonly imageUrl: Prisma.FieldRef<"wishlist_item", 'String'>
  readonly imageAlt: Prisma.FieldRef<"wishlist_item", 'String'>
  readonly price: Prisma.FieldRef<"wishlist_item", 'Decimal'>
  readonly currency: Prisma.FieldRef<"wishlist_item", 'String'>
  readonly available: Prisma.FieldRef<"wishlist_item", 'Boolean'>
  readonly addedAt: Prisma.FieldRef<"wishlist_item", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"wishlist_item", 'DateTime'>
}
    

// Custom InputTypes
/**
 * wishlist_item findUnique
 */
export type wishlist_itemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_item
   */
  select?: Prisma.wishlist_itemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_item
   */
  omit?: Prisma.wishlist_itemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_itemInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_item to fetch.
   */
  where: Prisma.wishlist_itemWhereUniqueInput
}

/**
 * wishlist_item findUniqueOrThrow
 */
export type wishlist_itemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_item
   */
  select?: Prisma.wishlist_itemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_item
   */
  omit?: Prisma.wishlist_itemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_itemInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_item to fetch.
   */
  where: Prisma.wishlist_itemWhereUniqueInput
}

/**
 * wishlist_item findFirst
 */
export type wishlist_itemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_item
   */
  select?: Prisma.wishlist_itemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_item
   */
  omit?: Prisma.wishlist_itemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_itemInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_item to fetch.
   */
  where?: Prisma.wishlist_itemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlist_items to fetch.
   */
  orderBy?: Prisma.wishlist_itemOrderByWithRelationInput | Prisma.wishlist_itemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for wishlist_items.
   */
  cursor?: Prisma.wishlist_itemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlist_items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlist_items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of wishlist_items.
   */
  distinct?: Prisma.Wishlist_itemScalarFieldEnum | Prisma.Wishlist_itemScalarFieldEnum[]
}

/**
 * wishlist_item findFirstOrThrow
 */
export type wishlist_itemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_item
   */
  select?: Prisma.wishlist_itemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_item
   */
  omit?: Prisma.wishlist_itemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_itemInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_item to fetch.
   */
  where?: Prisma.wishlist_itemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlist_items to fetch.
   */
  orderBy?: Prisma.wishlist_itemOrderByWithRelationInput | Prisma.wishlist_itemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for wishlist_items.
   */
  cursor?: Prisma.wishlist_itemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlist_items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlist_items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of wishlist_items.
   */
  distinct?: Prisma.Wishlist_itemScalarFieldEnum | Prisma.Wishlist_itemScalarFieldEnum[]
}

/**
 * wishlist_item findMany
 */
export type wishlist_itemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_item
   */
  select?: Prisma.wishlist_itemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_item
   */
  omit?: Prisma.wishlist_itemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_itemInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_items to fetch.
   */
  where?: Prisma.wishlist_itemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlist_items to fetch.
   */
  orderBy?: Prisma.wishlist_itemOrderByWithRelationInput | Prisma.wishlist_itemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing wishlist_items.
   */
  cursor?: Prisma.wishlist_itemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlist_items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlist_items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of wishlist_items.
   */
  distinct?: Prisma.Wishlist_itemScalarFieldEnum | Prisma.Wishlist_itemScalarFieldEnum[]
}

/**
 * wishlist_item create
 */
export type wishlist_itemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_item
   */
  select?: Prisma.wishlist_itemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_item
   */
  omit?: Prisma.wishlist_itemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_itemInclude<ExtArgs> | null
  /**
   * The data needed to create a wishlist_item.
   */
  data: Prisma.XOR<Prisma.wishlist_itemCreateInput, Prisma.wishlist_itemUncheckedCreateInput>
}

/**
 * wishlist_item createMany
 */
export type wishlist_itemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many wishlist_items.
   */
  data: Prisma.wishlist_itemCreateManyInput | Prisma.wishlist_itemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * wishlist_item createManyAndReturn
 */
export type wishlist_itemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_item
   */
  select?: Prisma.wishlist_itemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_item
   */
  omit?: Prisma.wishlist_itemOmit<ExtArgs> | null
  /**
   * The data used to create many wishlist_items.
   */
  data: Prisma.wishlist_itemCreateManyInput | Prisma.wishlist_itemCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_itemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * wishlist_item update
 */
export type wishlist_itemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_item
   */
  select?: Prisma.wishlist_itemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_item
   */
  omit?: Prisma.wishlist_itemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_itemInclude<ExtArgs> | null
  /**
   * The data needed to update a wishlist_item.
   */
  data: Prisma.XOR<Prisma.wishlist_itemUpdateInput, Prisma.wishlist_itemUncheckedUpdateInput>
  /**
   * Choose, which wishlist_item to update.
   */
  where: Prisma.wishlist_itemWhereUniqueInput
}

/**
 * wishlist_item updateMany
 */
export type wishlist_itemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update wishlist_items.
   */
  data: Prisma.XOR<Prisma.wishlist_itemUpdateManyMutationInput, Prisma.wishlist_itemUncheckedUpdateManyInput>
  /**
   * Filter which wishlist_items to update
   */
  where?: Prisma.wishlist_itemWhereInput
  /**
   * Limit how many wishlist_items to update.
   */
  limit?: number
}

/**
 * wishlist_item updateManyAndReturn
 */
export type wishlist_itemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_item
   */
  select?: Prisma.wishlist_itemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_item
   */
  omit?: Prisma.wishlist_itemOmit<ExtArgs> | null
  /**
   * The data used to update wishlist_items.
   */
  data: Prisma.XOR<Prisma.wishlist_itemUpdateManyMutationInput, Prisma.wishlist_itemUncheckedUpdateManyInput>
  /**
   * Filter which wishlist_items to update
   */
  where?: Prisma.wishlist_itemWhereInput
  /**
   * Limit how many wishlist_items to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_itemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * wishlist_item upsert
 */
export type wishlist_itemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_item
   */
  select?: Prisma.wishlist_itemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_item
   */
  omit?: Prisma.wishlist_itemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_itemInclude<ExtArgs> | null
  /**
   * The filter to search for the wishlist_item to update in case it exists.
   */
  where: Prisma.wishlist_itemWhereUniqueInput
  /**
   * In case the wishlist_item found by the `where` argument doesn't exist, create a new wishlist_item with this data.
   */
  create: Prisma.XOR<Prisma.wishlist_itemCreateInput, Prisma.wishlist_itemUncheckedCreateInput>
  /**
   * In case the wishlist_item was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.wishlist_itemUpdateInput, Prisma.wishlist_itemUncheckedUpdateInput>
}

/**
 * wishlist_item delete
 */
export type wishlist_itemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_item
   */
  select?: Prisma.wishlist_itemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_item
   */
  omit?: Prisma.wishlist_itemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_itemInclude<ExtArgs> | null
  /**
   * Filter which wishlist_item to delete.
   */
  where: Prisma.wishlist_itemWhereUniqueInput
}

/**
 * wishlist_item deleteMany
 */
export type wishlist_itemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which wishlist_items to delete
   */
  where?: Prisma.wishlist_itemWhereInput
  /**
   * Limit how many wishlist_items to delete.
   */
  limit?: number
}

/**
 * wishlist_item without action
 */
export type wishlist_itemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_item
   */
  select?: Prisma.wishlist_itemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_item
   */
  omit?: Prisma.wishlist_itemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_itemInclude<ExtArgs> | null
}
