
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `wishlist` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model wishlist
 * 
 */
export type wishlistModel = runtime.Types.Result.DefaultSelection<Prisma.$wishlistPayload>

export type AggregateWishlist = {
  _count: WishlistCountAggregateOutputType | null
  _min: WishlistMinAggregateOutputType | null
  _max: WishlistMaxAggregateOutputType | null
}

export type WishlistMinAggregateOutputType = {
  id: string | null
  shop: string | null
  key: string | null
  customerId: string | null
  visitorId: string | null
  email: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type WishlistMaxAggregateOutputType = {
  id: string | null
  shop: string | null
  key: string | null
  customerId: string | null
  visitorId: string | null
  email: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type WishlistCountAggregateOutputType = {
  id: number
  shop: number
  key: number
  customerId: number
  visitorId: number
  email: number
  name: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type WishlistMinAggregateInputType = {
  id?: true
  shop?: true
  key?: true
  customerId?: true
  visitorId?: true
  email?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type WishlistMaxAggregateInputType = {
  id?: true
  shop?: true
  key?: true
  customerId?: true
  visitorId?: true
  email?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type WishlistCountAggregateInputType = {
  id?: true
  shop?: true
  key?: true
  customerId?: true
  visitorId?: true
  email?: true
  name?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type WishlistAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which wishlist to aggregate.
   */
  where?: Prisma.wishlistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlists to fetch.
   */
  orderBy?: Prisma.wishlistOrderByWithRelationInput | Prisma.wishlistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.wishlistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned wishlists
  **/
  _count?: true | WishlistCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WishlistMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WishlistMaxAggregateInputType
}

export type GetWishlistAggregateType<T extends WishlistAggregateArgs> = {
      [P in keyof T & keyof AggregateWishlist]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWishlist[P]>
    : Prisma.GetScalarType<T[P], AggregateWishlist[P]>
}




export type wishlistGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.wishlistWhereInput
  orderBy?: Prisma.wishlistOrderByWithAggregationInput | Prisma.wishlistOrderByWithAggregationInput[]
  by: Prisma.WishlistScalarFieldEnum[] | Prisma.WishlistScalarFieldEnum
  having?: Prisma.wishlistScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WishlistCountAggregateInputType | true
  _min?: WishlistMinAggregateInputType
  _max?: WishlistMaxAggregateInputType
}

export type WishlistGroupByOutputType = {
  id: string
  shop: string
  key: string
  customerId: string | null
  visitorId: string | null
  email: string | null
  name: string | null
  createdAt: Date
  updatedAt: Date
  _count: WishlistCountAggregateOutputType | null
  _min: WishlistMinAggregateOutputType | null
  _max: WishlistMaxAggregateOutputType | null
}

export type GetWishlistGroupByPayload<T extends wishlistGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WishlistGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WishlistGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WishlistGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WishlistGroupByOutputType[P]>
      }
    >
  >



export type wishlistWhereInput = {
  AND?: Prisma.wishlistWhereInput | Prisma.wishlistWhereInput[]
  OR?: Prisma.wishlistWhereInput[]
  NOT?: Prisma.wishlistWhereInput | Prisma.wishlistWhereInput[]
  id?: Prisma.StringFilter<"wishlist"> | string
  shop?: Prisma.StringFilter<"wishlist"> | string
  key?: Prisma.StringFilter<"wishlist"> | string
  customerId?: Prisma.StringNullableFilter<"wishlist"> | string | null
  visitorId?: Prisma.StringNullableFilter<"wishlist"> | string | null
  email?: Prisma.StringNullableFilter<"wishlist"> | string | null
  name?: Prisma.StringNullableFilter<"wishlist"> | string | null
  createdAt?: Prisma.DateTimeFilter<"wishlist"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"wishlist"> | Date | string
  store?: Prisma.XOR<Prisma.StoresScalarRelationFilter, Prisma.storesWhereInput>
  items?: Prisma.Wishlist_itemListRelationFilter
  events?: Prisma.Wishlist_eventListRelationFilter
}

export type wishlistOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  shop?: Prisma.SortOrder
  key?: Prisma.SortOrder
  customerId?: Prisma.SortOrderInput | Prisma.SortOrder
  visitorId?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  store?: Prisma.storesOrderByWithRelationInput
  items?: Prisma.wishlist_itemOrderByRelationAggregateInput
  events?: Prisma.wishlist_eventOrderByRelationAggregateInput
}

export type wishlistWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  shop_key?: Prisma.wishlistShopKeyCompoundUniqueInput
  AND?: Prisma.wishlistWhereInput | Prisma.wishlistWhereInput[]
  OR?: Prisma.wishlistWhereInput[]
  NOT?: Prisma.wishlistWhereInput | Prisma.wishlistWhereInput[]
  shop?: Prisma.StringFilter<"wishlist"> | string
  key?: Prisma.StringFilter<"wishlist"> | string
  customerId?: Prisma.StringNullableFilter<"wishlist"> | string | null
  visitorId?: Prisma.StringNullableFilter<"wishlist"> | string | null
  email?: Prisma.StringNullableFilter<"wishlist"> | string | null
  name?: Prisma.StringNullableFilter<"wishlist"> | string | null
  createdAt?: Prisma.DateTimeFilter<"wishlist"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"wishlist"> | Date | string
  store?: Prisma.XOR<Prisma.StoresScalarRelationFilter, Prisma.storesWhereInput>
  items?: Prisma.Wishlist_itemListRelationFilter
  events?: Prisma.Wishlist_eventListRelationFilter
}, "id" | "shop_key">

export type wishlistOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  shop?: Prisma.SortOrder
  key?: Prisma.SortOrder
  customerId?: Prisma.SortOrderInput | Prisma.SortOrder
  visitorId?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.wishlistCountOrderByAggregateInput
  _max?: Prisma.wishlistMaxOrderByAggregateInput
  _min?: Prisma.wishlistMinOrderByAggregateInput
}

export type wishlistScalarWhereWithAggregatesInput = {
  AND?: Prisma.wishlistScalarWhereWithAggregatesInput | Prisma.wishlistScalarWhereWithAggregatesInput[]
  OR?: Prisma.wishlistScalarWhereWithAggregatesInput[]
  NOT?: Prisma.wishlistScalarWhereWithAggregatesInput | Prisma.wishlistScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"wishlist"> | string
  shop?: Prisma.StringWithAggregatesFilter<"wishlist"> | string
  key?: Prisma.StringWithAggregatesFilter<"wishlist"> | string
  customerId?: Prisma.StringNullableWithAggregatesFilter<"wishlist"> | string | null
  visitorId?: Prisma.StringNullableWithAggregatesFilter<"wishlist"> | string | null
  email?: Prisma.StringNullableWithAggregatesFilter<"wishlist"> | string | null
  name?: Prisma.StringNullableWithAggregatesFilter<"wishlist"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"wishlist"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"wishlist"> | Date | string
}

export type wishlistCreateInput = {
  id?: string
  key: string
  customerId?: string | null
  visitorId?: string | null
  email?: string | null
  name?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  store: Prisma.storesCreateNestedOneWithoutWishlistsInput
  items?: Prisma.wishlist_itemCreateNestedManyWithoutWishlistInput
  events?: Prisma.wishlist_eventCreateNestedManyWithoutWishlistInput
}

export type wishlistUncheckedCreateInput = {
  id?: string
  shop: string
  key: string
  customerId?: string | null
  visitorId?: string | null
  email?: string | null
  name?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  items?: Prisma.wishlist_itemUncheckedCreateNestedManyWithoutWishlistInput
  events?: Prisma.wishlist_eventUncheckedCreateNestedManyWithoutWishlistInput
}

export type wishlistUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  visitorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  store?: Prisma.storesUpdateOneRequiredWithoutWishlistsNestedInput
  items?: Prisma.wishlist_itemUpdateManyWithoutWishlistNestedInput
  events?: Prisma.wishlist_eventUpdateManyWithoutWishlistNestedInput
}

export type wishlistUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  visitorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  items?: Prisma.wishlist_itemUncheckedUpdateManyWithoutWishlistNestedInput
  events?: Prisma.wishlist_eventUncheckedUpdateManyWithoutWishlistNestedInput
}

export type wishlistCreateManyInput = {
  id?: string
  shop: string
  key: string
  customerId?: string | null
  visitorId?: string | null
  email?: string | null
  name?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type wishlistUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  visitorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type wishlistUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  visitorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WishlistListRelationFilter = {
  every?: Prisma.wishlistWhereInput
  some?: Prisma.wishlistWhereInput
  none?: Prisma.wishlistWhereInput
}

export type wishlistOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type wishlistShopKeyCompoundUniqueInput = {
  shop: string
  key: string
}

export type wishlistCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  shop?: Prisma.SortOrder
  key?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  visitorId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type wishlistMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  shop?: Prisma.SortOrder
  key?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  visitorId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type wishlistMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  shop?: Prisma.SortOrder
  key?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  visitorId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WishlistScalarRelationFilter = {
  is?: Prisma.wishlistWhereInput
  isNot?: Prisma.wishlistWhereInput
}

export type WishlistNullableScalarRelationFilter = {
  is?: Prisma.wishlistWhereInput | null
  isNot?: Prisma.wishlistWhereInput | null
}

export type wishlistCreateNestedManyWithoutStoreInput = {
  create?: Prisma.XOR<Prisma.wishlistCreateWithoutStoreInput, Prisma.wishlistUncheckedCreateWithoutStoreInput> | Prisma.wishlistCreateWithoutStoreInput[] | Prisma.wishlistUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.wishlistCreateOrConnectWithoutStoreInput | Prisma.wishlistCreateOrConnectWithoutStoreInput[]
  createMany?: Prisma.wishlistCreateManyStoreInputEnvelope
  connect?: Prisma.wishlistWhereUniqueInput | Prisma.wishlistWhereUniqueInput[]
}

export type wishlistUncheckedCreateNestedManyWithoutStoreInput = {
  create?: Prisma.XOR<Prisma.wishlistCreateWithoutStoreInput, Prisma.wishlistUncheckedCreateWithoutStoreInput> | Prisma.wishlistCreateWithoutStoreInput[] | Prisma.wishlistUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.wishlistCreateOrConnectWithoutStoreInput | Prisma.wishlistCreateOrConnectWithoutStoreInput[]
  createMany?: Prisma.wishlistCreateManyStoreInputEnvelope
  connect?: Prisma.wishlistWhereUniqueInput | Prisma.wishlistWhereUniqueInput[]
}

export type wishlistUpdateManyWithoutStoreNestedInput = {
  create?: Prisma.XOR<Prisma.wishlistCreateWithoutStoreInput, Prisma.wishlistUncheckedCreateWithoutStoreInput> | Prisma.wishlistCreateWithoutStoreInput[] | Prisma.wishlistUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.wishlistCreateOrConnectWithoutStoreInput | Prisma.wishlistCreateOrConnectWithoutStoreInput[]
  upsert?: Prisma.wishlistUpsertWithWhereUniqueWithoutStoreInput | Prisma.wishlistUpsertWithWhereUniqueWithoutStoreInput[]
  createMany?: Prisma.wishlistCreateManyStoreInputEnvelope
  set?: Prisma.wishlistWhereUniqueInput | Prisma.wishlistWhereUniqueInput[]
  disconnect?: Prisma.wishlistWhereUniqueInput | Prisma.wishlistWhereUniqueInput[]
  delete?: Prisma.wishlistWhereUniqueInput | Prisma.wishlistWhereUniqueInput[]
  connect?: Prisma.wishlistWhereUniqueInput | Prisma.wishlistWhereUniqueInput[]
  update?: Prisma.wishlistUpdateWithWhereUniqueWithoutStoreInput | Prisma.wishlistUpdateWithWhereUniqueWithoutStoreInput[]
  updateMany?: Prisma.wishlistUpdateManyWithWhereWithoutStoreInput | Prisma.wishlistUpdateManyWithWhereWithoutStoreInput[]
  deleteMany?: Prisma.wishlistScalarWhereInput | Prisma.wishlistScalarWhereInput[]
}

export type wishlistUncheckedUpdateManyWithoutStoreNestedInput = {
  create?: Prisma.XOR<Prisma.wishlistCreateWithoutStoreInput, Prisma.wishlistUncheckedCreateWithoutStoreInput> | Prisma.wishlistCreateWithoutStoreInput[] | Prisma.wishlistUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.wishlistCreateOrConnectWithoutStoreInput | Prisma.wishlistCreateOrConnectWithoutStoreInput[]
  upsert?: Prisma.wishlistUpsertWithWhereUniqueWithoutStoreInput | Prisma.wishlistUpsertWithWhereUniqueWithoutStoreInput[]
  createMany?: Prisma.wishlistCreateManyStoreInputEnvelope
  set?: Prisma.wishlistWhereUniqueInput | Prisma.wishlistWhereUniqueInput[]
  disconnect?: Prisma.wishlistWhereUniqueInput | Prisma.wishlistWhereUniqueInput[]
  delete?: Prisma.wishlistWhereUniqueInput | Prisma.wishlistWhereUniqueInput[]
  connect?: Prisma.wishlistWhereUniqueInput | Prisma.wishlistWhereUniqueInput[]
  update?: Prisma.wishlistUpdateWithWhereUniqueWithoutStoreInput | Prisma.wishlistUpdateWithWhereUniqueWithoutStoreInput[]
  updateMany?: Prisma.wishlistUpdateManyWithWhereWithoutStoreInput | Prisma.wishlistUpdateManyWithWhereWithoutStoreInput[]
  deleteMany?: Prisma.wishlistScalarWhereInput | Prisma.wishlistScalarWhereInput[]
}

export type wishlistCreateNestedOneWithoutItemsInput = {
  create?: Prisma.XOR<Prisma.wishlistCreateWithoutItemsInput, Prisma.wishlistUncheckedCreateWithoutItemsInput>
  connectOrCreate?: Prisma.wishlistCreateOrConnectWithoutItemsInput
  connect?: Prisma.wishlistWhereUniqueInput
}

export type wishlistUpdateOneRequiredWithoutItemsNestedInput = {
  create?: Prisma.XOR<Prisma.wishlistCreateWithoutItemsInput, Prisma.wishlistUncheckedCreateWithoutItemsInput>
  connectOrCreate?: Prisma.wishlistCreateOrConnectWithoutItemsInput
  upsert?: Prisma.wishlistUpsertWithoutItemsInput
  connect?: Prisma.wishlistWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.wishlistUpdateToOneWithWhereWithoutItemsInput, Prisma.wishlistUpdateWithoutItemsInput>, Prisma.wishlistUncheckedUpdateWithoutItemsInput>
}

export type wishlistCreateNestedOneWithoutEventsInput = {
  create?: Prisma.XOR<Prisma.wishlistCreateWithoutEventsInput, Prisma.wishlistUncheckedCreateWithoutEventsInput>
  connectOrCreate?: Prisma.wishlistCreateOrConnectWithoutEventsInput
  connect?: Prisma.wishlistWhereUniqueInput
}

export type wishlistUpdateOneWithoutEventsNestedInput = {
  create?: Prisma.XOR<Prisma.wishlistCreateWithoutEventsInput, Prisma.wishlistUncheckedCreateWithoutEventsInput>
  connectOrCreate?: Prisma.wishlistCreateOrConnectWithoutEventsInput
  upsert?: Prisma.wishlistUpsertWithoutEventsInput
  disconnect?: Prisma.wishlistWhereInput | boolean
  delete?: Prisma.wishlistWhereInput | boolean
  connect?: Prisma.wishlistWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.wishlistUpdateToOneWithWhereWithoutEventsInput, Prisma.wishlistUpdateWithoutEventsInput>, Prisma.wishlistUncheckedUpdateWithoutEventsInput>
}

export type wishlistCreateWithoutStoreInput = {
  id?: string
  key: string
  customerId?: string | null
  visitorId?: string | null
  email?: string | null
  name?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  items?: Prisma.wishlist_itemCreateNestedManyWithoutWishlistInput
  events?: Prisma.wishlist_eventCreateNestedManyWithoutWishlistInput
}

export type wishlistUncheckedCreateWithoutStoreInput = {
  id?: string
  key: string
  customerId?: string | null
  visitorId?: string | null
  email?: string | null
  name?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  items?: Prisma.wishlist_itemUncheckedCreateNestedManyWithoutWishlistInput
  events?: Prisma.wishlist_eventUncheckedCreateNestedManyWithoutWishlistInput
}

export type wishlistCreateOrConnectWithoutStoreInput = {
  where: Prisma.wishlistWhereUniqueInput
  create: Prisma.XOR<Prisma.wishlistCreateWithoutStoreInput, Prisma.wishlistUncheckedCreateWithoutStoreInput>
}

export type wishlistCreateManyStoreInputEnvelope = {
  data: Prisma.wishlistCreateManyStoreInput | Prisma.wishlistCreateManyStoreInput[]
  skipDuplicates?: boolean
}

export type wishlistUpsertWithWhereUniqueWithoutStoreInput = {
  where: Prisma.wishlistWhereUniqueInput
  update: Prisma.XOR<Prisma.wishlistUpdateWithoutStoreInput, Prisma.wishlistUncheckedUpdateWithoutStoreInput>
  create: Prisma.XOR<Prisma.wishlistCreateWithoutStoreInput, Prisma.wishlistUncheckedCreateWithoutStoreInput>
}

export type wishlistUpdateWithWhereUniqueWithoutStoreInput = {
  where: Prisma.wishlistWhereUniqueInput
  data: Prisma.XOR<Prisma.wishlistUpdateWithoutStoreInput, Prisma.wishlistUncheckedUpdateWithoutStoreInput>
}

export type wishlistUpdateManyWithWhereWithoutStoreInput = {
  where: Prisma.wishlistScalarWhereInput
  data: Prisma.XOR<Prisma.wishlistUpdateManyMutationInput, Prisma.wishlistUncheckedUpdateManyWithoutStoreInput>
}

export type wishlistScalarWhereInput = {
  AND?: Prisma.wishlistScalarWhereInput | Prisma.wishlistScalarWhereInput[]
  OR?: Prisma.wishlistScalarWhereInput[]
  NOT?: Prisma.wishlistScalarWhereInput | Prisma.wishlistScalarWhereInput[]
  id?: Prisma.StringFilter<"wishlist"> | string
  shop?: Prisma.StringFilter<"wishlist"> | string
  key?: Prisma.StringFilter<"wishlist"> | string
  customerId?: Prisma.StringNullableFilter<"wishlist"> | string | null
  visitorId?: Prisma.StringNullableFilter<"wishlist"> | string | null
  email?: Prisma.StringNullableFilter<"wishlist"> | string | null
  name?: Prisma.StringNullableFilter<"wishlist"> | string | null
  createdAt?: Prisma.DateTimeFilter<"wishlist"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"wishlist"> | Date | string
}

export type wishlistCreateWithoutItemsInput = {
  id?: string
  key: string
  customerId?: string | null
  visitorId?: string | null
  email?: string | null
  name?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  store: Prisma.storesCreateNestedOneWithoutWishlistsInput
  events?: Prisma.wishlist_eventCreateNestedManyWithoutWishlistInput
}

export type wishlistUncheckedCreateWithoutItemsInput = {
  id?: string
  shop: string
  key: string
  customerId?: string | null
  visitorId?: string | null
  email?: string | null
  name?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  events?: Prisma.wishlist_eventUncheckedCreateNestedManyWithoutWishlistInput
}

export type wishlistCreateOrConnectWithoutItemsInput = {
  where: Prisma.wishlistWhereUniqueInput
  create: Prisma.XOR<Prisma.wishlistCreateWithoutItemsInput, Prisma.wishlistUncheckedCreateWithoutItemsInput>
}

export type wishlistUpsertWithoutItemsInput = {
  update: Prisma.XOR<Prisma.wishlistUpdateWithoutItemsInput, Prisma.wishlistUncheckedUpdateWithoutItemsInput>
  create: Prisma.XOR<Prisma.wishlistCreateWithoutItemsInput, Prisma.wishlistUncheckedCreateWithoutItemsInput>
  where?: Prisma.wishlistWhereInput
}

export type wishlistUpdateToOneWithWhereWithoutItemsInput = {
  where?: Prisma.wishlistWhereInput
  data: Prisma.XOR<Prisma.wishlistUpdateWithoutItemsInput, Prisma.wishlistUncheckedUpdateWithoutItemsInput>
}

export type wishlistUpdateWithoutItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  visitorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  store?: Prisma.storesUpdateOneRequiredWithoutWishlistsNestedInput
  events?: Prisma.wishlist_eventUpdateManyWithoutWishlistNestedInput
}

export type wishlistUncheckedUpdateWithoutItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  visitorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  events?: Prisma.wishlist_eventUncheckedUpdateManyWithoutWishlistNestedInput
}

export type wishlistCreateWithoutEventsInput = {
  id?: string
  key: string
  customerId?: string | null
  visitorId?: string | null
  email?: string | null
  name?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  store: Prisma.storesCreateNestedOneWithoutWishlistsInput
  items?: Prisma.wishlist_itemCreateNestedManyWithoutWishlistInput
}

export type wishlistUncheckedCreateWithoutEventsInput = {
  id?: string
  shop: string
  key: string
  customerId?: string | null
  visitorId?: string | null
  email?: string | null
  name?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  items?: Prisma.wishlist_itemUncheckedCreateNestedManyWithoutWishlistInput
}

export type wishlistCreateOrConnectWithoutEventsInput = {
  where: Prisma.wishlistWhereUniqueInput
  create: Prisma.XOR<Prisma.wishlistCreateWithoutEventsInput, Prisma.wishlistUncheckedCreateWithoutEventsInput>
}

export type wishlistUpsertWithoutEventsInput = {
  update: Prisma.XOR<Prisma.wishlistUpdateWithoutEventsInput, Prisma.wishlistUncheckedUpdateWithoutEventsInput>
  create: Prisma.XOR<Prisma.wishlistCreateWithoutEventsInput, Prisma.wishlistUncheckedCreateWithoutEventsInput>
  where?: Prisma.wishlistWhereInput
}

export type wishlistUpdateToOneWithWhereWithoutEventsInput = {
  where?: Prisma.wishlistWhereInput
  data: Prisma.XOR<Prisma.wishlistUpdateWithoutEventsInput, Prisma.wishlistUncheckedUpdateWithoutEventsInput>
}

export type wishlistUpdateWithoutEventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  visitorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  store?: Prisma.storesUpdateOneRequiredWithoutWishlistsNestedInput
  items?: Prisma.wishlist_itemUpdateManyWithoutWishlistNestedInput
}

export type wishlistUncheckedUpdateWithoutEventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  visitorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  items?: Prisma.wishlist_itemUncheckedUpdateManyWithoutWishlistNestedInput
}

export type wishlistCreateManyStoreInput = {
  id?: string
  key: string
  customerId?: string | null
  visitorId?: string | null
  email?: string | null
  name?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type wishlistUpdateWithoutStoreInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  visitorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  items?: Prisma.wishlist_itemUpdateManyWithoutWishlistNestedInput
  events?: Prisma.wishlist_eventUpdateManyWithoutWishlistNestedInput
}

export type wishlistUncheckedUpdateWithoutStoreInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  visitorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  items?: Prisma.wishlist_itemUncheckedUpdateManyWithoutWishlistNestedInput
  events?: Prisma.wishlist_eventUncheckedUpdateManyWithoutWishlistNestedInput
}

export type wishlistUncheckedUpdateManyWithoutStoreInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  visitorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type WishlistCountOutputType
 */

export type WishlistCountOutputType = {
  items: number
  events: number
}

export type WishlistCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  items?: boolean | WishlistCountOutputTypeCountItemsArgs
  events?: boolean | WishlistCountOutputTypeCountEventsArgs
}

/**
 * WishlistCountOutputType without action
 */
export type WishlistCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WishlistCountOutputType
   */
  select?: Prisma.WishlistCountOutputTypeSelect<ExtArgs> | null
}

/**
 * WishlistCountOutputType without action
 */
export type WishlistCountOutputTypeCountItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.wishlist_itemWhereInput
}

/**
 * WishlistCountOutputType without action
 */
export type WishlistCountOutputTypeCountEventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.wishlist_eventWhereInput
}


export type wishlistSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  shop?: boolean
  key?: boolean
  customerId?: boolean
  visitorId?: boolean
  email?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  store?: boolean | Prisma.storesDefaultArgs<ExtArgs>
  items?: boolean | Prisma.wishlist$itemsArgs<ExtArgs>
  events?: boolean | Prisma.wishlist$eventsArgs<ExtArgs>
  _count?: boolean | Prisma.WishlistCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["wishlist"]>

export type wishlistSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  shop?: boolean
  key?: boolean
  customerId?: boolean
  visitorId?: boolean
  email?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  store?: boolean | Prisma.storesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["wishlist"]>

export type wishlistSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  shop?: boolean
  key?: boolean
  customerId?: boolean
  visitorId?: boolean
  email?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  store?: boolean | Prisma.storesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["wishlist"]>

export type wishlistSelectScalar = {
  id?: boolean
  shop?: boolean
  key?: boolean
  customerId?: boolean
  visitorId?: boolean
  email?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type wishlistOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "shop" | "key" | "customerId" | "visitorId" | "email" | "name" | "createdAt" | "updatedAt", ExtArgs["result"]["wishlist"]>
export type wishlistInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  store?: boolean | Prisma.storesDefaultArgs<ExtArgs>
  items?: boolean | Prisma.wishlist$itemsArgs<ExtArgs>
  events?: boolean | Prisma.wishlist$eventsArgs<ExtArgs>
  _count?: boolean | Prisma.WishlistCountOutputTypeDefaultArgs<ExtArgs>
}
export type wishlistIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  store?: boolean | Prisma.storesDefaultArgs<ExtArgs>
}
export type wishlistIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  store?: boolean | Prisma.storesDefaultArgs<ExtArgs>
}

export type $wishlistPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "wishlist"
  objects: {
    store: Prisma.$storesPayload<ExtArgs>
    items: Prisma.$wishlist_itemPayload<ExtArgs>[]
    events: Prisma.$wishlist_eventPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    shop: string
    key: string
    customerId: string | null
    visitorId: string | null
    email: string | null
    name: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["wishlist"]>
  composites: {}
}

export type wishlistGetPayload<S extends boolean | null | undefined | wishlistDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$wishlistPayload, S>

export type wishlistCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<wishlistFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WishlistCountAggregateInputType | true
  }

export interface wishlistDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['wishlist'], meta: { name: 'wishlist' } }
  /**
   * Find zero or one Wishlist that matches the filter.
   * @param {wishlistFindUniqueArgs} args - Arguments to find a Wishlist
   * @example
   * // Get one Wishlist
   * const wishlist = await prisma.wishlist.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends wishlistFindUniqueArgs>(args: Prisma.SelectSubset<T, wishlistFindUniqueArgs<ExtArgs>>): Prisma.Prisma__wishlistClient<runtime.Types.Result.GetResult<Prisma.$wishlistPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Wishlist that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {wishlistFindUniqueOrThrowArgs} args - Arguments to find a Wishlist
   * @example
   * // Get one Wishlist
   * const wishlist = await prisma.wishlist.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends wishlistFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, wishlistFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__wishlistClient<runtime.Types.Result.GetResult<Prisma.$wishlistPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Wishlist that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlistFindFirstArgs} args - Arguments to find a Wishlist
   * @example
   * // Get one Wishlist
   * const wishlist = await prisma.wishlist.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends wishlistFindFirstArgs>(args?: Prisma.SelectSubset<T, wishlistFindFirstArgs<ExtArgs>>): Prisma.Prisma__wishlistClient<runtime.Types.Result.GetResult<Prisma.$wishlistPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Wishlist that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlistFindFirstOrThrowArgs} args - Arguments to find a Wishlist
   * @example
   * // Get one Wishlist
   * const wishlist = await prisma.wishlist.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends wishlistFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, wishlistFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__wishlistClient<runtime.Types.Result.GetResult<Prisma.$wishlistPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Wishlists that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlistFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Wishlists
   * const wishlists = await prisma.wishlist.findMany()
   * 
   * // Get first 10 Wishlists
   * const wishlists = await prisma.wishlist.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const wishlistWithIdOnly = await prisma.wishlist.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends wishlistFindManyArgs>(args?: Prisma.SelectSubset<T, wishlistFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlistPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Wishlist.
   * @param {wishlistCreateArgs} args - Arguments to create a Wishlist.
   * @example
   * // Create one Wishlist
   * const Wishlist = await prisma.wishlist.create({
   *   data: {
   *     // ... data to create a Wishlist
   *   }
   * })
   * 
   */
  create<T extends wishlistCreateArgs>(args: Prisma.SelectSubset<T, wishlistCreateArgs<ExtArgs>>): Prisma.Prisma__wishlistClient<runtime.Types.Result.GetResult<Prisma.$wishlistPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Wishlists.
   * @param {wishlistCreateManyArgs} args - Arguments to create many Wishlists.
   * @example
   * // Create many Wishlists
   * const wishlist = await prisma.wishlist.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends wishlistCreateManyArgs>(args?: Prisma.SelectSubset<T, wishlistCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Wishlists and returns the data saved in the database.
   * @param {wishlistCreateManyAndReturnArgs} args - Arguments to create many Wishlists.
   * @example
   * // Create many Wishlists
   * const wishlist = await prisma.wishlist.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Wishlists and only return the `id`
   * const wishlistWithIdOnly = await prisma.wishlist.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends wishlistCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, wishlistCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlistPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Wishlist.
   * @param {wishlistDeleteArgs} args - Arguments to delete one Wishlist.
   * @example
   * // Delete one Wishlist
   * const Wishlist = await prisma.wishlist.delete({
   *   where: {
   *     // ... filter to delete one Wishlist
   *   }
   * })
   * 
   */
  delete<T extends wishlistDeleteArgs>(args: Prisma.SelectSubset<T, wishlistDeleteArgs<ExtArgs>>): Prisma.Prisma__wishlistClient<runtime.Types.Result.GetResult<Prisma.$wishlistPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Wishlist.
   * @param {wishlistUpdateArgs} args - Arguments to update one Wishlist.
   * @example
   * // Update one Wishlist
   * const wishlist = await prisma.wishlist.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends wishlistUpdateArgs>(args: Prisma.SelectSubset<T, wishlistUpdateArgs<ExtArgs>>): Prisma.Prisma__wishlistClient<runtime.Types.Result.GetResult<Prisma.$wishlistPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Wishlists.
   * @param {wishlistDeleteManyArgs} args - Arguments to filter Wishlists to delete.
   * @example
   * // Delete a few Wishlists
   * const { count } = await prisma.wishlist.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends wishlistDeleteManyArgs>(args?: Prisma.SelectSubset<T, wishlistDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Wishlists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlistUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Wishlists
   * const wishlist = await prisma.wishlist.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends wishlistUpdateManyArgs>(args: Prisma.SelectSubset<T, wishlistUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Wishlists and returns the data updated in the database.
   * @param {wishlistUpdateManyAndReturnArgs} args - Arguments to update many Wishlists.
   * @example
   * // Update many Wishlists
   * const wishlist = await prisma.wishlist.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Wishlists and only return the `id`
   * const wishlistWithIdOnly = await prisma.wishlist.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends wishlistUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, wishlistUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlistPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Wishlist.
   * @param {wishlistUpsertArgs} args - Arguments to update or create a Wishlist.
   * @example
   * // Update or create a Wishlist
   * const wishlist = await prisma.wishlist.upsert({
   *   create: {
   *     // ... data to create a Wishlist
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Wishlist we want to update
   *   }
   * })
   */
  upsert<T extends wishlistUpsertArgs>(args: Prisma.SelectSubset<T, wishlistUpsertArgs<ExtArgs>>): Prisma.Prisma__wishlistClient<runtime.Types.Result.GetResult<Prisma.$wishlistPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Wishlists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlistCountArgs} args - Arguments to filter Wishlists to count.
   * @example
   * // Count the number of Wishlists
   * const count = await prisma.wishlist.count({
   *   where: {
   *     // ... the filter for the Wishlists we want to count
   *   }
   * })
  **/
  count<T extends wishlistCountArgs>(
    args?: Prisma.Subset<T, wishlistCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WishlistCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Wishlist.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WishlistAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WishlistAggregateArgs>(args: Prisma.Subset<T, WishlistAggregateArgs>): Prisma.PrismaPromise<GetWishlistAggregateType<T>>

  /**
   * Group by Wishlist.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlistGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends wishlistGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: wishlistGroupByArgs['orderBy'] }
      : { orderBy?: wishlistGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, wishlistGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWishlistGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the wishlist model
 */
readonly fields: wishlistFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for wishlist.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__wishlistClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  store<T extends Prisma.storesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.storesDefaultArgs<ExtArgs>>): Prisma.Prisma__storesClient<runtime.Types.Result.GetResult<Prisma.$storesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  items<T extends Prisma.wishlist$itemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.wishlist$itemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlist_itemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  events<T extends Prisma.wishlist$eventsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.wishlist$eventsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlist_eventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the wishlist model
 */
export interface wishlistFieldRefs {
  readonly id: Prisma.FieldRef<"wishlist", 'String'>
  readonly shop: Prisma.FieldRef<"wishlist", 'String'>
  readonly key: Prisma.FieldRef<"wishlist", 'String'>
  readonly customerId: Prisma.FieldRef<"wishlist", 'String'>
  readonly visitorId: Prisma.FieldRef<"wishlist", 'String'>
  readonly email: Prisma.FieldRef<"wishlist", 'String'>
  readonly name: Prisma.FieldRef<"wishlist", 'String'>
  readonly createdAt: Prisma.FieldRef<"wishlist", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"wishlist", 'DateTime'>
}
    

// Custom InputTypes
/**
 * wishlist findUnique
 */
export type wishlistFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist
   */
  select?: Prisma.wishlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist
   */
  omit?: Prisma.wishlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlistInclude<ExtArgs> | null
  /**
   * Filter, which wishlist to fetch.
   */
  where: Prisma.wishlistWhereUniqueInput
}

/**
 * wishlist findUniqueOrThrow
 */
export type wishlistFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist
   */
  select?: Prisma.wishlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist
   */
  omit?: Prisma.wishlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlistInclude<ExtArgs> | null
  /**
   * Filter, which wishlist to fetch.
   */
  where: Prisma.wishlistWhereUniqueInput
}

/**
 * wishlist findFirst
 */
export type wishlistFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist
   */
  select?: Prisma.wishlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist
   */
  omit?: Prisma.wishlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlistInclude<ExtArgs> | null
  /**
   * Filter, which wishlist to fetch.
   */
  where?: Prisma.wishlistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlists to fetch.
   */
  orderBy?: Prisma.wishlistOrderByWithRelationInput | Prisma.wishlistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for wishlists.
   */
  cursor?: Prisma.wishlistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of wishlists.
   */
  distinct?: Prisma.WishlistScalarFieldEnum | Prisma.WishlistScalarFieldEnum[]
}

/**
 * wishlist findFirstOrThrow
 */
export type wishlistFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist
   */
  select?: Prisma.wishlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist
   */
  omit?: Prisma.wishlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlistInclude<ExtArgs> | null
  /**
   * Filter, which wishlist to fetch.
   */
  where?: Prisma.wishlistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlists to fetch.
   */
  orderBy?: Prisma.wishlistOrderByWithRelationInput | Prisma.wishlistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for wishlists.
   */
  cursor?: Prisma.wishlistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of wishlists.
   */
  distinct?: Prisma.WishlistScalarFieldEnum | Prisma.WishlistScalarFieldEnum[]
}

/**
 * wishlist findMany
 */
export type wishlistFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist
   */
  select?: Prisma.wishlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist
   */
  omit?: Prisma.wishlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlistInclude<ExtArgs> | null
  /**
   * Filter, which wishlists to fetch.
   */
  where?: Prisma.wishlistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlists to fetch.
   */
  orderBy?: Prisma.wishlistOrderByWithRelationInput | Prisma.wishlistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing wishlists.
   */
  cursor?: Prisma.wishlistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of wishlists.
   */
  distinct?: Prisma.WishlistScalarFieldEnum | Prisma.WishlistScalarFieldEnum[]
}

/**
 * wishlist create
 */
export type wishlistCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist
   */
  select?: Prisma.wishlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist
   */
  omit?: Prisma.wishlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlistInclude<ExtArgs> | null
  /**
   * The data needed to create a wishlist.
   */
  data: Prisma.XOR<Prisma.wishlistCreateInput, Prisma.wishlistUncheckedCreateInput>
}

/**
 * wishlist createMany
 */
export type wishlistCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many wishlists.
   */
  data: Prisma.wishlistCreateManyInput | Prisma.wishlistCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * wishlist createManyAndReturn
 */
export type wishlistCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist
   */
  select?: Prisma.wishlistSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist
   */
  omit?: Prisma.wishlistOmit<ExtArgs> | null
  /**
   * The data used to create many wishlists.
   */
  data: Prisma.wishlistCreateManyInput | Prisma.wishlistCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlistIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * wishlist update
 */
export type wishlistUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist
   */
  select?: Prisma.wishlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist
   */
  omit?: Prisma.wishlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlistInclude<ExtArgs> | null
  /**
   * The data needed to update a wishlist.
   */
  data: Prisma.XOR<Prisma.wishlistUpdateInput, Prisma.wishlistUncheckedUpdateInput>
  /**
   * Choose, which wishlist to update.
   */
  where: Prisma.wishlistWhereUniqueInput
}

/**
 * wishlist updateMany
 */
export type wishlistUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update wishlists.
   */
  data: Prisma.XOR<Prisma.wishlistUpdateManyMutationInput, Prisma.wishlistUncheckedUpdateManyInput>
  /**
   * Filter which wishlists to update
   */
  where?: Prisma.wishlistWhereInput
  /**
   * Limit how many wishlists to update.
   */
  limit?: number
}

/**
 * wishlist updateManyAndReturn
 */
export type wishlistUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist
   */
  select?: Prisma.wishlistSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist
   */
  omit?: Prisma.wishlistOmit<ExtArgs> | null
  /**
   * The data used to update wishlists.
   */
  data: Prisma.XOR<Prisma.wishlistUpdateManyMutationInput, Prisma.wishlistUncheckedUpdateManyInput>
  /**
   * Filter which wishlists to update
   */
  where?: Prisma.wishlistWhereInput
  /**
   * Limit how many wishlists to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlistIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * wishlist upsert
 */
export type wishlistUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist
   */
  select?: Prisma.wishlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist
   */
  omit?: Prisma.wishlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlistInclude<ExtArgs> | null
  /**
   * The filter to search for the wishlist to update in case it exists.
   */
  where: Prisma.wishlistWhereUniqueInput
  /**
   * In case the wishlist found by the `where` argument doesn't exist, create a new wishlist with this data.
   */
  create: Prisma.XOR<Prisma.wishlistCreateInput, Prisma.wishlistUncheckedCreateInput>
  /**
   * In case the wishlist was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.wishlistUpdateInput, Prisma.wishlistUncheckedUpdateInput>
}

/**
 * wishlist delete
 */
export type wishlistDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist
   */
  select?: Prisma.wishlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist
   */
  omit?: Prisma.wishlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlistInclude<ExtArgs> | null
  /**
   * Filter which wishlist to delete.
   */
  where: Prisma.wishlistWhereUniqueInput
}

/**
 * wishlist deleteMany
 */
export type wishlistDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which wishlists to delete
   */
  where?: Prisma.wishlistWhereInput
  /**
   * Limit how many wishlists to delete.
   */
  limit?: number
}

/**
 * wishlist.items
 */
export type wishlist$itemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_item
   */
  select?: Prisma.wishlist_itemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_item
   */
  omit?: Prisma.wishlist_itemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_itemInclude<ExtArgs> | null
  where?: Prisma.wishlist_itemWhereInput
  orderBy?: Prisma.wishlist_itemOrderByWithRelationInput | Prisma.wishlist_itemOrderByWithRelationInput[]
  cursor?: Prisma.wishlist_itemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Wishlist_itemScalarFieldEnum | Prisma.Wishlist_itemScalarFieldEnum[]
}

/**
 * wishlist.events
 */
export type wishlist$eventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_event
   */
  select?: Prisma.wishlist_eventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_event
   */
  omit?: Prisma.wishlist_eventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_eventInclude<ExtArgs> | null
  where?: Prisma.wishlist_eventWhereInput
  orderBy?: Prisma.wishlist_eventOrderByWithRelationInput | Prisma.wishlist_eventOrderByWithRelationInput[]
  cursor?: Prisma.wishlist_eventWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Wishlist_eventScalarFieldEnum | Prisma.Wishlist_eventScalarFieldEnum[]
}

/**
 * wishlist without action
 */
export type wishlistDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist
   */
  select?: Prisma.wishlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist
   */
  omit?: Prisma.wishlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlistInclude<ExtArgs> | null
}
