
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `wishlist_settings_profile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model wishlist_settings_profile
 * 
 */
export type wishlist_settings_profileModel = runtime.Types.Result.DefaultSelection<Prisma.$wishlist_settings_profilePayload>

export type AggregateWishlist_settings_profile = {
  _count: Wishlist_settings_profileCountAggregateOutputType | null
  _min: Wishlist_settings_profileMinAggregateOutputType | null
  _max: Wishlist_settings_profileMaxAggregateOutputType | null
}

export type Wishlist_settings_profileMinAggregateOutputType = {
  id: string | null
  fingerprint: string | null
  createdAt: Date | null
}

export type Wishlist_settings_profileMaxAggregateOutputType = {
  id: string | null
  fingerprint: string | null
  createdAt: Date | null
}

export type Wishlist_settings_profileCountAggregateOutputType = {
  id: number
  fingerprint: number
  settings: number
  createdAt: number
  _all: number
}


export type Wishlist_settings_profileMinAggregateInputType = {
  id?: true
  fingerprint?: true
  createdAt?: true
}

export type Wishlist_settings_profileMaxAggregateInputType = {
  id?: true
  fingerprint?: true
  createdAt?: true
}

export type Wishlist_settings_profileCountAggregateInputType = {
  id?: true
  fingerprint?: true
  settings?: true
  createdAt?: true
  _all?: true
}

export type Wishlist_settings_profileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which wishlist_settings_profile to aggregate.
   */
  where?: Prisma.wishlist_settings_profileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlist_settings_profiles to fetch.
   */
  orderBy?: Prisma.wishlist_settings_profileOrderByWithRelationInput | Prisma.wishlist_settings_profileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.wishlist_settings_profileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlist_settings_profiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlist_settings_profiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned wishlist_settings_profiles
  **/
  _count?: true | Wishlist_settings_profileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Wishlist_settings_profileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Wishlist_settings_profileMaxAggregateInputType
}

export type GetWishlist_settings_profileAggregateType<T extends Wishlist_settings_profileAggregateArgs> = {
      [P in keyof T & keyof AggregateWishlist_settings_profile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWishlist_settings_profile[P]>
    : Prisma.GetScalarType<T[P], AggregateWishlist_settings_profile[P]>
}




export type wishlist_settings_profileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.wishlist_settings_profileWhereInput
  orderBy?: Prisma.wishlist_settings_profileOrderByWithAggregationInput | Prisma.wishlist_settings_profileOrderByWithAggregationInput[]
  by: Prisma.Wishlist_settings_profileScalarFieldEnum[] | Prisma.Wishlist_settings_profileScalarFieldEnum
  having?: Prisma.wishlist_settings_profileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Wishlist_settings_profileCountAggregateInputType | true
  _min?: Wishlist_settings_profileMinAggregateInputType
  _max?: Wishlist_settings_profileMaxAggregateInputType
}

export type Wishlist_settings_profileGroupByOutputType = {
  id: string
  fingerprint: string
  settings: runtime.JsonValue
  createdAt: Date
  _count: Wishlist_settings_profileCountAggregateOutputType | null
  _min: Wishlist_settings_profileMinAggregateOutputType | null
  _max: Wishlist_settings_profileMaxAggregateOutputType | null
}

export type GetWishlist_settings_profileGroupByPayload<T extends wishlist_settings_profileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Wishlist_settings_profileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Wishlist_settings_profileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Wishlist_settings_profileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Wishlist_settings_profileGroupByOutputType[P]>
      }
    >
  >



export type wishlist_settings_profileWhereInput = {
  AND?: Prisma.wishlist_settings_profileWhereInput | Prisma.wishlist_settings_profileWhereInput[]
  OR?: Prisma.wishlist_settings_profileWhereInput[]
  NOT?: Prisma.wishlist_settings_profileWhereInput | Prisma.wishlist_settings_profileWhereInput[]
  id?: Prisma.StringFilter<"wishlist_settings_profile"> | string
  fingerprint?: Prisma.StringFilter<"wishlist_settings_profile"> | string
  settings?: Prisma.JsonFilter<"wishlist_settings_profile">
  createdAt?: Prisma.DateTimeFilter<"wishlist_settings_profile"> | Date | string
  assignments?: Prisma.Store_settingsListRelationFilter
}

export type wishlist_settings_profileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  fingerprint?: Prisma.SortOrder
  settings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  assignments?: Prisma.store_settingsOrderByRelationAggregateInput
}

export type wishlist_settings_profileWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  fingerprint?: string
  AND?: Prisma.wishlist_settings_profileWhereInput | Prisma.wishlist_settings_profileWhereInput[]
  OR?: Prisma.wishlist_settings_profileWhereInput[]
  NOT?: Prisma.wishlist_settings_profileWhereInput | Prisma.wishlist_settings_profileWhereInput[]
  settings?: Prisma.JsonFilter<"wishlist_settings_profile">
  createdAt?: Prisma.DateTimeFilter<"wishlist_settings_profile"> | Date | string
  assignments?: Prisma.Store_settingsListRelationFilter
}, "id" | "fingerprint">

export type wishlist_settings_profileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  fingerprint?: Prisma.SortOrder
  settings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.wishlist_settings_profileCountOrderByAggregateInput
  _max?: Prisma.wishlist_settings_profileMaxOrderByAggregateInput
  _min?: Prisma.wishlist_settings_profileMinOrderByAggregateInput
}

export type wishlist_settings_profileScalarWhereWithAggregatesInput = {
  AND?: Prisma.wishlist_settings_profileScalarWhereWithAggregatesInput | Prisma.wishlist_settings_profileScalarWhereWithAggregatesInput[]
  OR?: Prisma.wishlist_settings_profileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.wishlist_settings_profileScalarWhereWithAggregatesInput | Prisma.wishlist_settings_profileScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"wishlist_settings_profile"> | string
  fingerprint?: Prisma.StringWithAggregatesFilter<"wishlist_settings_profile"> | string
  settings?: Prisma.JsonWithAggregatesFilter<"wishlist_settings_profile">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"wishlist_settings_profile"> | Date | string
}

export type wishlist_settings_profileCreateInput = {
  id?: string
  fingerprint: string
  settings: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  assignments?: Prisma.store_settingsCreateNestedManyWithoutSettingsProfileInput
}

export type wishlist_settings_profileUncheckedCreateInput = {
  id?: string
  fingerprint: string
  settings: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  assignments?: Prisma.store_settingsUncheckedCreateNestedManyWithoutSettingsProfileInput
}

export type wishlist_settings_profileUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fingerprint?: Prisma.StringFieldUpdateOperationsInput | string
  settings?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assignments?: Prisma.store_settingsUpdateManyWithoutSettingsProfileNestedInput
}

export type wishlist_settings_profileUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fingerprint?: Prisma.StringFieldUpdateOperationsInput | string
  settings?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assignments?: Prisma.store_settingsUncheckedUpdateManyWithoutSettingsProfileNestedInput
}

export type wishlist_settings_profileCreateManyInput = {
  id?: string
  fingerprint: string
  settings: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type wishlist_settings_profileUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fingerprint?: Prisma.StringFieldUpdateOperationsInput | string
  settings?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type wishlist_settings_profileUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fingerprint?: Prisma.StringFieldUpdateOperationsInput | string
  settings?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Wishlist_settings_profileNullableScalarRelationFilter = {
  is?: Prisma.wishlist_settings_profileWhereInput | null
  isNot?: Prisma.wishlist_settings_profileWhereInput | null
}

export type wishlist_settings_profileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fingerprint?: Prisma.SortOrder
  settings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type wishlist_settings_profileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fingerprint?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type wishlist_settings_profileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fingerprint?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type wishlist_settings_profileCreateNestedOneWithoutAssignmentsInput = {
  create?: Prisma.XOR<Prisma.wishlist_settings_profileCreateWithoutAssignmentsInput, Prisma.wishlist_settings_profileUncheckedCreateWithoutAssignmentsInput>
  connectOrCreate?: Prisma.wishlist_settings_profileCreateOrConnectWithoutAssignmentsInput
  connect?: Prisma.wishlist_settings_profileWhereUniqueInput
}

export type wishlist_settings_profileUpdateOneWithoutAssignmentsNestedInput = {
  create?: Prisma.XOR<Prisma.wishlist_settings_profileCreateWithoutAssignmentsInput, Prisma.wishlist_settings_profileUncheckedCreateWithoutAssignmentsInput>
  connectOrCreate?: Prisma.wishlist_settings_profileCreateOrConnectWithoutAssignmentsInput
  upsert?: Prisma.wishlist_settings_profileUpsertWithoutAssignmentsInput
  disconnect?: Prisma.wishlist_settings_profileWhereInput | boolean
  delete?: Prisma.wishlist_settings_profileWhereInput | boolean
  connect?: Prisma.wishlist_settings_profileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.wishlist_settings_profileUpdateToOneWithWhereWithoutAssignmentsInput, Prisma.wishlist_settings_profileUpdateWithoutAssignmentsInput>, Prisma.wishlist_settings_profileUncheckedUpdateWithoutAssignmentsInput>
}

export type wishlist_settings_profileCreateWithoutAssignmentsInput = {
  id?: string
  fingerprint: string
  settings: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type wishlist_settings_profileUncheckedCreateWithoutAssignmentsInput = {
  id?: string
  fingerprint: string
  settings: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type wishlist_settings_profileCreateOrConnectWithoutAssignmentsInput = {
  where: Prisma.wishlist_settings_profileWhereUniqueInput
  create: Prisma.XOR<Prisma.wishlist_settings_profileCreateWithoutAssignmentsInput, Prisma.wishlist_settings_profileUncheckedCreateWithoutAssignmentsInput>
}

export type wishlist_settings_profileUpsertWithoutAssignmentsInput = {
  update: Prisma.XOR<Prisma.wishlist_settings_profileUpdateWithoutAssignmentsInput, Prisma.wishlist_settings_profileUncheckedUpdateWithoutAssignmentsInput>
  create: Prisma.XOR<Prisma.wishlist_settings_profileCreateWithoutAssignmentsInput, Prisma.wishlist_settings_profileUncheckedCreateWithoutAssignmentsInput>
  where?: Prisma.wishlist_settings_profileWhereInput
}

export type wishlist_settings_profileUpdateToOneWithWhereWithoutAssignmentsInput = {
  where?: Prisma.wishlist_settings_profileWhereInput
  data: Prisma.XOR<Prisma.wishlist_settings_profileUpdateWithoutAssignmentsInput, Prisma.wishlist_settings_profileUncheckedUpdateWithoutAssignmentsInput>
}

export type wishlist_settings_profileUpdateWithoutAssignmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fingerprint?: Prisma.StringFieldUpdateOperationsInput | string
  settings?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type wishlist_settings_profileUncheckedUpdateWithoutAssignmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fingerprint?: Prisma.StringFieldUpdateOperationsInput | string
  settings?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type Wishlist_settings_profileCountOutputType
 */

export type Wishlist_settings_profileCountOutputType = {
  assignments: number
}

export type Wishlist_settings_profileCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  assignments?: boolean | Wishlist_settings_profileCountOutputTypeCountAssignmentsArgs
}

/**
 * Wishlist_settings_profileCountOutputType without action
 */
export type Wishlist_settings_profileCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Wishlist_settings_profileCountOutputType
   */
  select?: Prisma.Wishlist_settings_profileCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Wishlist_settings_profileCountOutputType without action
 */
export type Wishlist_settings_profileCountOutputTypeCountAssignmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.store_settingsWhereInput
}


export type wishlist_settings_profileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fingerprint?: boolean
  settings?: boolean
  createdAt?: boolean
  assignments?: boolean | Prisma.wishlist_settings_profile$assignmentsArgs<ExtArgs>
  _count?: boolean | Prisma.Wishlist_settings_profileCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["wishlist_settings_profile"]>

export type wishlist_settings_profileSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fingerprint?: boolean
  settings?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["wishlist_settings_profile"]>

export type wishlist_settings_profileSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fingerprint?: boolean
  settings?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["wishlist_settings_profile"]>

export type wishlist_settings_profileSelectScalar = {
  id?: boolean
  fingerprint?: boolean
  settings?: boolean
  createdAt?: boolean
}

export type wishlist_settings_profileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "fingerprint" | "settings" | "createdAt", ExtArgs["result"]["wishlist_settings_profile"]>
export type wishlist_settings_profileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  assignments?: boolean | Prisma.wishlist_settings_profile$assignmentsArgs<ExtArgs>
  _count?: boolean | Prisma.Wishlist_settings_profileCountOutputTypeDefaultArgs<ExtArgs>
}
export type wishlist_settings_profileIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type wishlist_settings_profileIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $wishlist_settings_profilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "wishlist_settings_profile"
  objects: {
    assignments: Prisma.$store_settingsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    fingerprint: string
    settings: runtime.JsonValue
    createdAt: Date
  }, ExtArgs["result"]["wishlist_settings_profile"]>
  composites: {}
}

export type wishlist_settings_profileGetPayload<S extends boolean | null | undefined | wishlist_settings_profileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$wishlist_settings_profilePayload, S>

export type wishlist_settings_profileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<wishlist_settings_profileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Wishlist_settings_profileCountAggregateInputType | true
  }

export interface wishlist_settings_profileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['wishlist_settings_profile'], meta: { name: 'wishlist_settings_profile' } }
  /**
   * Find zero or one Wishlist_settings_profile that matches the filter.
   * @param {wishlist_settings_profileFindUniqueArgs} args - Arguments to find a Wishlist_settings_profile
   * @example
   * // Get one Wishlist_settings_profile
   * const wishlist_settings_profile = await prisma.wishlist_settings_profile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends wishlist_settings_profileFindUniqueArgs>(args: Prisma.SelectSubset<T, wishlist_settings_profileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__wishlist_settings_profileClient<runtime.Types.Result.GetResult<Prisma.$wishlist_settings_profilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Wishlist_settings_profile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {wishlist_settings_profileFindUniqueOrThrowArgs} args - Arguments to find a Wishlist_settings_profile
   * @example
   * // Get one Wishlist_settings_profile
   * const wishlist_settings_profile = await prisma.wishlist_settings_profile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends wishlist_settings_profileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, wishlist_settings_profileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__wishlist_settings_profileClient<runtime.Types.Result.GetResult<Prisma.$wishlist_settings_profilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Wishlist_settings_profile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_settings_profileFindFirstArgs} args - Arguments to find a Wishlist_settings_profile
   * @example
   * // Get one Wishlist_settings_profile
   * const wishlist_settings_profile = await prisma.wishlist_settings_profile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends wishlist_settings_profileFindFirstArgs>(args?: Prisma.SelectSubset<T, wishlist_settings_profileFindFirstArgs<ExtArgs>>): Prisma.Prisma__wishlist_settings_profileClient<runtime.Types.Result.GetResult<Prisma.$wishlist_settings_profilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Wishlist_settings_profile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_settings_profileFindFirstOrThrowArgs} args - Arguments to find a Wishlist_settings_profile
   * @example
   * // Get one Wishlist_settings_profile
   * const wishlist_settings_profile = await prisma.wishlist_settings_profile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends wishlist_settings_profileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, wishlist_settings_profileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__wishlist_settings_profileClient<runtime.Types.Result.GetResult<Prisma.$wishlist_settings_profilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Wishlist_settings_profiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_settings_profileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Wishlist_settings_profiles
   * const wishlist_settings_profiles = await prisma.wishlist_settings_profile.findMany()
   * 
   * // Get first 10 Wishlist_settings_profiles
   * const wishlist_settings_profiles = await prisma.wishlist_settings_profile.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const wishlist_settings_profileWithIdOnly = await prisma.wishlist_settings_profile.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends wishlist_settings_profileFindManyArgs>(args?: Prisma.SelectSubset<T, wishlist_settings_profileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlist_settings_profilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Wishlist_settings_profile.
   * @param {wishlist_settings_profileCreateArgs} args - Arguments to create a Wishlist_settings_profile.
   * @example
   * // Create one Wishlist_settings_profile
   * const Wishlist_settings_profile = await prisma.wishlist_settings_profile.create({
   *   data: {
   *     // ... data to create a Wishlist_settings_profile
   *   }
   * })
   * 
   */
  create<T extends wishlist_settings_profileCreateArgs>(args: Prisma.SelectSubset<T, wishlist_settings_profileCreateArgs<ExtArgs>>): Prisma.Prisma__wishlist_settings_profileClient<runtime.Types.Result.GetResult<Prisma.$wishlist_settings_profilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Wishlist_settings_profiles.
   * @param {wishlist_settings_profileCreateManyArgs} args - Arguments to create many Wishlist_settings_profiles.
   * @example
   * // Create many Wishlist_settings_profiles
   * const wishlist_settings_profile = await prisma.wishlist_settings_profile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends wishlist_settings_profileCreateManyArgs>(args?: Prisma.SelectSubset<T, wishlist_settings_profileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Wishlist_settings_profiles and returns the data saved in the database.
   * @param {wishlist_settings_profileCreateManyAndReturnArgs} args - Arguments to create many Wishlist_settings_profiles.
   * @example
   * // Create many Wishlist_settings_profiles
   * const wishlist_settings_profile = await prisma.wishlist_settings_profile.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Wishlist_settings_profiles and only return the `id`
   * const wishlist_settings_profileWithIdOnly = await prisma.wishlist_settings_profile.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends wishlist_settings_profileCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, wishlist_settings_profileCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlist_settings_profilePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Wishlist_settings_profile.
   * @param {wishlist_settings_profileDeleteArgs} args - Arguments to delete one Wishlist_settings_profile.
   * @example
   * // Delete one Wishlist_settings_profile
   * const Wishlist_settings_profile = await prisma.wishlist_settings_profile.delete({
   *   where: {
   *     // ... filter to delete one Wishlist_settings_profile
   *   }
   * })
   * 
   */
  delete<T extends wishlist_settings_profileDeleteArgs>(args: Prisma.SelectSubset<T, wishlist_settings_profileDeleteArgs<ExtArgs>>): Prisma.Prisma__wishlist_settings_profileClient<runtime.Types.Result.GetResult<Prisma.$wishlist_settings_profilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Wishlist_settings_profile.
   * @param {wishlist_settings_profileUpdateArgs} args - Arguments to update one Wishlist_settings_profile.
   * @example
   * // Update one Wishlist_settings_profile
   * const wishlist_settings_profile = await prisma.wishlist_settings_profile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends wishlist_settings_profileUpdateArgs>(args: Prisma.SelectSubset<T, wishlist_settings_profileUpdateArgs<ExtArgs>>): Prisma.Prisma__wishlist_settings_profileClient<runtime.Types.Result.GetResult<Prisma.$wishlist_settings_profilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Wishlist_settings_profiles.
   * @param {wishlist_settings_profileDeleteManyArgs} args - Arguments to filter Wishlist_settings_profiles to delete.
   * @example
   * // Delete a few Wishlist_settings_profiles
   * const { count } = await prisma.wishlist_settings_profile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends wishlist_settings_profileDeleteManyArgs>(args?: Prisma.SelectSubset<T, wishlist_settings_profileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Wishlist_settings_profiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_settings_profileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Wishlist_settings_profiles
   * const wishlist_settings_profile = await prisma.wishlist_settings_profile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends wishlist_settings_profileUpdateManyArgs>(args: Prisma.SelectSubset<T, wishlist_settings_profileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Wishlist_settings_profiles and returns the data updated in the database.
   * @param {wishlist_settings_profileUpdateManyAndReturnArgs} args - Arguments to update many Wishlist_settings_profiles.
   * @example
   * // Update many Wishlist_settings_profiles
   * const wishlist_settings_profile = await prisma.wishlist_settings_profile.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Wishlist_settings_profiles and only return the `id`
   * const wishlist_settings_profileWithIdOnly = await prisma.wishlist_settings_profile.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends wishlist_settings_profileUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, wishlist_settings_profileUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlist_settings_profilePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Wishlist_settings_profile.
   * @param {wishlist_settings_profileUpsertArgs} args - Arguments to update or create a Wishlist_settings_profile.
   * @example
   * // Update or create a Wishlist_settings_profile
   * const wishlist_settings_profile = await prisma.wishlist_settings_profile.upsert({
   *   create: {
   *     // ... data to create a Wishlist_settings_profile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Wishlist_settings_profile we want to update
   *   }
   * })
   */
  upsert<T extends wishlist_settings_profileUpsertArgs>(args: Prisma.SelectSubset<T, wishlist_settings_profileUpsertArgs<ExtArgs>>): Prisma.Prisma__wishlist_settings_profileClient<runtime.Types.Result.GetResult<Prisma.$wishlist_settings_profilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Wishlist_settings_profiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_settings_profileCountArgs} args - Arguments to filter Wishlist_settings_profiles to count.
   * @example
   * // Count the number of Wishlist_settings_profiles
   * const count = await prisma.wishlist_settings_profile.count({
   *   where: {
   *     // ... the filter for the Wishlist_settings_profiles we want to count
   *   }
   * })
  **/
  count<T extends wishlist_settings_profileCountArgs>(
    args?: Prisma.Subset<T, wishlist_settings_profileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Wishlist_settings_profileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Wishlist_settings_profile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Wishlist_settings_profileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Wishlist_settings_profileAggregateArgs>(args: Prisma.Subset<T, Wishlist_settings_profileAggregateArgs>): Prisma.PrismaPromise<GetWishlist_settings_profileAggregateType<T>>

  /**
   * Group by Wishlist_settings_profile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_settings_profileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends wishlist_settings_profileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: wishlist_settings_profileGroupByArgs['orderBy'] }
      : { orderBy?: wishlist_settings_profileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, wishlist_settings_profileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWishlist_settings_profileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the wishlist_settings_profile model
 */
readonly fields: wishlist_settings_profileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for wishlist_settings_profile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__wishlist_settings_profileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  assignments<T extends Prisma.wishlist_settings_profile$assignmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.wishlist_settings_profile$assignmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$store_settingsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the wishlist_settings_profile model
 */
export interface wishlist_settings_profileFieldRefs {
  readonly id: Prisma.FieldRef<"wishlist_settings_profile", 'String'>
  readonly fingerprint: Prisma.FieldRef<"wishlist_settings_profile", 'String'>
  readonly settings: Prisma.FieldRef<"wishlist_settings_profile", 'Json'>
  readonly createdAt: Prisma.FieldRef<"wishlist_settings_profile", 'DateTime'>
}
    

// Custom InputTypes
/**
 * wishlist_settings_profile findUnique
 */
export type wishlist_settings_profileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_settings_profile
   */
  select?: Prisma.wishlist_settings_profileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_settings_profile
   */
  omit?: Prisma.wishlist_settings_profileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_settings_profileInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_settings_profile to fetch.
   */
  where: Prisma.wishlist_settings_profileWhereUniqueInput
}

/**
 * wishlist_settings_profile findUniqueOrThrow
 */
export type wishlist_settings_profileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_settings_profile
   */
  select?: Prisma.wishlist_settings_profileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_settings_profile
   */
  omit?: Prisma.wishlist_settings_profileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_settings_profileInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_settings_profile to fetch.
   */
  where: Prisma.wishlist_settings_profileWhereUniqueInput
}

/**
 * wishlist_settings_profile findFirst
 */
export type wishlist_settings_profileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_settings_profile
   */
  select?: Prisma.wishlist_settings_profileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_settings_profile
   */
  omit?: Prisma.wishlist_settings_profileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_settings_profileInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_settings_profile to fetch.
   */
  where?: Prisma.wishlist_settings_profileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlist_settings_profiles to fetch.
   */
  orderBy?: Prisma.wishlist_settings_profileOrderByWithRelationInput | Prisma.wishlist_settings_profileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for wishlist_settings_profiles.
   */
  cursor?: Prisma.wishlist_settings_profileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlist_settings_profiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlist_settings_profiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of wishlist_settings_profiles.
   */
  distinct?: Prisma.Wishlist_settings_profileScalarFieldEnum | Prisma.Wishlist_settings_profileScalarFieldEnum[]
}

/**
 * wishlist_settings_profile findFirstOrThrow
 */
export type wishlist_settings_profileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_settings_profile
   */
  select?: Prisma.wishlist_settings_profileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_settings_profile
   */
  omit?: Prisma.wishlist_settings_profileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_settings_profileInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_settings_profile to fetch.
   */
  where?: Prisma.wishlist_settings_profileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlist_settings_profiles to fetch.
   */
  orderBy?: Prisma.wishlist_settings_profileOrderByWithRelationInput | Prisma.wishlist_settings_profileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for wishlist_settings_profiles.
   */
  cursor?: Prisma.wishlist_settings_profileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlist_settings_profiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlist_settings_profiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of wishlist_settings_profiles.
   */
  distinct?: Prisma.Wishlist_settings_profileScalarFieldEnum | Prisma.Wishlist_settings_profileScalarFieldEnum[]
}

/**
 * wishlist_settings_profile findMany
 */
export type wishlist_settings_profileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_settings_profile
   */
  select?: Prisma.wishlist_settings_profileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_settings_profile
   */
  omit?: Prisma.wishlist_settings_profileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_settings_profileInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_settings_profiles to fetch.
   */
  where?: Prisma.wishlist_settings_profileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlist_settings_profiles to fetch.
   */
  orderBy?: Prisma.wishlist_settings_profileOrderByWithRelationInput | Prisma.wishlist_settings_profileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing wishlist_settings_profiles.
   */
  cursor?: Prisma.wishlist_settings_profileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlist_settings_profiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlist_settings_profiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of wishlist_settings_profiles.
   */
  distinct?: Prisma.Wishlist_settings_profileScalarFieldEnum | Prisma.Wishlist_settings_profileScalarFieldEnum[]
}

/**
 * wishlist_settings_profile create
 */
export type wishlist_settings_profileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_settings_profile
   */
  select?: Prisma.wishlist_settings_profileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_settings_profile
   */
  omit?: Prisma.wishlist_settings_profileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_settings_profileInclude<ExtArgs> | null
  /**
   * The data needed to create a wishlist_settings_profile.
   */
  data: Prisma.XOR<Prisma.wishlist_settings_profileCreateInput, Prisma.wishlist_settings_profileUncheckedCreateInput>
}

/**
 * wishlist_settings_profile createMany
 */
export type wishlist_settings_profileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many wishlist_settings_profiles.
   */
  data: Prisma.wishlist_settings_profileCreateManyInput | Prisma.wishlist_settings_profileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * wishlist_settings_profile createManyAndReturn
 */
export type wishlist_settings_profileCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_settings_profile
   */
  select?: Prisma.wishlist_settings_profileSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_settings_profile
   */
  omit?: Prisma.wishlist_settings_profileOmit<ExtArgs> | null
  /**
   * The data used to create many wishlist_settings_profiles.
   */
  data: Prisma.wishlist_settings_profileCreateManyInput | Prisma.wishlist_settings_profileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * wishlist_settings_profile update
 */
export type wishlist_settings_profileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_settings_profile
   */
  select?: Prisma.wishlist_settings_profileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_settings_profile
   */
  omit?: Prisma.wishlist_settings_profileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_settings_profileInclude<ExtArgs> | null
  /**
   * The data needed to update a wishlist_settings_profile.
   */
  data: Prisma.XOR<Prisma.wishlist_settings_profileUpdateInput, Prisma.wishlist_settings_profileUncheckedUpdateInput>
  /**
   * Choose, which wishlist_settings_profile to update.
   */
  where: Prisma.wishlist_settings_profileWhereUniqueInput
}

/**
 * wishlist_settings_profile updateMany
 */
export type wishlist_settings_profileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update wishlist_settings_profiles.
   */
  data: Prisma.XOR<Prisma.wishlist_settings_profileUpdateManyMutationInput, Prisma.wishlist_settings_profileUncheckedUpdateManyInput>
  /**
   * Filter which wishlist_settings_profiles to update
   */
  where?: Prisma.wishlist_settings_profileWhereInput
  /**
   * Limit how many wishlist_settings_profiles to update.
   */
  limit?: number
}

/**
 * wishlist_settings_profile updateManyAndReturn
 */
export type wishlist_settings_profileUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_settings_profile
   */
  select?: Prisma.wishlist_settings_profileSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_settings_profile
   */
  omit?: Prisma.wishlist_settings_profileOmit<ExtArgs> | null
  /**
   * The data used to update wishlist_settings_profiles.
   */
  data: Prisma.XOR<Prisma.wishlist_settings_profileUpdateManyMutationInput, Prisma.wishlist_settings_profileUncheckedUpdateManyInput>
  /**
   * Filter which wishlist_settings_profiles to update
   */
  where?: Prisma.wishlist_settings_profileWhereInput
  /**
   * Limit how many wishlist_settings_profiles to update.
   */
  limit?: number
}

/**
 * wishlist_settings_profile upsert
 */
export type wishlist_settings_profileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_settings_profile
   */
  select?: Prisma.wishlist_settings_profileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_settings_profile
   */
  omit?: Prisma.wishlist_settings_profileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_settings_profileInclude<ExtArgs> | null
  /**
   * The filter to search for the wishlist_settings_profile to update in case it exists.
   */
  where: Prisma.wishlist_settings_profileWhereUniqueInput
  /**
   * In case the wishlist_settings_profile found by the `where` argument doesn't exist, create a new wishlist_settings_profile with this data.
   */
  create: Prisma.XOR<Prisma.wishlist_settings_profileCreateInput, Prisma.wishlist_settings_profileUncheckedCreateInput>
  /**
   * In case the wishlist_settings_profile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.wishlist_settings_profileUpdateInput, Prisma.wishlist_settings_profileUncheckedUpdateInput>
}

/**
 * wishlist_settings_profile delete
 */
export type wishlist_settings_profileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_settings_profile
   */
  select?: Prisma.wishlist_settings_profileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_settings_profile
   */
  omit?: Prisma.wishlist_settings_profileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_settings_profileInclude<ExtArgs> | null
  /**
   * Filter which wishlist_settings_profile to delete.
   */
  where: Prisma.wishlist_settings_profileWhereUniqueInput
}

/**
 * wishlist_settings_profile deleteMany
 */
export type wishlist_settings_profileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which wishlist_settings_profiles to delete
   */
  where?: Prisma.wishlist_settings_profileWhereInput
  /**
   * Limit how many wishlist_settings_profiles to delete.
   */
  limit?: number
}

/**
 * wishlist_settings_profile.assignments
 */
export type wishlist_settings_profile$assignmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the store_settings
   */
  select?: Prisma.store_settingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the store_settings
   */
  omit?: Prisma.store_settingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.store_settingsInclude<ExtArgs> | null
  where?: Prisma.store_settingsWhereInput
  orderBy?: Prisma.store_settingsOrderByWithRelationInput | Prisma.store_settingsOrderByWithRelationInput[]
  cursor?: Prisma.store_settingsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Store_settingsScalarFieldEnum | Prisma.Store_settingsScalarFieldEnum[]
}

/**
 * wishlist_settings_profile without action
 */
export type wishlist_settings_profileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_settings_profile
   */
  select?: Prisma.wishlist_settings_profileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_settings_profile
   */
  omit?: Prisma.wishlist_settings_profileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_settings_profileInclude<ExtArgs> | null
}
