
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `wishlist_sync_operation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model wishlist_sync_operation
 * 
 */
export type wishlist_sync_operationModel = runtime.Types.Result.DefaultSelection<Prisma.$wishlist_sync_operationPayload>

export type AggregateWishlist_sync_operation = {
  _count: Wishlist_sync_operationCountAggregateOutputType | null
  _min: Wishlist_sync_operationMinAggregateOutputType | null
  _max: Wishlist_sync_operationMaxAggregateOutputType | null
}

export type Wishlist_sync_operationMinAggregateOutputType = {
  id: string | null
  shop: string | null
  operationId: string | null
  action: string | null
  createdAt: Date | null
  completedAt: Date | null
}

export type Wishlist_sync_operationMaxAggregateOutputType = {
  id: string | null
  shop: string | null
  operationId: string | null
  action: string | null
  createdAt: Date | null
  completedAt: Date | null
}

export type Wishlist_sync_operationCountAggregateOutputType = {
  id: number
  shop: number
  operationId: number
  action: number
  createdAt: number
  completedAt: number
  _all: number
}


export type Wishlist_sync_operationMinAggregateInputType = {
  id?: true
  shop?: true
  operationId?: true
  action?: true
  createdAt?: true
  completedAt?: true
}

export type Wishlist_sync_operationMaxAggregateInputType = {
  id?: true
  shop?: true
  operationId?: true
  action?: true
  createdAt?: true
  completedAt?: true
}

export type Wishlist_sync_operationCountAggregateInputType = {
  id?: true
  shop?: true
  operationId?: true
  action?: true
  createdAt?: true
  completedAt?: true
  _all?: true
}

export type Wishlist_sync_operationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which wishlist_sync_operation to aggregate.
   */
  where?: Prisma.wishlist_sync_operationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlist_sync_operations to fetch.
   */
  orderBy?: Prisma.wishlist_sync_operationOrderByWithRelationInput | Prisma.wishlist_sync_operationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.wishlist_sync_operationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlist_sync_operations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlist_sync_operations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned wishlist_sync_operations
  **/
  _count?: true | Wishlist_sync_operationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Wishlist_sync_operationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Wishlist_sync_operationMaxAggregateInputType
}

export type GetWishlist_sync_operationAggregateType<T extends Wishlist_sync_operationAggregateArgs> = {
      [P in keyof T & keyof AggregateWishlist_sync_operation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWishlist_sync_operation[P]>
    : Prisma.GetScalarType<T[P], AggregateWishlist_sync_operation[P]>
}




export type wishlist_sync_operationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.wishlist_sync_operationWhereInput
  orderBy?: Prisma.wishlist_sync_operationOrderByWithAggregationInput | Prisma.wishlist_sync_operationOrderByWithAggregationInput[]
  by: Prisma.Wishlist_sync_operationScalarFieldEnum[] | Prisma.Wishlist_sync_operationScalarFieldEnum
  having?: Prisma.wishlist_sync_operationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Wishlist_sync_operationCountAggregateInputType | true
  _min?: Wishlist_sync_operationMinAggregateInputType
  _max?: Wishlist_sync_operationMaxAggregateInputType
}

export type Wishlist_sync_operationGroupByOutputType = {
  id: string
  shop: string
  operationId: string
  action: string
  createdAt: Date
  completedAt: Date | null
  _count: Wishlist_sync_operationCountAggregateOutputType | null
  _min: Wishlist_sync_operationMinAggregateOutputType | null
  _max: Wishlist_sync_operationMaxAggregateOutputType | null
}

export type GetWishlist_sync_operationGroupByPayload<T extends wishlist_sync_operationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Wishlist_sync_operationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Wishlist_sync_operationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Wishlist_sync_operationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Wishlist_sync_operationGroupByOutputType[P]>
      }
    >
  >



export type wishlist_sync_operationWhereInput = {
  AND?: Prisma.wishlist_sync_operationWhereInput | Prisma.wishlist_sync_operationWhereInput[]
  OR?: Prisma.wishlist_sync_operationWhereInput[]
  NOT?: Prisma.wishlist_sync_operationWhereInput | Prisma.wishlist_sync_operationWhereInput[]
  id?: Prisma.StringFilter<"wishlist_sync_operation"> | string
  shop?: Prisma.StringFilter<"wishlist_sync_operation"> | string
  operationId?: Prisma.StringFilter<"wishlist_sync_operation"> | string
  action?: Prisma.StringFilter<"wishlist_sync_operation"> | string
  createdAt?: Prisma.DateTimeFilter<"wishlist_sync_operation"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"wishlist_sync_operation"> | Date | string | null
  store?: Prisma.XOR<Prisma.StoresScalarRelationFilter, Prisma.storesWhereInput>
}

export type wishlist_sync_operationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  shop?: Prisma.SortOrder
  operationId?: Prisma.SortOrder
  action?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  store?: Prisma.storesOrderByWithRelationInput
}

export type wishlist_sync_operationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  shop_operationId?: Prisma.wishlist_sync_operationShopOperationIdCompoundUniqueInput
  AND?: Prisma.wishlist_sync_operationWhereInput | Prisma.wishlist_sync_operationWhereInput[]
  OR?: Prisma.wishlist_sync_operationWhereInput[]
  NOT?: Prisma.wishlist_sync_operationWhereInput | Prisma.wishlist_sync_operationWhereInput[]
  shop?: Prisma.StringFilter<"wishlist_sync_operation"> | string
  operationId?: Prisma.StringFilter<"wishlist_sync_operation"> | string
  action?: Prisma.StringFilter<"wishlist_sync_operation"> | string
  createdAt?: Prisma.DateTimeFilter<"wishlist_sync_operation"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"wishlist_sync_operation"> | Date | string | null
  store?: Prisma.XOR<Prisma.StoresScalarRelationFilter, Prisma.storesWhereInput>
}, "id" | "shop_operationId">

export type wishlist_sync_operationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  shop?: Prisma.SortOrder
  operationId?: Prisma.SortOrder
  action?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.wishlist_sync_operationCountOrderByAggregateInput
  _max?: Prisma.wishlist_sync_operationMaxOrderByAggregateInput
  _min?: Prisma.wishlist_sync_operationMinOrderByAggregateInput
}

export type wishlist_sync_operationScalarWhereWithAggregatesInput = {
  AND?: Prisma.wishlist_sync_operationScalarWhereWithAggregatesInput | Prisma.wishlist_sync_operationScalarWhereWithAggregatesInput[]
  OR?: Prisma.wishlist_sync_operationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.wishlist_sync_operationScalarWhereWithAggregatesInput | Prisma.wishlist_sync_operationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"wishlist_sync_operation"> | string
  shop?: Prisma.StringWithAggregatesFilter<"wishlist_sync_operation"> | string
  operationId?: Prisma.StringWithAggregatesFilter<"wishlist_sync_operation"> | string
  action?: Prisma.StringWithAggregatesFilter<"wishlist_sync_operation"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"wishlist_sync_operation"> | Date | string
  completedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"wishlist_sync_operation"> | Date | string | null
}

export type wishlist_sync_operationCreateInput = {
  id?: string
  operationId: string
  action: string
  createdAt?: Date | string
  completedAt?: Date | string | null
  store: Prisma.storesCreateNestedOneWithoutSyncOperationsInput
}

export type wishlist_sync_operationUncheckedCreateInput = {
  id?: string
  shop: string
  operationId: string
  action: string
  createdAt?: Date | string
  completedAt?: Date | string | null
}

export type wishlist_sync_operationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  operationId?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  store?: Prisma.storesUpdateOneRequiredWithoutSyncOperationsNestedInput
}

export type wishlist_sync_operationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  operationId?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type wishlist_sync_operationCreateManyInput = {
  id?: string
  shop: string
  operationId: string
  action: string
  createdAt?: Date | string
  completedAt?: Date | string | null
}

export type wishlist_sync_operationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  operationId?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type wishlist_sync_operationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  shop?: Prisma.StringFieldUpdateOperationsInput | string
  operationId?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type Wishlist_sync_operationListRelationFilter = {
  every?: Prisma.wishlist_sync_operationWhereInput
  some?: Prisma.wishlist_sync_operationWhereInput
  none?: Prisma.wishlist_sync_operationWhereInput
}

export type wishlist_sync_operationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type wishlist_sync_operationShopOperationIdCompoundUniqueInput = {
  shop: string
  operationId: string
}

export type wishlist_sync_operationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  shop?: Prisma.SortOrder
  operationId?: Prisma.SortOrder
  action?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type wishlist_sync_operationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  shop?: Prisma.SortOrder
  operationId?: Prisma.SortOrder
  action?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type wishlist_sync_operationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  shop?: Prisma.SortOrder
  operationId?: Prisma.SortOrder
  action?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type wishlist_sync_operationCreateNestedManyWithoutStoreInput = {
  create?: Prisma.XOR<Prisma.wishlist_sync_operationCreateWithoutStoreInput, Prisma.wishlist_sync_operationUncheckedCreateWithoutStoreInput> | Prisma.wishlist_sync_operationCreateWithoutStoreInput[] | Prisma.wishlist_sync_operationUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.wishlist_sync_operationCreateOrConnectWithoutStoreInput | Prisma.wishlist_sync_operationCreateOrConnectWithoutStoreInput[]
  createMany?: Prisma.wishlist_sync_operationCreateManyStoreInputEnvelope
  connect?: Prisma.wishlist_sync_operationWhereUniqueInput | Prisma.wishlist_sync_operationWhereUniqueInput[]
}

export type wishlist_sync_operationUncheckedCreateNestedManyWithoutStoreInput = {
  create?: Prisma.XOR<Prisma.wishlist_sync_operationCreateWithoutStoreInput, Prisma.wishlist_sync_operationUncheckedCreateWithoutStoreInput> | Prisma.wishlist_sync_operationCreateWithoutStoreInput[] | Prisma.wishlist_sync_operationUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.wishlist_sync_operationCreateOrConnectWithoutStoreInput | Prisma.wishlist_sync_operationCreateOrConnectWithoutStoreInput[]
  createMany?: Prisma.wishlist_sync_operationCreateManyStoreInputEnvelope
  connect?: Prisma.wishlist_sync_operationWhereUniqueInput | Prisma.wishlist_sync_operationWhereUniqueInput[]
}

export type wishlist_sync_operationUpdateManyWithoutStoreNestedInput = {
  create?: Prisma.XOR<Prisma.wishlist_sync_operationCreateWithoutStoreInput, Prisma.wishlist_sync_operationUncheckedCreateWithoutStoreInput> | Prisma.wishlist_sync_operationCreateWithoutStoreInput[] | Prisma.wishlist_sync_operationUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.wishlist_sync_operationCreateOrConnectWithoutStoreInput | Prisma.wishlist_sync_operationCreateOrConnectWithoutStoreInput[]
  upsert?: Prisma.wishlist_sync_operationUpsertWithWhereUniqueWithoutStoreInput | Prisma.wishlist_sync_operationUpsertWithWhereUniqueWithoutStoreInput[]
  createMany?: Prisma.wishlist_sync_operationCreateManyStoreInputEnvelope
  set?: Prisma.wishlist_sync_operationWhereUniqueInput | Prisma.wishlist_sync_operationWhereUniqueInput[]
  disconnect?: Prisma.wishlist_sync_operationWhereUniqueInput | Prisma.wishlist_sync_operationWhereUniqueInput[]
  delete?: Prisma.wishlist_sync_operationWhereUniqueInput | Prisma.wishlist_sync_operationWhereUniqueInput[]
  connect?: Prisma.wishlist_sync_operationWhereUniqueInput | Prisma.wishlist_sync_operationWhereUniqueInput[]
  update?: Prisma.wishlist_sync_operationUpdateWithWhereUniqueWithoutStoreInput | Prisma.wishlist_sync_operationUpdateWithWhereUniqueWithoutStoreInput[]
  updateMany?: Prisma.wishlist_sync_operationUpdateManyWithWhereWithoutStoreInput | Prisma.wishlist_sync_operationUpdateManyWithWhereWithoutStoreInput[]
  deleteMany?: Prisma.wishlist_sync_operationScalarWhereInput | Prisma.wishlist_sync_operationScalarWhereInput[]
}

export type wishlist_sync_operationUncheckedUpdateManyWithoutStoreNestedInput = {
  create?: Prisma.XOR<Prisma.wishlist_sync_operationCreateWithoutStoreInput, Prisma.wishlist_sync_operationUncheckedCreateWithoutStoreInput> | Prisma.wishlist_sync_operationCreateWithoutStoreInput[] | Prisma.wishlist_sync_operationUncheckedCreateWithoutStoreInput[]
  connectOrCreate?: Prisma.wishlist_sync_operationCreateOrConnectWithoutStoreInput | Prisma.wishlist_sync_operationCreateOrConnectWithoutStoreInput[]
  upsert?: Prisma.wishlist_sync_operationUpsertWithWhereUniqueWithoutStoreInput | Prisma.wishlist_sync_operationUpsertWithWhereUniqueWithoutStoreInput[]
  createMany?: Prisma.wishlist_sync_operationCreateManyStoreInputEnvelope
  set?: Prisma.wishlist_sync_operationWhereUniqueInput | Prisma.wishlist_sync_operationWhereUniqueInput[]
  disconnect?: Prisma.wishlist_sync_operationWhereUniqueInput | Prisma.wishlist_sync_operationWhereUniqueInput[]
  delete?: Prisma.wishlist_sync_operationWhereUniqueInput | Prisma.wishlist_sync_operationWhereUniqueInput[]
  connect?: Prisma.wishlist_sync_operationWhereUniqueInput | Prisma.wishlist_sync_operationWhereUniqueInput[]
  update?: Prisma.wishlist_sync_operationUpdateWithWhereUniqueWithoutStoreInput | Prisma.wishlist_sync_operationUpdateWithWhereUniqueWithoutStoreInput[]
  updateMany?: Prisma.wishlist_sync_operationUpdateManyWithWhereWithoutStoreInput | Prisma.wishlist_sync_operationUpdateManyWithWhereWithoutStoreInput[]
  deleteMany?: Prisma.wishlist_sync_operationScalarWhereInput | Prisma.wishlist_sync_operationScalarWhereInput[]
}

export type wishlist_sync_operationCreateWithoutStoreInput = {
  id?: string
  operationId: string
  action: string
  createdAt?: Date | string
  completedAt?: Date | string | null
}

export type wishlist_sync_operationUncheckedCreateWithoutStoreInput = {
  id?: string
  operationId: string
  action: string
  createdAt?: Date | string
  completedAt?: Date | string | null
}

export type wishlist_sync_operationCreateOrConnectWithoutStoreInput = {
  where: Prisma.wishlist_sync_operationWhereUniqueInput
  create: Prisma.XOR<Prisma.wishlist_sync_operationCreateWithoutStoreInput, Prisma.wishlist_sync_operationUncheckedCreateWithoutStoreInput>
}

export type wishlist_sync_operationCreateManyStoreInputEnvelope = {
  data: Prisma.wishlist_sync_operationCreateManyStoreInput | Prisma.wishlist_sync_operationCreateManyStoreInput[]
  skipDuplicates?: boolean
}

export type wishlist_sync_operationUpsertWithWhereUniqueWithoutStoreInput = {
  where: Prisma.wishlist_sync_operationWhereUniqueInput
  update: Prisma.XOR<Prisma.wishlist_sync_operationUpdateWithoutStoreInput, Prisma.wishlist_sync_operationUncheckedUpdateWithoutStoreInput>
  create: Prisma.XOR<Prisma.wishlist_sync_operationCreateWithoutStoreInput, Prisma.wishlist_sync_operationUncheckedCreateWithoutStoreInput>
}

export type wishlist_sync_operationUpdateWithWhereUniqueWithoutStoreInput = {
  where: Prisma.wishlist_sync_operationWhereUniqueInput
  data: Prisma.XOR<Prisma.wishlist_sync_operationUpdateWithoutStoreInput, Prisma.wishlist_sync_operationUncheckedUpdateWithoutStoreInput>
}

export type wishlist_sync_operationUpdateManyWithWhereWithoutStoreInput = {
  where: Prisma.wishlist_sync_operationScalarWhereInput
  data: Prisma.XOR<Prisma.wishlist_sync_operationUpdateManyMutationInput, Prisma.wishlist_sync_operationUncheckedUpdateManyWithoutStoreInput>
}

export type wishlist_sync_operationScalarWhereInput = {
  AND?: Prisma.wishlist_sync_operationScalarWhereInput | Prisma.wishlist_sync_operationScalarWhereInput[]
  OR?: Prisma.wishlist_sync_operationScalarWhereInput[]
  NOT?: Prisma.wishlist_sync_operationScalarWhereInput | Prisma.wishlist_sync_operationScalarWhereInput[]
  id?: Prisma.StringFilter<"wishlist_sync_operation"> | string
  shop?: Prisma.StringFilter<"wishlist_sync_operation"> | string
  operationId?: Prisma.StringFilter<"wishlist_sync_operation"> | string
  action?: Prisma.StringFilter<"wishlist_sync_operation"> | string
  createdAt?: Prisma.DateTimeFilter<"wishlist_sync_operation"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"wishlist_sync_operation"> | Date | string | null
}

export type wishlist_sync_operationCreateManyStoreInput = {
  id?: string
  operationId: string
  action: string
  createdAt?: Date | string
  completedAt?: Date | string | null
}

export type wishlist_sync_operationUpdateWithoutStoreInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  operationId?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type wishlist_sync_operationUncheckedUpdateWithoutStoreInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  operationId?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type wishlist_sync_operationUncheckedUpdateManyWithoutStoreInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  operationId?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type wishlist_sync_operationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  shop?: boolean
  operationId?: boolean
  action?: boolean
  createdAt?: boolean
  completedAt?: boolean
  store?: boolean | Prisma.storesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["wishlist_sync_operation"]>

export type wishlist_sync_operationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  shop?: boolean
  operationId?: boolean
  action?: boolean
  createdAt?: boolean
  completedAt?: boolean
  store?: boolean | Prisma.storesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["wishlist_sync_operation"]>

export type wishlist_sync_operationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  shop?: boolean
  operationId?: boolean
  action?: boolean
  createdAt?: boolean
  completedAt?: boolean
  store?: boolean | Prisma.storesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["wishlist_sync_operation"]>

export type wishlist_sync_operationSelectScalar = {
  id?: boolean
  shop?: boolean
  operationId?: boolean
  action?: boolean
  createdAt?: boolean
  completedAt?: boolean
}

export type wishlist_sync_operationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "shop" | "operationId" | "action" | "createdAt" | "completedAt", ExtArgs["result"]["wishlist_sync_operation"]>
export type wishlist_sync_operationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  store?: boolean | Prisma.storesDefaultArgs<ExtArgs>
}
export type wishlist_sync_operationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  store?: boolean | Prisma.storesDefaultArgs<ExtArgs>
}
export type wishlist_sync_operationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  store?: boolean | Prisma.storesDefaultArgs<ExtArgs>
}

export type $wishlist_sync_operationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "wishlist_sync_operation"
  objects: {
    store: Prisma.$storesPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    shop: string
    operationId: string
    action: string
    createdAt: Date
    completedAt: Date | null
  }, ExtArgs["result"]["wishlist_sync_operation"]>
  composites: {}
}

export type wishlist_sync_operationGetPayload<S extends boolean | null | undefined | wishlist_sync_operationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$wishlist_sync_operationPayload, S>

export type wishlist_sync_operationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<wishlist_sync_operationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Wishlist_sync_operationCountAggregateInputType | true
  }

export interface wishlist_sync_operationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['wishlist_sync_operation'], meta: { name: 'wishlist_sync_operation' } }
  /**
   * Find zero or one Wishlist_sync_operation that matches the filter.
   * @param {wishlist_sync_operationFindUniqueArgs} args - Arguments to find a Wishlist_sync_operation
   * @example
   * // Get one Wishlist_sync_operation
   * const wishlist_sync_operation = await prisma.wishlist_sync_operation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends wishlist_sync_operationFindUniqueArgs>(args: Prisma.SelectSubset<T, wishlist_sync_operationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__wishlist_sync_operationClient<runtime.Types.Result.GetResult<Prisma.$wishlist_sync_operationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Wishlist_sync_operation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {wishlist_sync_operationFindUniqueOrThrowArgs} args - Arguments to find a Wishlist_sync_operation
   * @example
   * // Get one Wishlist_sync_operation
   * const wishlist_sync_operation = await prisma.wishlist_sync_operation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends wishlist_sync_operationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, wishlist_sync_operationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__wishlist_sync_operationClient<runtime.Types.Result.GetResult<Prisma.$wishlist_sync_operationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Wishlist_sync_operation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_sync_operationFindFirstArgs} args - Arguments to find a Wishlist_sync_operation
   * @example
   * // Get one Wishlist_sync_operation
   * const wishlist_sync_operation = await prisma.wishlist_sync_operation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends wishlist_sync_operationFindFirstArgs>(args?: Prisma.SelectSubset<T, wishlist_sync_operationFindFirstArgs<ExtArgs>>): Prisma.Prisma__wishlist_sync_operationClient<runtime.Types.Result.GetResult<Prisma.$wishlist_sync_operationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Wishlist_sync_operation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_sync_operationFindFirstOrThrowArgs} args - Arguments to find a Wishlist_sync_operation
   * @example
   * // Get one Wishlist_sync_operation
   * const wishlist_sync_operation = await prisma.wishlist_sync_operation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends wishlist_sync_operationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, wishlist_sync_operationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__wishlist_sync_operationClient<runtime.Types.Result.GetResult<Prisma.$wishlist_sync_operationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Wishlist_sync_operations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_sync_operationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Wishlist_sync_operations
   * const wishlist_sync_operations = await prisma.wishlist_sync_operation.findMany()
   * 
   * // Get first 10 Wishlist_sync_operations
   * const wishlist_sync_operations = await prisma.wishlist_sync_operation.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const wishlist_sync_operationWithIdOnly = await prisma.wishlist_sync_operation.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends wishlist_sync_operationFindManyArgs>(args?: Prisma.SelectSubset<T, wishlist_sync_operationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlist_sync_operationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Wishlist_sync_operation.
   * @param {wishlist_sync_operationCreateArgs} args - Arguments to create a Wishlist_sync_operation.
   * @example
   * // Create one Wishlist_sync_operation
   * const Wishlist_sync_operation = await prisma.wishlist_sync_operation.create({
   *   data: {
   *     // ... data to create a Wishlist_sync_operation
   *   }
   * })
   * 
   */
  create<T extends wishlist_sync_operationCreateArgs>(args: Prisma.SelectSubset<T, wishlist_sync_operationCreateArgs<ExtArgs>>): Prisma.Prisma__wishlist_sync_operationClient<runtime.Types.Result.GetResult<Prisma.$wishlist_sync_operationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Wishlist_sync_operations.
   * @param {wishlist_sync_operationCreateManyArgs} args - Arguments to create many Wishlist_sync_operations.
   * @example
   * // Create many Wishlist_sync_operations
   * const wishlist_sync_operation = await prisma.wishlist_sync_operation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends wishlist_sync_operationCreateManyArgs>(args?: Prisma.SelectSubset<T, wishlist_sync_operationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Wishlist_sync_operations and returns the data saved in the database.
   * @param {wishlist_sync_operationCreateManyAndReturnArgs} args - Arguments to create many Wishlist_sync_operations.
   * @example
   * // Create many Wishlist_sync_operations
   * const wishlist_sync_operation = await prisma.wishlist_sync_operation.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Wishlist_sync_operations and only return the `id`
   * const wishlist_sync_operationWithIdOnly = await prisma.wishlist_sync_operation.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends wishlist_sync_operationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, wishlist_sync_operationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlist_sync_operationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Wishlist_sync_operation.
   * @param {wishlist_sync_operationDeleteArgs} args - Arguments to delete one Wishlist_sync_operation.
   * @example
   * // Delete one Wishlist_sync_operation
   * const Wishlist_sync_operation = await prisma.wishlist_sync_operation.delete({
   *   where: {
   *     // ... filter to delete one Wishlist_sync_operation
   *   }
   * })
   * 
   */
  delete<T extends wishlist_sync_operationDeleteArgs>(args: Prisma.SelectSubset<T, wishlist_sync_operationDeleteArgs<ExtArgs>>): Prisma.Prisma__wishlist_sync_operationClient<runtime.Types.Result.GetResult<Prisma.$wishlist_sync_operationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Wishlist_sync_operation.
   * @param {wishlist_sync_operationUpdateArgs} args - Arguments to update one Wishlist_sync_operation.
   * @example
   * // Update one Wishlist_sync_operation
   * const wishlist_sync_operation = await prisma.wishlist_sync_operation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends wishlist_sync_operationUpdateArgs>(args: Prisma.SelectSubset<T, wishlist_sync_operationUpdateArgs<ExtArgs>>): Prisma.Prisma__wishlist_sync_operationClient<runtime.Types.Result.GetResult<Prisma.$wishlist_sync_operationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Wishlist_sync_operations.
   * @param {wishlist_sync_operationDeleteManyArgs} args - Arguments to filter Wishlist_sync_operations to delete.
   * @example
   * // Delete a few Wishlist_sync_operations
   * const { count } = await prisma.wishlist_sync_operation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends wishlist_sync_operationDeleteManyArgs>(args?: Prisma.SelectSubset<T, wishlist_sync_operationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Wishlist_sync_operations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_sync_operationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Wishlist_sync_operations
   * const wishlist_sync_operation = await prisma.wishlist_sync_operation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends wishlist_sync_operationUpdateManyArgs>(args: Prisma.SelectSubset<T, wishlist_sync_operationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Wishlist_sync_operations and returns the data updated in the database.
   * @param {wishlist_sync_operationUpdateManyAndReturnArgs} args - Arguments to update many Wishlist_sync_operations.
   * @example
   * // Update many Wishlist_sync_operations
   * const wishlist_sync_operation = await prisma.wishlist_sync_operation.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Wishlist_sync_operations and only return the `id`
   * const wishlist_sync_operationWithIdOnly = await prisma.wishlist_sync_operation.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends wishlist_sync_operationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, wishlist_sync_operationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlist_sync_operationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Wishlist_sync_operation.
   * @param {wishlist_sync_operationUpsertArgs} args - Arguments to update or create a Wishlist_sync_operation.
   * @example
   * // Update or create a Wishlist_sync_operation
   * const wishlist_sync_operation = await prisma.wishlist_sync_operation.upsert({
   *   create: {
   *     // ... data to create a Wishlist_sync_operation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Wishlist_sync_operation we want to update
   *   }
   * })
   */
  upsert<T extends wishlist_sync_operationUpsertArgs>(args: Prisma.SelectSubset<T, wishlist_sync_operationUpsertArgs<ExtArgs>>): Prisma.Prisma__wishlist_sync_operationClient<runtime.Types.Result.GetResult<Prisma.$wishlist_sync_operationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Wishlist_sync_operations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_sync_operationCountArgs} args - Arguments to filter Wishlist_sync_operations to count.
   * @example
   * // Count the number of Wishlist_sync_operations
   * const count = await prisma.wishlist_sync_operation.count({
   *   where: {
   *     // ... the filter for the Wishlist_sync_operations we want to count
   *   }
   * })
  **/
  count<T extends wishlist_sync_operationCountArgs>(
    args?: Prisma.Subset<T, wishlist_sync_operationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Wishlist_sync_operationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Wishlist_sync_operation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Wishlist_sync_operationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Wishlist_sync_operationAggregateArgs>(args: Prisma.Subset<T, Wishlist_sync_operationAggregateArgs>): Prisma.PrismaPromise<GetWishlist_sync_operationAggregateType<T>>

  /**
   * Group by Wishlist_sync_operation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_sync_operationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends wishlist_sync_operationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: wishlist_sync_operationGroupByArgs['orderBy'] }
      : { orderBy?: wishlist_sync_operationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, wishlist_sync_operationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWishlist_sync_operationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the wishlist_sync_operation model
 */
readonly fields: wishlist_sync_operationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for wishlist_sync_operation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__wishlist_sync_operationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  store<T extends Prisma.storesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.storesDefaultArgs<ExtArgs>>): Prisma.Prisma__storesClient<runtime.Types.Result.GetResult<Prisma.$storesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the wishlist_sync_operation model
 */
export interface wishlist_sync_operationFieldRefs {
  readonly id: Prisma.FieldRef<"wishlist_sync_operation", 'String'>
  readonly shop: Prisma.FieldRef<"wishlist_sync_operation", 'String'>
  readonly operationId: Prisma.FieldRef<"wishlist_sync_operation", 'String'>
  readonly action: Prisma.FieldRef<"wishlist_sync_operation", 'String'>
  readonly createdAt: Prisma.FieldRef<"wishlist_sync_operation", 'DateTime'>
  readonly completedAt: Prisma.FieldRef<"wishlist_sync_operation", 'DateTime'>
}
    

// Custom InputTypes
/**
 * wishlist_sync_operation findUnique
 */
export type wishlist_sync_operationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_sync_operation
   */
  select?: Prisma.wishlist_sync_operationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_sync_operation
   */
  omit?: Prisma.wishlist_sync_operationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_sync_operationInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_sync_operation to fetch.
   */
  where: Prisma.wishlist_sync_operationWhereUniqueInput
}

/**
 * wishlist_sync_operation findUniqueOrThrow
 */
export type wishlist_sync_operationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_sync_operation
   */
  select?: Prisma.wishlist_sync_operationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_sync_operation
   */
  omit?: Prisma.wishlist_sync_operationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_sync_operationInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_sync_operation to fetch.
   */
  where: Prisma.wishlist_sync_operationWhereUniqueInput
}

/**
 * wishlist_sync_operation findFirst
 */
export type wishlist_sync_operationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_sync_operation
   */
  select?: Prisma.wishlist_sync_operationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_sync_operation
   */
  omit?: Prisma.wishlist_sync_operationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_sync_operationInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_sync_operation to fetch.
   */
  where?: Prisma.wishlist_sync_operationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlist_sync_operations to fetch.
   */
  orderBy?: Prisma.wishlist_sync_operationOrderByWithRelationInput | Prisma.wishlist_sync_operationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for wishlist_sync_operations.
   */
  cursor?: Prisma.wishlist_sync_operationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlist_sync_operations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlist_sync_operations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of wishlist_sync_operations.
   */
  distinct?: Prisma.Wishlist_sync_operationScalarFieldEnum | Prisma.Wishlist_sync_operationScalarFieldEnum[]
}

/**
 * wishlist_sync_operation findFirstOrThrow
 */
export type wishlist_sync_operationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_sync_operation
   */
  select?: Prisma.wishlist_sync_operationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_sync_operation
   */
  omit?: Prisma.wishlist_sync_operationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_sync_operationInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_sync_operation to fetch.
   */
  where?: Prisma.wishlist_sync_operationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlist_sync_operations to fetch.
   */
  orderBy?: Prisma.wishlist_sync_operationOrderByWithRelationInput | Prisma.wishlist_sync_operationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for wishlist_sync_operations.
   */
  cursor?: Prisma.wishlist_sync_operationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlist_sync_operations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlist_sync_operations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of wishlist_sync_operations.
   */
  distinct?: Prisma.Wishlist_sync_operationScalarFieldEnum | Prisma.Wishlist_sync_operationScalarFieldEnum[]
}

/**
 * wishlist_sync_operation findMany
 */
export type wishlist_sync_operationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_sync_operation
   */
  select?: Prisma.wishlist_sync_operationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_sync_operation
   */
  omit?: Prisma.wishlist_sync_operationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_sync_operationInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_sync_operations to fetch.
   */
  where?: Prisma.wishlist_sync_operationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlist_sync_operations to fetch.
   */
  orderBy?: Prisma.wishlist_sync_operationOrderByWithRelationInput | Prisma.wishlist_sync_operationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing wishlist_sync_operations.
   */
  cursor?: Prisma.wishlist_sync_operationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlist_sync_operations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlist_sync_operations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of wishlist_sync_operations.
   */
  distinct?: Prisma.Wishlist_sync_operationScalarFieldEnum | Prisma.Wishlist_sync_operationScalarFieldEnum[]
}

/**
 * wishlist_sync_operation create
 */
export type wishlist_sync_operationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_sync_operation
   */
  select?: Prisma.wishlist_sync_operationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_sync_operation
   */
  omit?: Prisma.wishlist_sync_operationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_sync_operationInclude<ExtArgs> | null
  /**
   * The data needed to create a wishlist_sync_operation.
   */
  data: Prisma.XOR<Prisma.wishlist_sync_operationCreateInput, Prisma.wishlist_sync_operationUncheckedCreateInput>
}

/**
 * wishlist_sync_operation createMany
 */
export type wishlist_sync_operationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many wishlist_sync_operations.
   */
  data: Prisma.wishlist_sync_operationCreateManyInput | Prisma.wishlist_sync_operationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * wishlist_sync_operation createManyAndReturn
 */
export type wishlist_sync_operationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_sync_operation
   */
  select?: Prisma.wishlist_sync_operationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_sync_operation
   */
  omit?: Prisma.wishlist_sync_operationOmit<ExtArgs> | null
  /**
   * The data used to create many wishlist_sync_operations.
   */
  data: Prisma.wishlist_sync_operationCreateManyInput | Prisma.wishlist_sync_operationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_sync_operationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * wishlist_sync_operation update
 */
export type wishlist_sync_operationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_sync_operation
   */
  select?: Prisma.wishlist_sync_operationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_sync_operation
   */
  omit?: Prisma.wishlist_sync_operationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_sync_operationInclude<ExtArgs> | null
  /**
   * The data needed to update a wishlist_sync_operation.
   */
  data: Prisma.XOR<Prisma.wishlist_sync_operationUpdateInput, Prisma.wishlist_sync_operationUncheckedUpdateInput>
  /**
   * Choose, which wishlist_sync_operation to update.
   */
  where: Prisma.wishlist_sync_operationWhereUniqueInput
}

/**
 * wishlist_sync_operation updateMany
 */
export type wishlist_sync_operationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update wishlist_sync_operations.
   */
  data: Prisma.XOR<Prisma.wishlist_sync_operationUpdateManyMutationInput, Prisma.wishlist_sync_operationUncheckedUpdateManyInput>
  /**
   * Filter which wishlist_sync_operations to update
   */
  where?: Prisma.wishlist_sync_operationWhereInput
  /**
   * Limit how many wishlist_sync_operations to update.
   */
  limit?: number
}

/**
 * wishlist_sync_operation updateManyAndReturn
 */
export type wishlist_sync_operationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_sync_operation
   */
  select?: Prisma.wishlist_sync_operationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_sync_operation
   */
  omit?: Prisma.wishlist_sync_operationOmit<ExtArgs> | null
  /**
   * The data used to update wishlist_sync_operations.
   */
  data: Prisma.XOR<Prisma.wishlist_sync_operationUpdateManyMutationInput, Prisma.wishlist_sync_operationUncheckedUpdateManyInput>
  /**
   * Filter which wishlist_sync_operations to update
   */
  where?: Prisma.wishlist_sync_operationWhereInput
  /**
   * Limit how many wishlist_sync_operations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_sync_operationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * wishlist_sync_operation upsert
 */
export type wishlist_sync_operationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_sync_operation
   */
  select?: Prisma.wishlist_sync_operationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_sync_operation
   */
  omit?: Prisma.wishlist_sync_operationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_sync_operationInclude<ExtArgs> | null
  /**
   * The filter to search for the wishlist_sync_operation to update in case it exists.
   */
  where: Prisma.wishlist_sync_operationWhereUniqueInput
  /**
   * In case the wishlist_sync_operation found by the `where` argument doesn't exist, create a new wishlist_sync_operation with this data.
   */
  create: Prisma.XOR<Prisma.wishlist_sync_operationCreateInput, Prisma.wishlist_sync_operationUncheckedCreateInput>
  /**
   * In case the wishlist_sync_operation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.wishlist_sync_operationUpdateInput, Prisma.wishlist_sync_operationUncheckedUpdateInput>
}

/**
 * wishlist_sync_operation delete
 */
export type wishlist_sync_operationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_sync_operation
   */
  select?: Prisma.wishlist_sync_operationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_sync_operation
   */
  omit?: Prisma.wishlist_sync_operationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_sync_operationInclude<ExtArgs> | null
  /**
   * Filter which wishlist_sync_operation to delete.
   */
  where: Prisma.wishlist_sync_operationWhereUniqueInput
}

/**
 * wishlist_sync_operation deleteMany
 */
export type wishlist_sync_operationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which wishlist_sync_operations to delete
   */
  where?: Prisma.wishlist_sync_operationWhereInput
  /**
   * Limit how many wishlist_sync_operations to delete.
   */
  limit?: number
}

/**
 * wishlist_sync_operation without action
 */
export type wishlist_sync_operationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_sync_operation
   */
  select?: Prisma.wishlist_sync_operationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_sync_operation
   */
  omit?: Prisma.wishlist_sync_operationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_sync_operationInclude<ExtArgs> | null
}
