
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  stores: 'stores',
  session: 'session',
  store_settings: 'store_settings',
  wishlist: 'wishlist',
  wishlist_item: 'wishlist_item',
  wishlist_event: 'wishlist_event',
  wishlist_sync_operation: 'wishlist_sync_operation',
  wishlist_settings_profile: 'wishlist_settings_profile'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const StoresScalarFieldEnum = {
  shop: 'shop',
  isActive: 'isActive',
  installedAt: 'installedAt',
  updatedAt: 'updatedAt'
} as const

export type StoresScalarFieldEnum = (typeof StoresScalarFieldEnum)[keyof typeof StoresScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  content: 'content',
  shop: 'shop'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const Store_settingsScalarFieldEnum = {
  id: 'id',
  shop: 'shop',
  iconEnabled: 'iconEnabled',
  showOnCollectionPages: 'showOnCollectionPages',
  showOnHomePage: 'showOnHomePage',
  showOnProductImage: 'showOnProductImage',
  autoInjectHeaderIcon: 'autoInjectHeaderIcon',
  heartColor: 'heartColor',
  iconPositionX: 'iconPositionX',
  iconPositionY: 'iconPositionY',
  pageTitle: 'pageTitle',
  emptyStateTitle: 'emptyStateTitle',
  emptyStateBody: 'emptyStateBody',
  floatingButtonEnabled: 'floatingButtonEnabled',
  floatingButtonText: 'floatingButtonText',
  floatingButtonPosition: 'floatingButtonPosition',
  addButtonEnabled: 'addButtonEnabled',
  addButtonText: 'addButtonText',
  removeButtonText: 'removeButtonText',
  showPrices: 'showPrices',
  showAddToCart: 'showAddToCart',
  requireLogin: 'requireLogin',
  onlyInStock: 'onlyInStock',
  excludedTags: 'excludedTags',
  customCss: 'customCss',
  setupEmbedConfirmed: 'setupEmbedConfirmed',
  customizedAt: 'customizedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  settingsProfileId: 'settingsProfileId'
} as const

export type Store_settingsScalarFieldEnum = (typeof Store_settingsScalarFieldEnum)[keyof typeof Store_settingsScalarFieldEnum]


export const WishlistScalarFieldEnum = {
  id: 'id',
  shop: 'shop',
  key: 'key',
  customerId: 'customerId',
  visitorId: 'visitorId',
  email: 'email',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WishlistScalarFieldEnum = (typeof WishlistScalarFieldEnum)[keyof typeof WishlistScalarFieldEnum]


export const Wishlist_itemScalarFieldEnum = {
  id: 'id',
  wishlistId: 'wishlistId',
  productId: 'productId',
  variantId: 'variantId',
  productHandle: 'productHandle',
  title: 'title',
  variantTitle: 'variantTitle',
  productUrl: 'productUrl',
  imageUrl: 'imageUrl',
  imageAlt: 'imageAlt',
  price: 'price',
  currency: 'currency',
  available: 'available',
  addedAt: 'addedAt',
  updatedAt: 'updatedAt'
} as const

export type Wishlist_itemScalarFieldEnum = (typeof Wishlist_itemScalarFieldEnum)[keyof typeof Wishlist_itemScalarFieldEnum]


export const Wishlist_eventScalarFieldEnum = {
  id: 'id',
  shop: 'shop',
  wishlistId: 'wishlistId',
  type: 'type',
  productId: 'productId',
  variantId: 'variantId',
  value: 'value',
  createdAt: 'createdAt'
} as const

export type Wishlist_eventScalarFieldEnum = (typeof Wishlist_eventScalarFieldEnum)[keyof typeof Wishlist_eventScalarFieldEnum]


export const Wishlist_sync_operationScalarFieldEnum = {
  id: 'id',
  shop: 'shop',
  operationId: 'operationId',
  action: 'action',
  createdAt: 'createdAt',
  completedAt: 'completedAt'
} as const

export type Wishlist_sync_operationScalarFieldEnum = (typeof Wishlist_sync_operationScalarFieldEnum)[keyof typeof Wishlist_sync_operationScalarFieldEnum]


export const Wishlist_settings_profileScalarFieldEnum = {
  id: 'id',
  fingerprint: 'fingerprint',
  settings: 'settings',
  createdAt: 'createdAt'
} as const

export type Wishlist_settings_profileScalarFieldEnum = (typeof Wishlist_settings_profileScalarFieldEnum)[keyof typeof Wishlist_settings_profileScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

