
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models.ts"
import { type PrismaClient } from "./class.ts"

export type * from '../models.ts'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
export const prismaVersion: PrismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  stores: 'stores',
  session: 'session',
  store_settings: 'store_settings',
  wishlist: 'wishlist',
  wishlist_item: 'wishlist_item',
  wishlist_event: 'wishlist_event',
  wishlist_sync_operation: 'wishlist_sync_operation',
  wishlist_settings_profile: 'wishlist_settings_profile'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "stores" | "session" | "store_settings" | "wishlist" | "wishlist_item" | "wishlist_event" | "wishlist_sync_operation" | "wishlist_settings_profile"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    stores: {
      payload: Prisma.$storesPayload<ExtArgs>
      fields: Prisma.storesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.storesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$storesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.storesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$storesPayload>
        }
        findFirst: {
          args: Prisma.storesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$storesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.storesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$storesPayload>
        }
        findMany: {
          args: Prisma.storesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$storesPayload>[]
        }
        create: {
          args: Prisma.storesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$storesPayload>
        }
        createMany: {
          args: Prisma.storesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.storesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$storesPayload>[]
        }
        delete: {
          args: Prisma.storesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$storesPayload>
        }
        update: {
          args: Prisma.storesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$storesPayload>
        }
        deleteMany: {
          args: Prisma.storesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.storesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.storesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$storesPayload>[]
        }
        upsert: {
          args: Prisma.storesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$storesPayload>
        }
        aggregate: {
          args: Prisma.StoresAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateStores>
        }
        groupBy: {
          args: Prisma.storesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StoresGroupByOutputType>[]
        }
        count: {
          args: Prisma.storesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StoresCountAggregateOutputType> | number
        }
      }
    }
    session: {
      payload: Prisma.$sessionPayload<ExtArgs>
      fields: Prisma.sessionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.sessionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$sessionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.sessionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$sessionPayload>
        }
        findFirst: {
          args: Prisma.sessionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$sessionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.sessionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$sessionPayload>
        }
        findMany: {
          args: Prisma.sessionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$sessionPayload>[]
        }
        create: {
          args: Prisma.sessionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$sessionPayload>
        }
        createMany: {
          args: Prisma.sessionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.sessionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$sessionPayload>[]
        }
        delete: {
          args: Prisma.sessionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$sessionPayload>
        }
        update: {
          args: Prisma.sessionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$sessionPayload>
        }
        deleteMany: {
          args: Prisma.sessionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.sessionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.sessionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$sessionPayload>[]
        }
        upsert: {
          args: Prisma.sessionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$sessionPayload>
        }
        aggregate: {
          args: Prisma.SessionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSession>
        }
        groupBy: {
          args: Prisma.sessionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SessionGroupByOutputType>[]
        }
        count: {
          args: Prisma.sessionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SessionCountAggregateOutputType> | number
        }
      }
    }
    store_settings: {
      payload: Prisma.$store_settingsPayload<ExtArgs>
      fields: Prisma.store_settingsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.store_settingsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$store_settingsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.store_settingsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$store_settingsPayload>
        }
        findFirst: {
          args: Prisma.store_settingsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$store_settingsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.store_settingsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$store_settingsPayload>
        }
        findMany: {
          args: Prisma.store_settingsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$store_settingsPayload>[]
        }
        create: {
          args: Prisma.store_settingsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$store_settingsPayload>
        }
        createMany: {
          args: Prisma.store_settingsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.store_settingsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$store_settingsPayload>[]
        }
        delete: {
          args: Prisma.store_settingsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$store_settingsPayload>
        }
        update: {
          args: Prisma.store_settingsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$store_settingsPayload>
        }
        deleteMany: {
          args: Prisma.store_settingsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.store_settingsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.store_settingsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$store_settingsPayload>[]
        }
        upsert: {
          args: Prisma.store_settingsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$store_settingsPayload>
        }
        aggregate: {
          args: Prisma.Store_settingsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateStore_settings>
        }
        groupBy: {
          args: Prisma.store_settingsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Store_settingsGroupByOutputType>[]
        }
        count: {
          args: Prisma.store_settingsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Store_settingsCountAggregateOutputType> | number
        }
      }
    }
    wishlist: {
      payload: Prisma.$wishlistPayload<ExtArgs>
      fields: Prisma.wishlistFieldRefs
      operations: {
        findUnique: {
          args: Prisma.wishlistFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlistPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.wishlistFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlistPayload>
        }
        findFirst: {
          args: Prisma.wishlistFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlistPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.wishlistFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlistPayload>
        }
        findMany: {
          args: Prisma.wishlistFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlistPayload>[]
        }
        create: {
          args: Prisma.wishlistCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlistPayload>
        }
        createMany: {
          args: Prisma.wishlistCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.wishlistCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlistPayload>[]
        }
        delete: {
          args: Prisma.wishlistDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlistPayload>
        }
        update: {
          args: Prisma.wishlistUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlistPayload>
        }
        deleteMany: {
          args: Prisma.wishlistDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.wishlistUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.wishlistUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlistPayload>[]
        }
        upsert: {
          args: Prisma.wishlistUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlistPayload>
        }
        aggregate: {
          args: Prisma.WishlistAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateWishlist>
        }
        groupBy: {
          args: Prisma.wishlistGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WishlistGroupByOutputType>[]
        }
        count: {
          args: Prisma.wishlistCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WishlistCountAggregateOutputType> | number
        }
      }
    }
    wishlist_item: {
      payload: Prisma.$wishlist_itemPayload<ExtArgs>
      fields: Prisma.wishlist_itemFieldRefs
      operations: {
        findUnique: {
          args: Prisma.wishlist_itemFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_itemPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.wishlist_itemFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_itemPayload>
        }
        findFirst: {
          args: Prisma.wishlist_itemFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_itemPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.wishlist_itemFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_itemPayload>
        }
        findMany: {
          args: Prisma.wishlist_itemFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_itemPayload>[]
        }
        create: {
          args: Prisma.wishlist_itemCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_itemPayload>
        }
        createMany: {
          args: Prisma.wishlist_itemCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.wishlist_itemCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_itemPayload>[]
        }
        delete: {
          args: Prisma.wishlist_itemDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_itemPayload>
        }
        update: {
          args: Prisma.wishlist_itemUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_itemPayload>
        }
        deleteMany: {
          args: Prisma.wishlist_itemDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.wishlist_itemUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.wishlist_itemUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_itemPayload>[]
        }
        upsert: {
          args: Prisma.wishlist_itemUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_itemPayload>
        }
        aggregate: {
          args: Prisma.Wishlist_itemAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateWishlist_item>
        }
        groupBy: {
          args: Prisma.wishlist_itemGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Wishlist_itemGroupByOutputType>[]
        }
        count: {
          args: Prisma.wishlist_itemCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Wishlist_itemCountAggregateOutputType> | number
        }
      }
    }
    wishlist_event: {
      payload: Prisma.$wishlist_eventPayload<ExtArgs>
      fields: Prisma.wishlist_eventFieldRefs
      operations: {
        findUnique: {
          args: Prisma.wishlist_eventFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_eventPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.wishlist_eventFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_eventPayload>
        }
        findFirst: {
          args: Prisma.wishlist_eventFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_eventPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.wishlist_eventFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_eventPayload>
        }
        findMany: {
          args: Prisma.wishlist_eventFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_eventPayload>[]
        }
        create: {
          args: Prisma.wishlist_eventCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_eventPayload>
        }
        createMany: {
          args: Prisma.wishlist_eventCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.wishlist_eventCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_eventPayload>[]
        }
        delete: {
          args: Prisma.wishlist_eventDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_eventPayload>
        }
        update: {
          args: Prisma.wishlist_eventUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_eventPayload>
        }
        deleteMany: {
          args: Prisma.wishlist_eventDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.wishlist_eventUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.wishlist_eventUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_eventPayload>[]
        }
        upsert: {
          args: Prisma.wishlist_eventUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_eventPayload>
        }
        aggregate: {
          args: Prisma.Wishlist_eventAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateWishlist_event>
        }
        groupBy: {
          args: Prisma.wishlist_eventGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Wishlist_eventGroupByOutputType>[]
        }
        count: {
          args: Prisma.wishlist_eventCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Wishlist_eventCountAggregateOutputType> | number
        }
      }
    }
    wishlist_sync_operation: {
      payload: Prisma.$wishlist_sync_operationPayload<ExtArgs>
      fields: Prisma.wishlist_sync_operationFieldRefs
      operations: {
        findUnique: {
          args: Prisma.wishlist_sync_operationFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_sync_operationPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.wishlist_sync_operationFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_sync_operationPayload>
        }
        findFirst: {
          args: Prisma.wishlist_sync_operationFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_sync_operationPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.wishlist_sync_operationFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_sync_operationPayload>
        }
        findMany: {
          args: Prisma.wishlist_sync_operationFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_sync_operationPayload>[]
        }
        create: {
          args: Prisma.wishlist_sync_operationCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_sync_operationPayload>
        }
        createMany: {
          args: Prisma.wishlist_sync_operationCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.wishlist_sync_operationCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_sync_operationPayload>[]
        }
        delete: {
          args: Prisma.wishlist_sync_operationDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_sync_operationPayload>
        }
        update: {
          args: Prisma.wishlist_sync_operationUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_sync_operationPayload>
        }
        deleteMany: {
          args: Prisma.wishlist_sync_operationDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.wishlist_sync_operationUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.wishlist_sync_operationUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_sync_operationPayload>[]
        }
        upsert: {
          args: Prisma.wishlist_sync_operationUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_sync_operationPayload>
        }
        aggregate: {
          args: Prisma.Wishlist_sync_operationAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateWishlist_sync_operation>
        }
        groupBy: {
          args: Prisma.wishlist_sync_operationGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Wishlist_sync_operationGroupByOutputType>[]
        }
        count: {
          args: Prisma.wishlist_sync_operationCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Wishlist_sync_operationCountAggregateOutputType> | number
        }
      }
    }
    wishlist_settings_profile: {
      payload: Prisma.$wishlist_settings_profilePayload<ExtArgs>
      fields: Prisma.wishlist_settings_profileFieldRefs
      operations: {
        findUnique: {
          args: Prisma.wishlist_settings_profileFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_settings_profilePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.wishlist_settings_profileFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_settings_profilePayload>
        }
        findFirst: {
          args: Prisma.wishlist_settings_profileFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_settings_profilePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.wishlist_settings_profileFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_settings_profilePayload>
        }
        findMany: {
          args: Prisma.wishlist_settings_profileFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_settings_profilePayload>[]
        }
        create: {
          args: Prisma.wishlist_settings_profileCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_settings_profilePayload>
        }
        createMany: {
          args: Prisma.wishlist_settings_profileCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.wishlist_settings_profileCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_settings_profilePayload>[]
        }
        delete: {
          args: Prisma.wishlist_settings_profileDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_settings_profilePayload>
        }
        update: {
          args: Prisma.wishlist_settings_profileUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_settings_profilePayload>
        }
        deleteMany: {
          args: Prisma.wishlist_settings_profileDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.wishlist_settings_profileUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.wishlist_settings_profileUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_settings_profilePayload>[]
        }
        upsert: {
          args: Prisma.wishlist_settings_profileUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$wishlist_settings_profilePayload>
        }
        aggregate: {
          args: Prisma.Wishlist_settings_profileAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateWishlist_settings_profile>
        }
        groupBy: {
          args: Prisma.wishlist_settings_profileGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Wishlist_settings_profileGroupByOutputType>[]
        }
        count: {
          args: Prisma.wishlist_settings_profileCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Wishlist_settings_profileCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const StoresScalarFieldEnum = {
  shop: 'shop',
  isActive: 'isActive',
  installedAt: 'installedAt',
  updatedAt: 'updatedAt'
} as const

export type StoresScalarFieldEnum = (typeof StoresScalarFieldEnum)[keyof typeof StoresScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  content: 'content',
  shop: 'shop'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const Store_settingsScalarFieldEnum = {
  id: 'id',
  shop: 'shop',
  iconEnabled: 'iconEnabled',
  showOnCollectionPages: 'showOnCollectionPages',
  showOnHomePage: 'showOnHomePage',
  showOnProductImage: 'showOnProductImage',
  autoInjectHeaderIcon: 'autoInjectHeaderIcon',
  heartColor: 'heartColor',
  iconPositionX: 'iconPositionX',
  iconPositionY: 'iconPositionY',
  pageTitle: 'pageTitle',
  emptyStateTitle: 'emptyStateTitle',
  emptyStateBody: 'emptyStateBody',
  floatingButtonEnabled: 'floatingButtonEnabled',
  floatingButtonText: 'floatingButtonText',
  floatingButtonPosition: 'floatingButtonPosition',
  addButtonEnabled: 'addButtonEnabled',
  addButtonText: 'addButtonText',
  removeButtonText: 'removeButtonText',
  showPrices: 'showPrices',
  showAddToCart: 'showAddToCart',
  requireLogin: 'requireLogin',
  onlyInStock: 'onlyInStock',
  excludedTags: 'excludedTags',
  customCss: 'customCss',
  setupEmbedConfirmed: 'setupEmbedConfirmed',
  customizedAt: 'customizedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  settingsProfileId: 'settingsProfileId'
} as const

export type Store_settingsScalarFieldEnum = (typeof Store_settingsScalarFieldEnum)[keyof typeof Store_settingsScalarFieldEnum]


export const WishlistScalarFieldEnum = {
  id: 'id',
  shop: 'shop',
  key: 'key',
  customerId: 'customerId',
  visitorId: 'visitorId',
  email: 'email',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WishlistScalarFieldEnum = (typeof WishlistScalarFieldEnum)[keyof typeof WishlistScalarFieldEnum]


export const Wishlist_itemScalarFieldEnum = {
  id: 'id',
  wishlistId: 'wishlistId',
  productId: 'productId',
  variantId: 'variantId',
  productHandle: 'productHandle',
  title: 'title',
  variantTitle: 'variantTitle',
  productUrl: 'productUrl',
  imageUrl: 'imageUrl',
  imageAlt: 'imageAlt',
  price: 'price',
  currency: 'currency',
  available: 'available',
  addedAt: 'addedAt',
  updatedAt: 'updatedAt'
} as const

export type Wishlist_itemScalarFieldEnum = (typeof Wishlist_itemScalarFieldEnum)[keyof typeof Wishlist_itemScalarFieldEnum]


export const Wishlist_eventScalarFieldEnum = {
  id: 'id',
  shop: 'shop',
  wishlistId: 'wishlistId',
  type: 'type',
  productId: 'productId',
  variantId: 'variantId',
  value: 'value',
  createdAt: 'createdAt'
} as const

export type Wishlist_eventScalarFieldEnum = (typeof Wishlist_eventScalarFieldEnum)[keyof typeof Wishlist_eventScalarFieldEnum]


export const Wishlist_sync_operationScalarFieldEnum = {
  id: 'id',
  shop: 'shop',
  operationId: 'operationId',
  action: 'action',
  createdAt: 'createdAt',
  completedAt: 'completedAt'
} as const

export type Wishlist_sync_operationScalarFieldEnum = (typeof Wishlist_sync_operationScalarFieldEnum)[keyof typeof Wishlist_sync_operationScalarFieldEnum]


export const Wishlist_settings_profileScalarFieldEnum = {
  id: 'id',
  fingerprint: 'fingerprint',
  settings: 'settings',
  createdAt: 'createdAt'
} as const

export type Wishlist_settings_profileScalarFieldEnum = (typeof Wishlist_settings_profileScalarFieldEnum)[keyof typeof Wishlist_settings_profileScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'Decimal'
 */
export type DecimalFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Decimal'>
    


/**
 * Reference to a field of type 'Decimal[]'
 */
export type ListDecimalFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Decimal[]'>
    


/**
 * Reference to a field of type 'Json'
 */
export type JsonFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Json'>
    


/**
 * Reference to a field of type 'QueryMode'
 */
export type EnumQueryModeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'QueryMode'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
  /**
   * Optional maximum size for the query plan cache. If not provided, a default size will be used.
   * A value of `0` can be used to disable the cache entirely. A higher cache size can improve
   * performance for applications that execute a large number of unique queries, while a smaller
   * cache size can reduce memory usage.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   queryPlanCacheMaxSize: 100,
   * })
   * ```
   */
  queryPlanCacheMaxSize?: number
}
export type GlobalOmitConfig = {
  stores?: Prisma.storesOmit
  session?: Prisma.sessionOmit
  store_settings?: Prisma.store_settingsOmit
  wishlist?: Prisma.wishlistOmit
  wishlist_item?: Prisma.wishlist_itemOmit
  wishlist_event?: Prisma.wishlist_eventOmit
  wishlist_sync_operation?: Prisma.wishlist_sync_operationOmit
  wishlist_settings_profile?: Prisma.wishlist_settings_profileOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

